### ISSUE TITLE
[🚀 Request] Access to Extension README page?

### ISSUE THREAD

**Issue by NevEinsit** [redhat-developer/vscode-extension-tester#1031]
### Describe the request

Hello,

This is actually more like a question.
Do we have any support to the README page of extensions? (See below). The editor title can be found but I cannot access the content of it. It seems to be WebView (similar to https://marketplace.visualstudio.com/items?itemName=ms-python.python) but cannot access by locators.
![extension_README](https://github.com/redhat-developer/vscode-extension-tester/assets/56264258/ec759a1f-9bc3-431c-b9fc-003a8d2b5dde)

Much appreciated!

### Usage

As a tester, I want to make sure that the extension README contains important information (introduction, requirements, license compliance, etc.)

**Comment by djelinek** [comment]
Hello @NevEinsit, thank you for bringing up this issue. Actually that is good one and it should be possible, but I am not 100% sure, because we are not testing that at the moment.

I will take a look closer and get back to you soon!
