### ISSUE TITLE
[🚫 Bug] `fail-zero` flag in `.mocharc.json` is not respected

### ISSUE THREAD

**Issue by EcksDy** [redhat-developer/vscode-extension-tester#1053]
### Describe the bug

When no tests are found, the `fail-zero` flag in specified `.mocharc.json` is not respected, and process still does exit 0, although no tests were found.
[Logs can be found in the Test OS Ubuntu-latest - VSCode latest step.](https://github.com/EcksDy/vscode-env-switcher/actions/runs/7279883973/job/19837124687)

P.S.
Test file exists, but no tests are found because of another unrelated issue with my build step. I've completely missed it because I was sure everything is alright since the tests pipeline was green 🤦‍♂️
I want to make sure that whenever no tests are found(files/tests), the ui-test fails.

### Steps to reproduce

```Shell
1. Checkout: https://github.com/EcksDy/vscode-env-switcher/tree/fix-not-failing-when-no-tests-run
2. Run `npm run install:all`
3. Run `npm run ui-test`
```

### Logs

```Shell
Extension 'env-switcher-0.5.2.vsix' was successfully installed.
Loading mocha configuration from ./src/ui-test/setup/.mocharc.json


  0 passing (1ms)

... exit 0
```

### Operating System

Windows 10, WSL 2, Ubuntu 20.04

### Visual Studio Code

1.85.0

### vscode-extension-tester

5.10.0

### NodeJS

v18.13.0

### npm

8.19.3

**Comment by djelinek** [comment]
Hello, thank you for reporting this issue. 

I have tested with `.mochaarc.json` and I can confirm it is not working as expected. Currently I do not completely understand why.. but I would expect more upstream problem with Mocha itself.

anyway.. in ExTester project tests we are relying on JS format of that config file (`.mochaarc.js`) and I have tested that with that it is working as expected. You can see content of configuration below.

```js
module.exports = {
	timeout: 10000,
	failZero: true
};

```

could you please also try another kind of mocha configuration?

**Comment by djelinek** [comment]
closing, feel free to reopen or just continue in the thread here in case of more questions.
