### ISSUE TITLE
[🚀 Request] Support for newer node versions

### ISSUE THREAD

**Issue by ronsig** [redhat-developer/vscode-extension-tester#1106]
### Describe the request

Can support for node 20+ be added?
Thanks

### Usage

We're trying to test our extension, which opens webviewsand uses Angular17.
This leaves us in a precarious place, since A17 has node version ^18.13.0 || ^20.9.0, and the tester has node <=18.15

This means that when A18 comes out in 05/24, we'll probabaly be either blocked from upgrading, or have to stop using the tester.

**Comment by apupier** [comment]
duplicates https://github.com/redhat-developer/vscode-extension-tester/issues/975

Several failed attempts so far to do the upgrade.

**Comment by ronsig** [comment]
Thanks. Hope it gets resolved soon

**Comment by djelinek** [comment]
closing --> Duplicate issue
