### ISSUE TITLE
[🚫 Bug] windowControls seems not working

### ISSUE THREAD

**Issue by NevEinsit** [redhat-developer/vscode-extension-tester#1117]
### Describe the bug

Hello,

We tried to maximize the VSCode instance because we need TitleBarItems that are not visible in a normal sized VSCode instance. But we found that we cannot maximize the VSCode instance by the control.

Please see more details in steps to reproduce. Thanks!

### Steps to reproduce

```Shell
Code snippet:
`
const controls = new TitleBar().getWindowControls();
await controls.restore();
await new Promise((f) => setTimeout(f, 3000));
await controls.maximize();
await new Promise((f) => setTimeout(f, 3000));
await controls.restore();
await new Promise((f) => setTimeout(f, 3000));
await controls.maximize();
await new Promise((f) => setTimeout(f, 3000));
`
While running the test, observe the VSCode test instance, it's not resized. But I can still click on the buttons to perform maximize and restore manually.
```

### Logs

```Shell
Window is not maximized
Window is already maximized
Window is not maximized
Window is already maximized
```

### Operating System

Windows 10, Ubuntu 22.04

### Visual Studio Code

1.85.0

### vscode-extension-tester

7.0.0

### NodeJS

18.15.0

**Comment by djelinek** [comment]
unfortunately this cannot be fixed 🙁 . The Window Control is no more available in a DOM of Visual Studio Code at all.

The `WindowControls` page object will be deprecated.
