### ISSUE TITLE
Update Notification.dismiss locator

### ISSUE THREAD

**Issue by mlorinc** [redhat-developer/vscode-extension-tester#112]
After 1.45.0 update, notification close button does not have `codicon-close` class.

New html structure of close button:
```html
<li class="action-item" role="presentation">
    <a class="action-label codicon codicon-notifications-clear" role="button" tabindex="0" title="Clear Notification (Delete)"></a>
</li>
```

**Comment by jrichter1** [comment]
You mean https://github.com/redhat-developer/vscode-extension-tester/commit/10773969bc510a73aad3d7202bea688f1bb94d90 ?
If you're on 3.0.0, you should already get the updated locators. If not, try regenerating your package-lock.

**Comment by jrichter1** [comment]
Sorry, I can't read properly. Let me check.
