### ISSUE TITLE
Test the source control?

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#116]
Is it possible to write UI tests for the source control?

I'd like to specifically check if the correct file entries show up in my source control view, whether the diffs show up in the gutter and if clicking on the gutter opens the diff view with the correct commands. I've looked into the wiki and glanced over the source code, but couldn't find anything.

**Comment by jrichter1** [comment]
There is no page object implemented for SCM view, yet. As of now your best bet is to use simple webdriver, until somebody gets around to implement this.

**Comment by jrichter1** [comment]
ScmView page object is now available
