### ISSUE TITLE
[🚫 Bug]  Output of the terminal not being added to the `terminal.log` file

### ISSUE THREAD

**Issue by andreriesco** [redhat-developer/vscode-extension-tester#1179]
### Describe the bug

Hello,

When running my tests the output shown on the terminal is not being written to the `terminal.log` file, which is exists on the logs folder (`/tmp/test-resources/settings/logs/20240307T150303`) but is empty.

### Steps to reproduce

Here is the test that I am running, which is at `src/tests/:

```Shell


import { assert } from 'chai';
// import the webdriver and the high level browser wrapper
import { VSBrowser, WebDriver } from 'vscode-extension-tester';

// Create a Mocha suite
describe('My Test Suite', () => {
    let browser: VSBrowser;
    let driver: WebDriver;

    // initialize the browser and webdriver
    before(async () => {
        browser = VSBrowser.instance;
        driver = browser.driver;
    });

    // test whatever we want using webdriver,
    // here we are just checking the page title
    it('My Test Case', async () => {
        const title = await driver.getTitle();
        assert.equal(title, 'Welcome - Visual Studio Code');
    });
});
```

The command that I am using:
```
node node_modules/vscode-extension-tester/out/cli.js setup-and-run -c 1.86.2 -e dotvscode 'out/tests/*.js'
```

And the output in the bash terminal:
```
> myext@2.4.2 pack
> vsce package --target linux-x64

Executing prepublish script 'npm run vscode:prepublish'...

> myext@2.4.2 vscode:prepublish
> npm run compile


> myext@2.4.2 compile
> tsc -p ./

This extension consists of 9082 files, out of which 845 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /home/andreriesco/Documents/myext/myext-linux-x64-2.4.2.vsix (9082 files, 12.71MB)
Downloading VS Code: 1.86.2 / stable
VS Code exists in local cache, skipping download
ChromeDriver 118.0.5993.70 exists in local cache, skipping download
Executing prepublish script 'npm run vscode:prepublish'...

> myext@2.4.2 vscode:prepublish
> npm run compile


> myext@2.4.2 compile
> tsc -p ./

This extension consists of 9082 files, out of which 845 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 DONE  Packaged: /home/andreriesco/Documents/myext/myext-2.4.2.vsix (9082 files, 12.71MB)
Installing extensions...
(node:68499) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'myext-2.4.2.vsix' was successfully installed.
Loading mocha configuration from /home/andreriesco/Documents/myext/.mocharc.js
Cloning into '/home/andreriesco/.myexttest'...
done.
Project templates clone OK


Writing code settings to /tmp/test-resources/settings/User/settings.json
Launching browser...
Browser ready in 4204 ms
Launching tests...
  My Test Suite
    OK My Test Case

Shutting down the browser

  1 passing (5s)
```

### Logs

There isn't any log of error presented in the terminal, but in the end the `terminal.log` file is empty.

### Operating System

Ubuntu 22.04

### Visual Studio Code

1.86.2

### vscode-extension-tester

7.2.0

### NodeJS

18.15.0

### npm

9.5.0

**Comment by djelinek** [comment]
Hello, logs presented in `/tmp/test-resources/settings/logs` are outputs for VS Code instance views, terminals, outputs etc..

So if you are expecting some output there.. first of all you need to execute something inside integrated terminal in VS Code testing instance during tests.

For now I am closing this issue because it is not bug, we are not saving output of test run in terminal. Feel free to open request or comment with further questions 🙂

**Comment by andreriesco** [comment]
Makes sense. Is there any method I can use to get this output presented on the terminal also saved on a file? At least this part of the results of each test
```
Launching browser...
Browser ready in 4204 ms
Launching tests...
  My Test Suite
    OK My Test Case

Shutting down the browser

  1 passing (5s)
```

**Comment by djelinek** [comment]
> Makes sense @djelinek . Is there any method I can use to get this output presented on the terminal also saved on a file? At least this part of the results of each test
> 
> ```
> Launching browser...
> Browser ready in 4204 ms
> Launching tests...
>   My Test Suite
>     OK My Test Case
> 
> Shutting down the browser
> 
>   1 passing (5s)
> ```

you can take a look if there is some existing [Mocha reporter](https://mochajs.org/#reporters) which suits you.. or you can try to provide your own custom Mocha reporter and then reuse it using [Mocha config](https://mochajs.org/#configuring-mocha-nodejs) file provided to ExTester.

or you can just to use power of cmd tools eg using `tee`
```
extest setup-and-run './out/ui-test/*-test.js'  --extensions_dir .test-extensions | tee uitest-report.log
```
