### ISSUE TITLE
How to open an editor tab's context menu?

### ISSUE THREAD

**Issue by uozuAho** [redhat-developer/vscode-extension-tester#118]
Hi, sorry if this is in the docs somewhere, but I couldn't find it 😢 

I've tried `editor (TextEditor).openContextMenu()`, and `EditorView` doesn't seem to have that method.

Just for clarity, here's the context menu I'd like to open:

![image](https://user-images.githubusercontent.com/2265109/82795948-1a432300-9eb8-11ea-9483-8098ab38fa29.png)

**Comment by jrichter1** [comment]
Not your fault, it's not there. I'll add it for the next version.

**Comment by uozuAho** [comment]
> Not your fault, it's not there. I'll add it for the next version.

Wow, thanks! For the fast response, and in advance for adding the feature 👍

**Comment by devipv02** [comment]
Is there a hack to use context menu on macOS? I see it's a native dialog, would like to know if there is a way to use it

**Comment by jrichter1** [comment]
> Is there a hack to use context menu on macOS? I see it's a native dialog, would like to know if there is a way to use it

Don't know any, sadly. There usually is a workaround, like using the command palette instead, but nothing to navigate the context menu.

**Comment by uozuAho** [comment]
I'm using the new `getTab()` feature documented here: https://github.com/redhat-developer/vscode-extension-tester/wiki/EditorView . Working well, thanks! 👍 Let me know if you want me to close the issue.
