### ISSUE TITLE
[🚫 Bug] Sending Alt+* seems not to be working

### ISSUE THREAD

**Issue by tzAcee** [redhat-developer/vscode-extension-tester#1190]
### Describe the bug

Chording the Alt key with something else seems to send Ctrl+Shift+* instead of Alt+*.

I have tried to replace Key.ALT with Key.CONTROL or Key.SHIFT instead, but this also does not make the Alt chording to work.

In my use-case I wanted to call the combination Alt+x, which always resolved in Ctrl+Shift+X which opens the extension view.

### Steps to reproduce

```Shell
Execute the Following (under linux):
    // Send Alt+X
    await VSBrowser.instance.driver.actions()
    .sendKeys(Key.chord(Key.ALT, "x"))
    .perform();

To verify that Ctrl+Shift+* is sent instead, try to chord Key.ALT with "s" which than opens the save as dialog.
```

### Logs

```Shell
- (afaik) no relevant logs
```

### Operating System

Ubuntu 23.10

### Visual Studio Code

1.87.2

### vscode-extension-tester

7.2.0

### NodeJS

18.13.0

### npm

9.2.0

**Comment by djelinek** [comment]
Hello, if this is making problems, it must probably come from `selenium-webdriver` package which these actions comes from.. anyway.. can you try if one of these options will solve your issue please?

`await VSBrowser.instance.driver.actions().sendKeys(Key.chord(Key.ALT, 'x'));`

or 

`await VSBrowser.instance.driver.actions().keyDown(Key.ALT).sendKeys('x').perform();`


also it depends where or on which element are you trying to execute this shortcut?

**Comment by tzAcee** [comment]
@djelinek Thanks for your answer! Both of these options are not working, unfortunately.

Im trying to call this on an editor. The test-code looks like this:

```JavaScript  
it('Extension can be activated by "Alt+X"', async () => {
    await vsController.openNewEmptyFile();
    // Check if an editor with untitled document is open
    const editorView = new EditorView();
    const titles = await editorView.getOpenEditorTitles();
    const untitledEditor = titles.find((title)=>title.startsWith("Untitled-"));
    assert(untitledEditor != undefined);
    const editor = await new EditorView().openEditor(untitledEditor as string);
    await editor.wait();
    // Send Alt+X
    //await VSBrowser.instance.driver.actions().keyDown(Key.ALT).pause(100).keyUp(Key.ALT).perform();
    await VSBrowser.instance.driver.actions().keyDown(Key.ALT).sendKeys('x').perform();

    await editorView.closeAllEditors();
  });
```

**Comment by tzAcee** [comment]
I've found a workaround, but this is the nastiest thing in existence :dagger:  (release Shift+Ctrl after pressing Alt):

`await VSBrowser.instance.driver.actions().keyDown(Key.ALT).keyUp(Key.CONTROL).keyUp(Key.SHIFT).sendKeys("x").perform();`
