### ISSUE TITLE
[🚫 Bug] Dialog Pushbutton Not Working

### ISSUE THREAD

**Issue by vaisakhkannan** [redhat-developer/vscode-extension-tester#1195]
### Describe the bug

As mentioned in the link [Push a button](https://github.com/redhat-developer/vscode-extension-tester/wiki/ModalDialog#push-a-button) , I am unable to execute the command `await dialog.pushButton('Save All');`. However, commands such as `dialog.getMessage()`, `dialog.getDetails()`, and `dialog.getButtons()` are functioning correctly. Upon debugging, it was discovered that the push button function is causing the failure.

This is code that is causing the issue.

```
pushButton(title) {
        return __awaiter(this, void 0, void 0, function* () {
            const buttons = yield this.getButtons();
            const titles = yield Promise.all(buttons.map((btn) => __awaiter(this, void 0, void 0, function* () { 
                return btn.getAttribute('title'); 
            })));
            const index = titles.findIndex(value => value === title);
            if (index > -1) {
                yield buttons[index].click();
            }
        });
    }
```

In the given code snippet, the titles are not being retrieved. Therefore, the button index cannot be found to perform a click.

### Steps to reproduce

```Shell
My Test code below

describe('Clear Command History', () => {
  let dialog: ModalDialog;
  
  before(async () => {
      await new Workbench().executeCommand('Clear Command History');
      dialog = new ModalDialog();
  });

  // now we can check what the dialog says
  it('Get the message', async () => {
      const message = await dialog.getMessage();

      expect(message).contains('Do you want to clear the history of recently used commands?');
  });

  // and the additional details
  it('Get the details', async () => {
      const details = await dialog.getDetails();

      expect(details).equals(`This action is irreversible!`);
  });

  // we can also find and use the buttons on the dialog
  it('Use the buttons', async () => {
      const buttons =  await dialog.getButtons();
      expect(buttons.length).equals(2);
      await dialog.pushButton('Clear');
  });
});
```

### Logs

```Shell
no relevant logs
```

### Operating System

Mac OS 14.2.1

### Visual Studio Code

Version: 1.87.2 (Universal)

### vscode-extension-tester

7.1.0

### NodeJS

18.15.0

### npm

9.5.0

**Comment by djelinek** [comment]
Hello, thank you for reporting this issue!

The fix will come with another release of ExTester this week 🙂 

https://github.com/redhat-developer/vscode-extension-tester/pull/1167/commits/1b19e8d49b73453f17ca05f1fe90902e7c74b99c
