### ISSUE TITLE
[🚀 Request] How to send text to TreeItem

### ISSUE THREAD

**Issue by NevEinsit** [redhat-developer/vscode-extension-tester#1206]
### Describe the request

Hello,

We are currently writing a text about creating/renaming files in the explorer view. The way we do it is to use the context menu on a TreeItem and click on the new file/folder or rename option. We can find the newly created item as a child item under the tree, but cannot proceed with inputting text as its name.

```
...
// const "parentFolder" is the parent folder where we want to create the new file
const parentFolder = await workspace.findChildItem("parent");
const menu = await parentFolder!.openContextMenu();
const op = await menu.getItem("New File...");
await op!.click();
const newFile = await parentFolder!.getChildren()[0]; // The new file is the first item under parent folder
await newFile.sendKeys("newFileName.txt") // Error, element not interactable
```
![image](https://github.com/redhat-developer/vscode-extension-tester/assets/56264258/f0fe0e15-cdcf-4d41-a661-0c5736eeefeb)

Is there a way to do this?

Thanks!

### Usage

We want to achieve file manipulation under the explorer view.

**Comment by pospisilf** [comment]
You're getting error because assigning newFile is not necessary. You can call directly sendKeys on active view. Also it's necessary to add enter on the end of filename. Something like this should be working: 
```
const parentFolder = await workspace.findChildItem("parent");
const menu = await parentFolder!.openContextMenu();
const op = await menu.getItem("New File...");
await op!.click();
await workspace.getDriver().actions().sendKeys("newFileName.txt" + Key.ENTER).perform();
```
