### ISSUE TITLE
[🚫 Bug] Setting.setValue() does not work for combo box

### ISSUE THREAD

**Issue by ronsig** [redhat-developer/vscode-extension-tester#1243]
### Describe the bug

This used to work before.
I try to set a value to a combo box field - e.g. `Files->Auto Save` or `Editor->Cursor Style`
I'm able to locate the setting using 
`let setting = await settingsEditor.findSetting('Auto Save', 'Files');`

However, calling `await setting.setValue("afterDelay");` shows me the combo box opening, but the value is not set.
![image](https://github.com/redhat-developer/vscode-extension-tester/assets/13620715/917a0f2f-7bd0-4baf-887c-d5b10f048494)
I also tried using `await setting.sendKeys("a");`, but got an "not interactable" error.

Similarly, `await setting.getValue()` always returns an empty string, regardless of which setting the combo box has.
I tried adding short delays or repatign the action - but this had no effect.
Note that `setValue() `appears to function ok for text fields (e.g. "Auto Save Delay")

### Steps to reproduce

```Shell
1. run
let setting = await settingsEditor.findSetting('Auto Save', 'Files');
await setting.setValue("afterDelay"); 

2. you will see the combo box opening, but its value is not modified
```

### Logs

```Shell
no errors are thrown
```

### Operating System

Windows 10

### Visual Studio Code

1.88.0

### vscode-extension-tester

7.1.0. Also tried 8.0.2

### NodeJS

18.13

### npm

8.19.3

**Comment by djelinek** [comment]
Hello @ronsig , thank you for reaching to us!

did you tried to get setting as ComboSetting? could you please try with

`let setting = await settingsEditor.findSetting('Auto Save', 'Files') as ComboSetting;`

other should remain same as you have.

**Comment by ronsig** [comment]
Hi @djelinek,
I tried casting as CobmboSetting, as suggested. Works ok now.
Thanks!

Ron

**Comment by ronsig** [comment]
Hi @djelinek,

Please note that after upgrading to 8.2.0 I now see a degradation. 
By the time `await settingsEditor.findSetting('Auto Save', 'Files') as ComboSetting;`  returns, the setting may not have loaded yet
I had to implement a do-while loop. It usually takes 0-5 attempts until the setting is retrieved and I can modify it.
Here's what I used:
```
    let count = 0;
    do {
        let setting = await settingsEditor.findSetting('Auto Save', 'Files') as ComboSetting;
        if(setting) {
            await setting.setValue(state);
            break;
        }
        count++;
    } while (count < 10);
```

**Comment by djelinek** [comment]
> Hi @djelinek,
> 
> Please note that after upgrading to 8.2.0 I now see a degradation. By the time `await settingsEditor.findSetting('Auto Save', 'Files') as ComboSetting;` returns, the setting may not have loaded yet I had to implement a do-while loop. It usually takes 0-5 attempts until the setting is retrieved and I can modify it. Here's what I used:
> 
> ```
>     let count = 0;
>     do {
>         let setting = await settingsEditor.findSetting('Auto Save', 'Files') as ComboSetting;
>         if(setting) {
>             await setting.setValue(state);
>             break;
>         }
>         count++;
>     } while (count < 10);
> ```

Hello @ronsig , thank you for the feedback. I can happen, I will investigate the `findSetting` method further and improve a bit waitings there.

For now I would suggest you to not use `do/while` structure, but instead rely on driver.wait method which allows you to implement a dynamic waitings for these kind of possible flaky dynamic waiting elements..

```typescript
let setting = await editor.getDriver().wait(async () => {
	return await editor.findSetting('Title Bar Style', 'Window') as ComboSetting;
}, 10_000); // keep trying for 10 seconds
await setting.setValue(state);
```

the code above will try to find settings till result is something else than `undefined`. It can be resolved any time during set timeout (eg. 10_000ms) or it will fail after set timeout if the return value is still `false / undefined`

**Comment by djelinek** [comment]
> Hi @djelinek, I tried casting as CobmboSetting, as suggested. Works ok now. Thanks!
> 
> Ron

closing as resolved at the moment
