### ISSUE TITLE
SyntaxError: manifest.json: Unexpected token : in JSON at position 3

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-extension-tester#127]
Manifest.json URL has changed - CodeUtil throws an error when downloading VSCode.
Latest 1.46.0 revision of VSCode has changed path to the cgmanifest.json file.

[The code here] cannot find file there and so the content of the manifest is "404: Not Found".

Actual [url] for the above mentioned revision...

[The code here]: https://github.com/redhat-developer/vscode-extension-tester/blob/62112e853b7d4eda6b94c4266686cb7863201ba2/src/util/codeUtil.ts#L225
[url]: https://raw.githubusercontent.com/microsoft/vscode/release/1.46/cgmanifest.json

**Comment by jrichter1** [comment]
Yeah, somebody decided to rename all the release branches.

Anyway, patch 3.0.2 is out, should work with the new vscode.
