### ISSUE TITLE
Setting up Environment Fails when running behind a proxy

### ISSUE THREAD

**Issue by alii-gator** [redhat-developer/vscode-extension-tester#128]
Version `3.0.1`

I noticed that execution of the tests fails when connected to a proxy.
The process fails at `Installing extensions...`, it's even before reaching the test step.

I have already configured npm proxy. When i turn off the proxy the execution is completed successfully. The Tests are completely local. I wonder why the proxy is creating an issue

These logs might help
```
13 verbose stack Error:test-vscode-e2e-tests@1.0.0 test: `extest run-tests out/ui-test/*.js `
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by jrichter1** [comment]
This is quite surprising. All the steps that actually download data run fine, but then it fails on installing a local file into vscode.

TBH I don't know what is going on under the hood (this is just a CLI call to vscode), so I'm not sure if there is a way out of this.

**Comment by alii-gator** [comment]
@jrichter1 so it seems like its more of a problem on VS Code side. so i will close this issue.
Thanks.
