### ISSUE TITLE
[🚫 Bug] Wait periods needed to make sure tree items are loaded

### ISSUE THREAD

**Issue by ronsig** [redhat-developer/vscode-extension-tester#1320]
### Describe the bug

I often seem to need to add wait periods when loading elements, in order to make sure my extension's prjeuct view is loaded and expanded.

For example 
```
 await VSBrowser.instance.openResources(testWorkspacePath);
 await (await new ActivityBar().getViewControl(generalHelpers.TestConstants.VIEW_CONTAINER_TITLE))?.openView();
 // now to initialize the view
 const view = new SideBarView();
 content = view.getContent();
 let tree = await content.getSection("Structure");
 await new Promise(res => setTimeout(res, 300));  <--- I had to add this to make sure the tree was indeed instantiated
 await tree.expand();
```

I often encounter elements that are created, but I have to artificially add wait periods, so they finish loading their content. I can't use wait(until.elementLocated() since the element is there and can be located, but is not fully loaded

### Steps to reproduce

```Shell
This happens in my extension's project view, so I don't have steps beyond the above
```

### Logs

```Shell
None. Without the wait period, I get "undefined" when trying to access content of elements not fullly loaded
```

### Operating System

Windows 10

### Visual Studio Code

1.89.1

### vscode-extension-tester

8.0.2

### NodeJS

18.13

### npm

8.19.3

**Comment by djelinek** [comment]
Hello @ronsig , thank you for opening an issue! 

This is a hard to catch everywhere. We are still trying to keep ExTester more like API to allow users interaction than solve everything to make ExTester heavy and slow. But I am not saying there is not still a lot of space to improve or that there is maybe some missing timeout..

Those timeouts and waitings are still in many cases better to implement on side of tests..

Anyway, to your issue specifically, I would suggest to more use dynamic waits using driver to avoid 
1. static waitings
2. it is really a customisable thingy

could you please try to eg use something like example below? it should allow you to wait for elements properly loaded and then you can call any operations for each item.

```typescript
await content.getDriver().wait(
	async () => {
		const items = await section.getVisibleItems();
		return items.length > 0;
	},
	5_000,
	'View items were not properly loaded in 5 seconds...',
);
```

**Comment by djelinek** [comment]
closing, feel free to reopen or just continue in the thread here in case of more questions.
