### ISSUE TITLE
tested extension reuses  present node_modules

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#133]
I have made a very silly mistake in an extension that I am developing: I have added `node_modules` to the `.vscodeignore` file and thus the `.vsix` does not contain the dependencies (and fails to even load for obvious reasons). I would have expected that vscode-extension-tester would have caught this issue, but it didn't.

I have tried to reproduce this again and if I explicitly exclude `node_modules` from the `vsix`, then vscode-extension-tester will indeed create a package without the dependencies. Nevertheless, the extension tests still pass, which leads me to believe that the running vscode instance somehow inherits/shares the `node_modules`? Would it be possible to somehow not do that? Thereby one could catch stupid mistakes like mine or less stupid ones like accidentally specifying a runtime dependency in `devDependencies`.

**Comment by jrichter1** [comment]
I'm not experiencing this problem. When a dependency is missing from the vsix, it always fails to activate, therefore the tests fail.

To be clear, I've removed both `node_modules` and `package-lock.json` and reinstalled everything after modifying an extension to fit your setup. I'm also not using any globally installed packages. Am I missing something?

**Comment by dcermak** [comment]
Did you also explicitly exclude the `node_modules` via the `.vscodeignore`?

**Comment by jrichter1** [comment]
yep, then I reinstalled all packages just to have a fresh setup, and the extension refused to activate every time
