### ISSUE TITLE
Ubuntu WLS - WebDriverError: unknown error: Chrome failed to start: exited abnormally (DevToolsActivePort file doesn't exist)

### ISSUE THREAD

**Issue by Foxhoundn** [redhat-developer/vscode-extension-tester#134]
Hi,

I am having trouble running tests on Ubuntu running in WLS on Windows 10.

The error is

```
WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/foxhoundn/projects/qorus-vscode/test-resources/VSCode-linux-x64/code is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}),platform=Linux 4.4.0-18362-Microsoft x86_64)
```

It works just fine on my Mac.

Thanks for any info

**Comment by jrichter1** [comment]
I don't have any experience with WSL, so I'm assuming it pretty much is a bash only Ubuntu. Meaning there probably is no display or GUI for vscode to start in the first place, unless you have the libraries installed.

First thing I'd check is if vscode can even be launched on its own inside WSL. It might require various graphical environment libraries and most likely some form of display, like a virtual frame buffer or vnc server.

**Comment by Foxhoundn** [comment]
Hi, thanks Jan for the info.
