### ISSUE TITLE
[🚫 Bug] install-vsix fails on windows when file pattern like ./**.vsix is provided

### ISSUE THREAD

**Issue by jiri-skrivanek** [redhat-developer/vscode-extension-tester#1354]
### Describe the bug

install-vsix fails on windows when file pattern like ./**.vsix is provided. It works on unix. Related code in node_modules/vscode-extension-tester/out/extester.js is

       const uri = new url_1.URL(vsixFile);
                if (!(process.platform === 'win32' && /^\w:/.test(uri.protocol))) {
                    target = path.basename(vsixFile);
                }

### Steps to reproduce

```Shell
node node_modules/vscode-extension-tester/out/cli.js install-vsix --vsix_file ./**.vsix
```

### Logs

```Shell
Error: File ./**.vsix does not exist
    at ExTester.installVsix (D:\repo\myextension\node_modules\vscode-extension-tester\out\extester.js:87:27)
    at D:\repo\myextension\node_modules\vscode-extension-tester\out\cli.js:41:18
```

### Operating System

Windows11

### Visual Studio Code

1.90.0

### vscode-extension-tester

7.3.2

### NodeJS

20.12.2

**Comment by jiri-skrivanek** [comment]
Any ideas abut this?

**Comment by djelinek** [comment]
> Any ideas abut this?

Hello, I am starting to investigate this issue. I will let you know with my findings ASAP 🙂 

Thank you for your patience.

**Comment by jiri-skrivanek** [comment]
Any new observations?

**Comment by djelinek** [comment]
> Any new observations?

hello, I was on a PTO last week, so I will continue on that ASAP. 

At the moment I was able to reproduce on Windows VM, so I will take a look more closely into current implementation and options how to improve it
