### ISSUE TITLE
Enhancement: InputBox QuickInputButtons support

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#136]
VS Code provides a way to display buttons on the for an `InputBox`. In this case, the back button on the top left:
![image](https://user-images.githubusercontent.com/20326645/85899231-c8016480-b7cb-11ea-93e3-038cbf9e1e53.png)

`InputBox` can contain a list of `QuickInputButtons`
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bf2a6e1785dc5f702846d56c092a092b7eb485b4/types/vscode/index.d.ts#L8946

`QuickInputButtons.Back`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bf2a6e1785dc5f702846d56c092a092b7eb485b4/types/vscode/index.d.ts#L8991

It would be great if there was a built-in way to access these button(s) from my tests.

As a workaround, I have found the class name of the button I wanted (ie, `codicon-quick-input-back` in this case) and been calling `findElement(By.className('codicon-quick-input-back')`.

**Comment by jrichter1** [comment]
`Input`s got the `back` and `getTitle` methods in the last release.
