### ISSUE TITLE
Question: Is there a way to use right click (context menu) on webview

### ISSUE THREAD

**Issue by devipv02** [redhat-developer/vscode-extension-tester#147]
Hi

I have a question. Can we use right click on any element in webview. I'm able to click. Just wondering if there is a way to right click and open custom context menu.

Thank you

**Comment by jrichter1** [comment]
You can use webdriver actions for that. You will need a reference to the element you want to click on and a webdriver instance.
Could look something like this:
```typescript
await webdriver.actions().click(element, Button.RIGHT).perform();
```

**Comment by devipv02** [comment]
Thank you
