### ISSUE TITLE
Run Tests - Can't run multiple tests on Linux when they are splitted in multiple folders

### ISSUE THREAD

**Issue by yannickowow** [redhat-developer/vscode-extension-tester#150]
Hi,
I am writing tests using vscode-extensions-tester, and so I decided to split my tests in multiple folders:
In folder ui-tests, I created folders containing each a description (md) and a test (ts),
When I compile, they are as well in multiple folders (folder-name/name.js), but when I try to run this tests, only the first one is ran, according to alphabetically ordered folder name.

On Windows, it works correctly, all tests are ran.

Configuration:
```json
"name": "UI Tests",
			"type": "node",
			"request": "launch",
			"program": "${workspaceFolder}/node_modules/vscode-extension-tester/out/cli.js",
			"args": [
				"run-tests",
				"${workspaceFolder}/out/ui-tests/**/*.js",
				"-o",
				"resources/test-settings.json"
			],
			"outFiles": [
				"${workspaceFolder}/out/ui-tests/*.js"
			],
			"console": "integratedTerminal",
			"internalConsoleOptions": "neverOpen",
```
Running on RHEL7 and Windows 10 - both x64.
Thanks in advance

**Comment by jrichter1** [comment]
It seems the glob pattern is automatically being interpreted by shell before it is even passed into extest.
Try wrapping it in quotes
```
"args": [
				"run-tests",
				"'${workspaceFolder}/out/ui-tests/**/*.js'",
				"-o",
				"resources/test-settings.json"
			]
```

**Comment by yannickowow** [comment]
Thanks for your fast reply, it worked
