### ISSUE TITLE
Running multiple test suites from multiple files

### ISSUE THREAD

**Issue by Foxhoundn** [redhat-developer/vscode-extension-tester#151]
Hi!

How can we run multiple tests from multiple files?

`extest` supports only one argument so when we do `ui-test/node_modules/.bin/extest run-tests 'ui-test/out/*.js'` it tries to run all the files correctly but after the first suite is finished it shuts down the driver and uninstalls everything (even on success) and the second file crashes.

```
Writing code settings to /home/test/testing/hZhRcYQoY6eoEto8Iz2hBO0X/qorus-vscode/test-resources/settings/User/settings.json
  Config Items Tests
    ✓ Create service class (19177ms)
    ✓ Create class (15685ms)
    ✓ Create service (31659ms)
    ✓ Check files
    ✓ Open file (10786ms)
  Webview Simple Test
    1) "before all" hook for "Shows environment page"
Shutting down the browser
Uninstalling vscode-extension-tester.api-handler...
Extension 'vscode-extension-tester.api-handler' was successfully uninstalled!
  5 passing (2m)
  1 failing
  1) Webview Simple Test
       "before all" hook for "Shows environment page":
     TimeoutError: Waiting until element is visible
```

How do we prevent the driver shutdown when multiple files are ran?

Thanks!

**Comment by jrichter1** [comment]
Hi,

the log you posted suggests the second test suite is actually launched before everything shuts down. But since the `beforeAll` hook crashes with `TimeoutError`, the tests are skipped and the editor shuts down. Fixing the before all hook should help you here.

**Comment by Foxhoundn** [comment]
Hi Jan,

How can we wait for everything to shut down and run the next suite?

**Comment by Foxhoundn** [comment]
> Hi,
> 
> the log you posted suggests the second test suite is actually launched before everything shuts down. But since the `beforeAll` hook crashes with `TimeoutError`, the tests are skipped and the editor shuts down because there are no more tests to run. Fixing the before all hook should help you here.

Thanks for the quick reply!

How can we wait for everything to shut down and start the next suite?

**Comment by jrichter1** [comment]
> Thanks for the quick reply!
> 
> How can we wait for everything to shut down and start the next suite?

There is no reason to restart the environment between test suites. All the files from the glob pattern are loaded and executed sequentially. The log you posted suggests the second suite file is loaded and run before the shutdown happens.

The problem you seem to be facing is the second suite's `beforeAll` method crashes when run. When that happens, the rest of the suite is skipped. Since there probably is no other suite to run, it shuts down.

**Comment by Foxhoundn** [comment]
> > Thanks for the quick reply!
> > How can we wait for everything to shut down and start the next suite?
> 
> There is no reason to restart the environment between test suites. All the files from the glob pattern are loaded and executed sequentially. The log you posted suggests the second suite file is loaded and run before the shutdown happens.
> 
> The problem you seem to be facing is the second suite's `beforeAll` method crashes when run. When that happens, the rest of the suite is skipped. Since there probably is no other suite to run, it shuts down.

The thing is, when the second suite (webview_simple_test) is ran on it's own, it goes through just fine. It only breaks in the beforeAll hook if it's run sequentially with the other test suite.

**Comment by Foxhoundn** [comment]
Also sometimes this happens after all the tests in the first suite are done

```
Shutting down the browser
  1) "after all" hook in "{root}"

  5 passing (3m)
  1 failing

  1) "after all" hook in "{root}":
     Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

All 5 tests pass, but the after all hook crashes (we don't have any after all hook, i guess it's some kind of internal cleaning?)

**Comment by jrichter1** [comment]
Could you try a run with 2 files, where the second suite file contains only a minimal test case? Something as dumb as just `expect(true)`. That way we can definitely see if both files are run with very little chance of the second one crashing.

As for the `{root}` hooks, they are the ones that start (before) and exit (after) the browser. One of them failing like this usually means ChromeDriver has crashed unexpectedly, but that's really difficult to debug.

**Comment by Foxhoundn** [comment]
Hi @jrichter1 ,

I managed to get this all working by restructuring our tests, so thanks for your help! 

I do have another obstacle :) How can we run 2 _specific_ tests with one command? I tried the following:

`run-tests "ui-test/out/_setup.spec.js ui-test/out/test.spec.js"`
`run-tests "ui-test/out/_setup.spec.js, ui-test/out/test.spec.js"`
`run-tests "ui-test/out/{_setup, test}.spec.js"`

None of these work. I want to have a way to run a specific test, but the `_setup` test has to be run before any test (it adds the folder to the workspace etc).

Can you help?

Thanks!

**Comment by jrichter1** [comment]
`run-tests "ui-test/out/{_setup,test}.spec.js` should work. Without the space.

**Comment by Foxhoundn** [comment]
@jrichter1 ugh spaces :) Thanks!
