### ISSUE TITLE
Compatibility with VS Code lower versions

### ISSUE THREAD

**Issue by bode-jr** [redhat-developer/vscode-extension-tester#152]
I tried setting it with lower version of VS Code.

![Capture](https://user-images.githubusercontent.com/39143809/91010491-2eacce00-e615-11ea-8474-e27a83bf50d7.PNG)

**Comment by jrichter1** [comment]
The first version of VS Code that was ever supported by this project is `1.37.0`, back when extension tester was first released in a working state with all the page objects. Anything older than that will run based on pure luck.

That being said, I am no longer capable of maintaining support all the way back, so currently the plan is to support the latest 5 versions (minor versions for now, we'll see if vscode 2 ever comes out).

I will be updating the readme, so it is properly visible.

**Comment by bode-jr** [comment]
Okay, I wasn't able to read it. nevermind.. thanks
