### ISSUE TITLE
Support nested setting options

### ISSUE THREAD

**Issue by ewanharris** [redhat-developer/vscode-extension-tester#155]
In the extension I work on we tend to follow a pattern for settings values like this `<extension_name>.<area>.<key>` for example `titanium.general.logLevel`.

When using the `findSetting` API to set this I had to set the category as `Titanium › General` (e.g. `await editor.findSetting('Log Level', 'Titanium › General')`) as it seems VS Code will insert a `›` in-between the first and second value.

I'm curious as to whether you think this is maybe something that should be handled internally in vscode-extension-tester as the behaviour could be something the changes in VS Code over time? Maybe the `findSetting` function could become `async findSetting(title: string, ...categories: string[]): Promise<Setting>` and perform `categories.join(' › ')` before calling sendKeys?

Happy to file a PR to make that happen if you're happy with the suggestion

**Comment by jrichter1** [comment]
@ewanharris absolutely, go for it :)
