### ISSUE TITLE
Consider splitting ViewSection.openItem() into two different functions

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#159]
I have been recently using vscode-extension-tester to test tree views rather extensively and have found the `ViewSection.openItem()` function a bit awkward to use as it returns a Promise resolving to either `void ` or a `ViewItem[]`. After checking the source code, I see where this comes from: the function is implemented for the `TreeSection` class and for the `ExtensionsViewSection` class, where `openItem` returns an array of children for the former and nothing for the latter.

This makes the usage of this function a bit odd, because you have to either turn off strict null checks or add `!` everywhere to convince typescript that this is actually always defined, when using this on `TreeSection`s. I would propose to either unify the behavior of `openItem` to always return a `ViewItem[]` or split function into two distinct ones. How about calling the `ExtensionsViewSection`'s one `findAndClickItem()`? (it does effectively just that: find + click).

Another option would be to introduce stronger typing and somehow (TM) make the getters for the sidebar return a different type when the extension side panel is requested (albeit I have no idea whether that is even possible).

**Comment by jrichter1** [comment]
I guess the easy way would be to just have `ExtensionViewSection`'s `openItem` return an empty array. It's about as clean as anything else without completely breaking for existing users.

**Comment by jrichter1** [comment]
Fixed in page-objects 1.2.3
