### ISSUE TITLE
Flakey behavior when launching the tester

### ISSUE THREAD

**Issue by quoctruong** [redhat-developer/vscode-extension-tester#164]
I've been getting this error messages when launching the extension tester once in a while (like 1 out of 4 attempts).
```
"before all" hook in "{root}"
No message!
Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
Error: Timeout of 15000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

Any ideas on what may cause this?

**Comment by jrichter1** [comment]
I'm assuming this is a case when chromedriver gets stuck on launch. There have been numerous problems with it tied to certain environment/os configurations.

There might be some configuration out there that can help your case, but first I need to know what OS you're running on so I can test it :)

**Comment by quoctruong** [comment]
@jrichter1 This is mostly on macOS. Sometimes on a Ubuntu VM as well (16.04). My Node version is 12.16.2.

**Comment by quoctruong** [comment]
Here's the log before the crashed:
```
Extension '<redacted>.vsix' was successfully installed.
Installing extensions...
Extension 'api-handler.vsix' was successfully installed.
Loading mocha configuration from config.mocharc.json
Writing code settings to /<redacted>/test-resources/settings/User/settings.json

```

**Comment by vincentjocodes** [comment]
I'm having the same problem on macOS 10.15.6

**Comment by orlade-anz** [comment]
Same on MacOS 11.5.2, VS Code 1.59.0, `vscode-extension-tester` 4.12.

It's also flaky whether or not the extension I'm trying to test is even installed in the VS Code instance, even after `extest install-vsix`.

**Comment by brodao** [comment]
Hello everybody.
I also have this occurrence, but on Windows 10. I managed to run the test two or three times.
