### ISSUE TITLE
Yarn is now automatically used for `vsce package` instead of npm since last vsce update

### ISSUE THREAD

**Issue by Foxhoundn** [redhat-developer/vscode-extension-tester#167]
It would be great to allow for the `--no-yarn` option to be added to the `setup-tests` command. Right now it supports `-y` but that has no impact now since yarn is now the default value.

**Comment by jrichter1** [comment]
AFAIK the default use of yarn is a bug, so it should get fixed soon.  But then again `--no-yarn` would give yarn users the option not to yarn. I'll try it out.

**Comment by jrichter1** [comment]
Fixed in 3.2.1
