### ISSUE TITLE
".tab-close" is no longer a CSS class on tabs in editor, therefore `closeAllEditors()` fails

### ISSUE THREAD

**Issue by Foxhoundn** [redhat-developer/vscode-extension-tester#176]
".tab-close" is no longer a CSS class on tabs in editor, therefore `closeAllEditors()` fails

![Screenshot 2020-10-15 at 11 30 45](https://user-images.githubusercontent.com/8861481/96105061-e3f35800-0ed9-11eb-9414-12de60b4936a.png)

It seems that the CSS was changed inside VSCode.

Changing the locator to `By.className('.tab-actions .codicon-close')` should be enough to fix this? I don't think there could be 2 `.codicon-close` buttons inside the tab actions.

**Comment by Foxhoundn** [comment]
I can help with a PR if you agree with the suggested change.

**Comment by jrichter1** [comment]
this:
https://github.com/redhat-developer/vscode-extension-tester/blob/master/locators/lib/1.50.0.ts#L7

it is already released, all you need to do is make sure your `package-lock.json` doesn't enforce `vscode-extension-tester-locators` older than `1.50.0`

**Comment by Foxhoundn** [comment]
Yeah that was it, thanks.

But now when running setup tests we get `error: unknown option `--no-yarn'`, we are on `vsce 1.81.1`, I thought this has been fixed? Should we run tests setup with an additional command?

**Comment by Foxhoundn** [comment]
I was able to hack that out in the `codeUtil.js` file and setup the tests. Were there any breaking changes in `3.2.1` compared to `3.0.0`? Our `before` setup is failing with no clear message:

```
  const workbench = new Workbench();
    const editorView = new EditorView();

    await sleep(8000);

    await workbench.executeCommand('Qorus: Open Webview');

    let isWebviewOpen = false;

    while (!isWebviewOpen) {
        await sleep(1000);
        isWebviewOpen = (await editorView.getOpenEditorTitles()).includes('Qorus Webview');
    }

    await sleep(1000);

    const webview = await new WebView(editorView, 'Qorus Webview');
    await webview.wait();
    await webview.switchToFrame();

    await sleep(3000);

    return {
        workbench,
        editorView,
        webview,
    };
```

Error: 

```
 "before all" hook for "Create service class":
     TypeError: Invalid locator
      at Object.check [as checkedLocator] (ui-test/node_modules/selenium-webdriver/lib/by.js:275:9)
      at EditorView.findElement (ui-test/node_modules/selenium-webdriver/lib/webdriver.js:2048:18)
      at new AbstractElement (ui-test/node_modules/monaco-page-objects/out/components/AbstractElement.js:39:48)
      at new ElementWithContexMenu (ui-test/node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:19:1)
      at new Editor (ui-test/node_modules/monaco-page-objects/out/components/editor/Editor.js:20:9)
      at new WebView (ui-test/node_modules/monaco-page-objects/out/components/editor/WebView.js:17:1)
      at /Users/filipwitosz/Code/Projects/qorus-vscode/ui-test/out/common/utils.js:29:27
      at Generator.next (<anonymous>)
      at fulfilled (ui-test/out/common/utils.js:5:58)
```

**Comment by jrichter1** [comment]
> Yeah that was it, thanks.
> 
> But now when running setup tests we get `error: unknown option --no-yarn'`, we are on `vsce 1.81.1`, I thought this has been fixed? Should we run tests setup with an additional command?
> 
> @jrichter1 did they remove the `--no-yarn` option after they fixed the bug 2 weeks ago?

I just checked vsce 1.81.1 and `--no-yarn` is definitely still there. Can you check what version you get from `./node_modules/.bin/vsce -V`

**Comment by jrichter1** [comment]
> I was able to hack that out in the `codeUtil.js` file and setup the tests. Were there any breaking changes in `3.2.1` compared to `3.0.0`? Our `before` setup is failing with no clear message:

As far as I'm aware, the `Editor` classes, including `Webview` no longer take title as an argument in their constructors.

**Comment by Foxhoundn** [comment]
All fixed, thx Jan!
