### ISSUE TITLE
ActionSequence dragAndDrop() uses the mouse location instead of provided location

### ISSUE THREAD

**Issue by Foxhoundn** [redhat-developer/vscode-extension-tester#177]
Hi,

It seems that the `ActionSequence`'s `dragAndDrop()` uses the mouse location instead of provided location. When running the tests, the element is ^^dragged^^ but appears - and is dropped - under the mouse' position. If I manually  move the mouse above the droppable element, everything works.

The code - 
```
const mapper = await getNthElement(webview, 'fsm-toolbar-mapper');

const mapperButtonLocation = await mapper.getLocation();

await new ActionSequence(driver)
        .dragAndDrop(mapper, { x: mapperButtonLocation.x, y: mapperButtonLocation.y + 150 })
        .perform();
```

Any insight is appreaciated, thx.

**Comment by jrichter1** [comment]
Looking at the webdriver documentation, ```The target element may be moved to the location of another element, or by an offset (in pixels).``` 
It looks like you are trying to move the element to an absolute position, but the method is expecting an offset, so it might end up out of bounds. The first thing I'd try is ```dragAndDrop(mapper, { x: 0, y: 150 })```

**Comment by Foxhoundn** [comment]
That was my first try and it's the same, no matter what I put in the target location, it always ends up below the mouse.

**Comment by jrichter1** [comment]
You can also try creating a drag&drop sequence manually to see if there is any difference
```mouseDown(mapper).mouseMove(offset).mouseUp()```

**Comment by Foxhoundn** [comment]
Nope, tried that as well and it's literally the same behaviour

**Comment by Foxhoundn** [comment]
Found a way :)

![JPEG image](https://user-images.githubusercontent.com/8861481/96994856-9906bf80-152d-11eb-8363-ee2b6b1de9c5.jpeg)

It's a screenshot, but you can clearly see where the button was dragged (completely outside of the window where the mouse was).

**Comment by jrichter1** [comment]
I've looked over the selenium repo and found this: https://github.com/SeleniumHQ/selenium/issues/7744
It looks like nobody really knows for sure why this is actually happening :(

**Comment by Foxhoundn** [comment]
bummer :(

**Comment by Foxhoundn** [comment]
Ok gotta work around this, is there a way to right click on an element?

**Comment by jrichter1** [comment]
using an action sequence should do it, you will just need to import `Button`
```typescript
await new ActionSequence(driver).click(element, Button.RIGHT).perform();
```
