### ISSUE TITLE
Add wait condition for the ViewContent.hasProgress in ExtensionsViewSection.findItem

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-extension-tester#183]

**Comment by odockal** [comment]
Seems like such wait already exists: https://github.com/redhat-developer/vscode-extension-tester/blob/73804a38018142208b5077c13e0e405fdd8feeb0/page-objects/src/components/sidebar/extensions/ExtensionsViewSection.ts#L46

**Comment by jrichter1** [comment]
Soo, is this an issue after all?

**Comment by odockal** [comment]
nope
