### ISSUE TITLE
File path InputBox.setText() places wrong text during processing actual text replacement

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-extension-tester#185]
I am talking about a bit different Input Dialog, it might behave in a different way than others. It is Simple Files dialog (settings: files.simpleDialog.enable). Settings this option can invoke it. This is alternative vscode way to set file path instead of native dialog.

**Comment by jrichter1** [comment]
Should no longer misbehave in the latest release. Although if a path doesn't contain a trailing separator, the input will need to be confirmed twice.
