### ISSUE TITLE
Possibility to wait for `runTests` to finish running?

### ISSUE THREAD

**Issue by Foxhoundn** [redhat-developer/vscode-extension-tester#187]
Is there a way to programatically wait for the `runTests` function to finish?

```
(async () => {
    await Tests.runTests(`ui-test/out/{_setup,${test}}.spec.js`)
    console.log('after');
})();
```

Right now `after` is logged when the function is executed, not after the script finishes running, is there a way to make it sync?

**Comment by jrichter1** [comment]
Yep, that's a bug. Let me fix it.

**Comment by Foxhoundn** [comment]
> Yep, that's a bug. Let me fix it.
Thanks Jan!

Also right now the `runTests` returns void, is there a way to return the exit code or `$?` ?

**Comment by jrichter1** [comment]
> Also right now the `runTests` returns void, is there a way to return the exit code or `$?` ?

Yeah, why not.

**Comment by jrichter1** [comment]
Fixed and released.
