### ISSUE TITLE
ExtensionsViewItem.install() resolves before installation is complete

### ISSUE THREAD

**Issue by mlorinc** [redhat-developer/vscode-extension-tester#188]
### How to reproduce

I have prepared [test case](https://github.com/mlorinc/vscode-extensions-tester-install-demonstration/blob/master/src/extension.test.ts) which performs following steps:

1. Open marketplace
1. Find any extension (preferable large extension because small extension might be downloaded fast enough)
1. Install extension
1. Screenshot ExtensionViewItem.

Test case should create following screenshot:
![wsdl2rest](https://user-images.githubusercontent.com/22118977/99685770-3c8eb580-2a83-11eb-9bdc-844cd11a717f.png)

When I add `await new Promise(resolve => setTimeout(resolve, 60000));` right after `await wsdl2rest?.install();`, following screenshot is captured.
![wsdl2rest](https://user-images.githubusercontent.com/22118977/99686788-3947f980-2a84-11eb-99c8-713d8a61f7c6.png)

**Comment by jrichter1** [comment]
Well, the documentation says 
```
     * @returns Promise resolving when the Install button is clicked or not found at all
```
so it was intended to work this way back then. I guess you'd like it enhanced a bit :)
