### ISSUE TITLE
Take screenshots on error in beforeAll/afterAll methods

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#193]
it will be convenient to take a screenshots in beforeAll and afterAll when an error occurs

**Comment by jrichter1** [comment]
This might not be possible to do across the board. Hooks are not treated like tests in mocha, in fact the screenshot on failure function is done using hooks, and I can't find a way to hook hooks.

I'm afraid you'll have to implement this as part of your tests. You can manually take screenshots using `VSBrowser.instance.takeScreenshot(fileName)` and implement a simple wrapper that will call it on error.
