### ISSUE TITLE
Use conditional wait to retrieve the OpenDialog

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#194]
currently, there is a sleep of 4 seconds. https://github.com/redhat-developer/vscode-extension-tester/blob/860862f904ffce3c408fc79c8b8171741afc1d62/native/src/dialogHandler.ts#L15
It seems that on Circle CI, for Camel LSP client VS code, this is not always enough. To have it more robust, using a conditional wait would be better.

an intermediate step could be to provide a configurable timeout

**Comment by jrichter1** [comment]
Well, I don't have a way to check native dialogs. The configurable timeout is a possible improvement, but there is now a way around using native dialogs whatsoever. Vscode now has a setting called `Dialog Style` that lets you use `custom` dialogs instead of native. Essentially turning file pickers into input boxes.

**Comment by apupier** [comment]
> but there is now a way around using native dialogs whatsoever. Vscode now has a setting called `Dialog Style` that lets you use `custom` dialogs instead of native. Essentially turning file pickers into input boxes.

Can you provide an example to use it please?

**Comment by apupier** [comment]
> > but there is now a way around using native dialogs whatsoever. Vscode now has a setting called `Dialog Style` that lets you use `custom` dialogs instead of native. Essentially turning file pickers into input boxes.
> 
> Can you provide an example to use it please?

I tried with:

```
	const settingsEditor = await new Workbench().openSettings();
	const setting = await settingsEditor.findSetting('Dialog Style', 'Window');
	await setting.setValue('custom');
```

but it is still native dialog which is displayed

**Comment by jrichter1** [comment]
> I tried with:
> 
> ```
> 	const settingsEditor = await new Workbench().openSettings();
> 	const setting = await settingsEditor.findSetting('Dialog Style', 'Window');
> 	await setting.setValue('custom');
> ```
> 
> but it is still native dialog which is displayed

For some reason there is a second setting that needs to be checked for this to work:
`Files > Simple Dialog > Enable`

**Comment by apupier** [comment]
> For some reason there is a second setting that needs to be checked for this to work:
> `Files > Simple Dialog > Enable`

With that I can do it manually locally.
I'm unable to tick the "Enable" option through test though, tried:
```
	const filesDialogSetting = await settingsEditor.findSetting('Simple Dialog', 'Files');
	await filesDialogSetting.setValue(true);
```
![XML DSL support Auto-completion for referenced components IDs Auto-completion for referenced ID of  direct  component](https://user-images.githubusercontent.com/1105127/100236590-2888ff00-2f2e-11eb-9a44-5163813f995b.png)

but there is this error:
`TypeError: Cannot read property 'setValue' of undefined`

**Comment by jrichter1** [comment]
try
```typescript
    const filesDialogSetting = await settingsEditor.findSetting('Enable', 'Simple Dialog', 'Files');
    await filesDialogSetting.setValue(true);
```

**Comment by apupier** [comment]
> try
> 
> ```ts
>     const filesDialogSetting = await settingsEditor.findSetting('Enable', 'Simple Dialog', 'Files');
>     await filesDialogSetting.setValue(true);
> ```

same result.

I also tried `settingsEditor.findSetting('Simple Dialog', 'Files', 'Text Editor');` and `settingsEditor.findSetting('Simple Dialog', 'Text Editor', 'Files');` but in these cases in the scrennshot failure, the setting does no appear.

**Comment by jrichter1** [comment]
Yeah, I posted it in the wrong order, edited, but you were too quick.

**Comment by jrichter1** [comment]
The setting is named 'Enable', the groups are 'Files' > 'Simple Dialog', so the arguments need to be in this order
```
findSetting('Enable', 'Files', 'Simple Dialog');
```

**Comment by apupier** [comment]
> The setting is named 'Enable', the groups are 'Files' > 'Simple Dialog', so the arguments need to be in this order
> 
> ```
> findSetting('Enable', 'Files', 'Simple Dialog');
> ```

opening the inputbox for file path is now working! thanks (next step provide the correct path, previously a relative path was provided and it is was working, no more the case)

**Comment by jrichter1** [comment]
It wants an absolute path, and for some reason it prefers paths that don't start with / on unix. I'm still trying to figure that out.

**Comment by jrichter1** [comment]
I've added at least a variable delay for the open dialog. Now that simple dialog should be usable, I think it will make for much easier time than the native one.
