### ISSUE TITLE
Methods 'findItem' and 'getVisibleItems' in ExtensionsViewSection return wrong results

### ISSUE THREAD

**Issue by Majdos** [redhat-developer/vscode-extension-tester#20]
### Description

Methods `findItem` and `getVisibleItems` in **ExtensionsViewSection** are not working because of bad locator.

1. `findItem` function always contains right title but wrong data which belongs to first extension in view.
2. `getVisibleItems` returns list of extensions. Titles are right but other data such as description, author, etc belongs to first extension in view.

### Potencial cause

Locator: `.//div[contains(@class, 'monaco-list-row') and .//span/text()='${title}']`

Locator should be looking for div which has `monaco-list-row` class, instead it finds `monaco-list-rows` and breaks methods which are based on `monaco-list-row` element.
 
### Note

Please note, other locators might have similar issues.

**Comment by jrichter1** [comment]
Thanks for the contribution @Majdos
