### ISSUE TITLE
Chromedriver stops immediately after launch with vscode 1.51.0 and 1.51.1

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#204]
My test pipeline using vscode-extension-tester has recently been experiencing some problems: vscode simply dies immediately after being launched after about a second. I have tried to debug this issue a bit, but I have been only able to find out that this issue occurs with vscode 1.51.0 and 1.51.1. The previous versions work just fine.

Also, vscode does not appear to really crash. At least there is no coredump or anything else that would indicate that. Instead chromedriver appears to simply just stop. I have tried to increase the logging level of chromedriver via the `logLevel` parameter to `setupAndRunTests`, but the log unfortunately includes no indication what would be the error besides:
```
[11:48:53 AM][DEBUG] DevTools WebSocket Command: Runtime.evaluate (id=19) 847CC0718C5C69DF3B2DC1825469B2B5 {
   "expression": "1"
}
[11:48:53 AM][DEBUG] DevTools WebSocket Event: DOM.inlineStyleInvalidated 847CC0718C5C69DF3B2DC1825469B2B5 {
   "nodeIds": [ 14 ]
}
[11:48:53 AM][DEBUG] DevTools WebSocket Response: Runtime.evaluate (id=19) 847CC0718C5C69DF3B2DC1825469B2B5 {
   "result": {
      "description": "1",
      "type": "number",
      "value": 1
   }
}
[11:48:53 AM][INFO] Done waiting for pending navigations. Status: ok
[11:48:53 AM][INFO] [e4afa17e37ee80eb43a0a4c1b6dcc33a] RESPONSE FindElements [ {
   "ELEMENT": "0.6390581574867937-1"
} ]
[11:48:56 AM][INFO] [e4afa17e37ee80eb43a0a4c1b6dcc33a] COMMAND FindElement {
   "using": "css selector",
   "value": "html"
}
[11:48:56 AM][DEBUG] DevTools HTTP Request: http://localhost:34341/json/list
[11:48:56 AM][DEBUG] DevTools HTTP Request failed
[11:48:56 AM][INFO] [e4afa17e37ee80eb43a0a4c1b6dcc33a] RESPONSE FindElement ERROR chrome not reachable
  (Session info: chrome=83.0.4103.122)
```
which just indicates that the chromedriver stops for some reason.

Any idea how to debug this further?

**Comment by jrichter1** [comment]
@dcermak can you share the environment this is happening on? I'd like to replicate the circumstances, see if there is a way out of this.

**Comment by dcermak** [comment]
Sorry for forgetting about this completely… This is in my testing environment for the [open-build-service-connector](https://github.com/SUSE/open-build-service-connector). In theory you should get the same thing as I, if you run `yarn run test:ui` in a clone of the repository (unfortunately I still have a bunch of local changes that I did not push yet).

**Comment by dcermak** [comment]
So, I've come back to this and ran my ui tests on a fresh checkout from the master branch and the same issue is still there: the ui tests fail with vscode newer than 1.51.0.

One thing that I'm wondering about: could this be related to me using webpack to bundle my extension? I don't think it should, but I just say #214 and the extension mentioned there uses gulp for minification as far as I know.

**Comment by dcermak** [comment]
This actually appears to be a crash in vscode that only occurs under chromedriver: https://github.com/microsoft/vscode/issues/114635

**Comment by dcermak** [comment]
I have resolved this issue, it was caused by me messing with LD_PRELOAD a bit too much.

**Comment by infiniteregrets** [comment]
> I have resolved this issue, it was caused by me messing with LD_PRELOAD a bit too much.

hey @dcermak, I am currently facing the problem described in #214 and we are using webpack and LD_PRELOAD to load into the process refer https://github.com/metalbear-co/mirrord/blob/main/vscode-ext/src/extension.ts . Could you please describe how did you end up fixing your issue? Thanks!
