### ISSUE TITLE
Support packaging an extension with --yarn?

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#22]
I am working on a vscode extension, that doesn't really work too well with npm and thus I'm using yarn instead. Unfortunately that means that running `vsce package` is broken and instead I must invoke it as `vsce package --yarn`. Would it be possible to add a flag/option to this function: https://github.com/redhat-developer/vscode-extension-tester/blob/5aa523892b0314d899024e6b56b186cd554d7df2/src/util/codeUtil.ts#L120
that it will invoke `vsce package` with `--yarn` if the user wishes to do so?

This should be relatively straight forward to pull of, so I can submit a pull request myself, if you'd accept it?

**Comment by jrichter1** [comment]
Sounds reasonable. Just make sure the API and the CLI stay consistent, i.e. the commands that use this this method should also allow this flag.

**Comment by jrichter1** [comment]
This would also be a great opportunity to add a new sample project. If you'd be willing to add a sample yarn-packaged extension after you're done with the enhancement, that would be absolutely terrific :)

**Comment by jrichter1** [comment]
Thank you for the contribution.
