### ISSUE TITLE
Cannot install `vscode-extension-tester` behind proxy

### ISSUE THREAD

**Issue by mati-o** [redhat-developer/vscode-extension-tester#226]
Hello,

I would like to try `vscode-extension-tester` this for my project as it looks just like what I need :). Unfortunately, I am running behind a corporate proxy network that is able to get modules and dependencies from `npm` but **not** from GitHub.

The module `monaco-page-objects` specifies a dependency to `deep-merge` as a GitHub URL:

https://github.com/redhat-developer/vscode-extension-tester/blob/12a7651e8fb09481d5a0cdbc825cc336d13f0cb9/page-objects/package.json#L43

Would it be possible to specify it as a regular `npm` dependency?

Also, knowing that this module tries to download stuff from the internet, would it be possible to use environment variables to specify a proxy?

Regards,
Mati

**Comment by jrichter1** [comment]
Hello there,

as far as the github based module goes, I could eventually push it npm as well. It's just quite low on my priority list right now.
AFAIK there should be no more obstacles to using this behind a proxy though. `HTTP_PROXY` and `HTTPS_PROXY` environment variables should be respected by the module.

**Comment by jrichter1** [comment]
From `4.0` on the github dependency is gone, go ahead and try it out.

**Comment by mati-o** [comment]
> From `4.0` on the github dependency is gone, go ahead and try it out.

Much appreciated! I was able to install it successfully. 

I had no time to use it yet but I'll find try to in the next couple of days.
