### ISSUE TITLE
Testing Information Message with {modal:true}

### ISSUE THREAD

**Issue by lakxraju** [redhat-developer/vscode-extension-tester#230]
I show an information message where `modal` is set to true. Is there a way to access this notification for testing? I already tried getting from the NotificationCenter but it didnt work. 

```
vscode.window.showInformationMessage(`Are you sure?`, { modal: true }, 'yes', 'no')
```

**Comment by jrichter1** [comment]
You can handle modal dialogs using [ModalDialog](https://github.com/redhat-developer/vscode-extension-tester/wiki/ModalDialog) object. But it will only work if the `window > dialog style` setting is set to `custom`, `"window.dialogStyle": "custom"` in JSON format.

**Comment by lakxraju** [comment]
Thanks for your reply. 
Which JSON file are you talking about? 
I can set this option to `custom` in my vscode using the UI but how can I do that in the testing instance?

**Comment by jrichter1** [comment]
Either you can navigate to the settings editor and change the setting as part of your tests, there are page objects to do just that.

Or you can launch your tests with a custom JSON file that overrides the default vscode settings.
Lets say you have a file called `settings.json` that looks like this:
```
{
  "window.dialogStyle": "custom"
}
```
I'm assuming you're using a CLI command to launch the tests. Adding `-o settings.json` will take the json file and set the options on launch.

**Comment by lakxraju** [comment]
That worked 💯 ! Thanks @jrichter1
