### ISSUE TITLE
Working with npm@7 or node@15 ?

### ISSUE THREAD

**Issue by goretkin** [redhat-developer/vscode-extension-tester#253]
This package has an indirect dependency on 

https://www.npmjs.com/package/opencv4nodejs-prebuilt

(via https://github.com/nut-tree/nut.js)

which has an issue on npm@7
https://github.com/nut-tree/opencv4nodejs/issues/9

or perhaps it's node@15
https://github.com/nut-tree/nut.js/issues/193

**Comment by jrichter1** [comment]
Just using the `vscode-extension-tester` package will not pull in this dependency, therefore there should be no problem with latest nodejs.

The problem would be in `vscode-extension-tester-native`, which you would need to add separately. It was meant to handle some native dialogs like `open file`, but nowadays vscode has ways to do all dialogs inside the browser so the native package kind of lost its purpose.

**Comment by goretkin** [comment]
Thanks for the clarification!

I was trying to use `vscode-extension-tester` from source (e.g. build it, use `npm link`) and I ran into this issue. Perhaps I was unnecessarily building `vscode-extension-tester-native` and therefore running into this issue.
