### ISSUE TITLE
Error or warn on unused CLI arguments

### ISSUE THREAD

**Issue by goretkin** [redhat-developer/vscode-extension-tester#254]
If a shell does globbing instead of passing the argument literally, then there will be extra arguments to extest. 

It seems that extest silently drops trailing CLI arguments.

e.g. https://github.com/nishants/vscode-e2e-tests/issues/4

**Comment by jrichter1** [comment]
> It seems that extest silently drops trailing CLI arguments.

Correct. It only scans as many arguments as it expects and it's by design. It seemed to me most CLI tools behave this way by default. 

I really don't want to error because of extra arguments. But it might have some value to extend the glob pattern to variadic.
