### ISSUE TITLE
macOS, ChannelView.getCurrentChannel

### ISSUE THREAD

**Issue by goretkin** [redhat-developer/vscode-extension-tester#255]
Some locators appear not to be working on VSCode v1.54. I think that is to be expected given it was released a mere four days ago...

But curiously, some things related to `ChannelView` are working on macOS and v1.54 that are broken on Linux/Windows.
I saw that some tests have always been disabled on `darwin`. I disabled them more specifically here: https://github.com/goretkin/vscode-extension-tester/pull/1/commits/9ca4d8faedf3a6fe4eb2072bfb44e518110dc86b

I don't know if there is a way to mark a test as broken on mocha, but I thought it worthwhile to test for the broken behavior on macOS.

I wanted to quickly check the behavior across platforms for this specific test. If you'd like to see the result of the GitHub Actions, feel free to take a look:
https://github.com/goretkin/vscode-extension-tester/pull/1

**Comment by jrichter1** [comment]
MacOS has a bunch of features that just don't work with webdriver, like context menus - they are all native. Tests that run into these problems are disabled, that's why some test suites might not look broken on mac.

Anyway, I'll fix the new locators ASAP.
