### ISSUE TITLE
VSCode Download Fails

### ISSUE THREAD

**Issue by lakxraju** [redhat-developer/vscode-extension-tester#257]
VS Code IDE download step fails during test and it gets aborted. Seems like the website is down. But the vscode download from VSCode website is successful. Is there a fallback URL which can be added?

PS: I tried changing the version of VSCode and not successful as well. 

```
Downloading VS Code from: https://vscode-update.azurewebsites.net/1.52.1/darwin/stable
internal/streams/legacy.js:61
      throw er; // Unhandled stream error in pipe.
      ^

Error: getaddrinfo ENOTFOUND vscode-update.azurewebsites.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'vscode-update.azurewebsites.net'
}
```

**Comment by lakxraju** [comment]
fyi, In [VSCode documentation](https://code.visualstudio.com/docs/supporting/faq), the suggested download URL is `https://update.code.visualstudio.com/1.50.1/linux-deb-armhf/stable`

**Comment by jrichter1** [comment]
thanks for the heads up, I'll get a fix up ASAP

**Comment by jrichter1** [comment]
4.0.2 is live with the updated URL
