### ISSUE TITLE
WebView not working with latest VSCode Insider

### ISSUE THREAD

**Issue by quoctruong** [redhat-developer/vscode-extension-tester#260]
I'm not sure if this is because VSCode is enabling iframe based webview but with the latest version of the VSCode Insider, after calling `webview.switchToFrame`, `webview.findWebElement` no longer works correctly.

**Comment by go-nelango** [comment]
This seems to be fixed in [#263](redhat-developer/vscode-extension-tester#263). Will this be in the next release? If so, when is the next release being planned for?

**Comment by jrichter1** [comment]
Released 4.0.3 today, have fun.
