### ISSUE TITLE
Can't get vscode via extest

### ISSUE THREAD

**Issue by detihoronyatkonya** [redhat-developer/vscode-extension-tester#264]
Im trying `extest get-vscode` and geting

> Downloading VS Code from: https://vscode-update.azurewebsites.net/latest/linux-x64/stable
> Downloaded VS Code into \<path to my project\>/test-resources/stable.tar.gz
> Unpacking VS Code into \<path to my project\>/test-resources
> Error: incorrect header check
>     at Zlib.zlibOnError [as onerror] (node:zlib:182:17)

**Comment by jrichter1** [comment]
The download URL that we used from the start got shut down. It's been updated, but you'll need to update extest to version 4.0.2. Sorry for the inconvenience.

**Comment by detihoronyatkonya** [comment]
Thank you very much. Тow everything worked :)
