### ISSUE TITLE
functionality to access specific content/symbol of vscode statusbar

### ISSUE THREAD

**Issue by immanishbainsla** [redhat-developer/vscode-extension-tester#271]
Hey there, I want to access statusbar's particular icon in left side which is being created by an extension and similiary for an icon next to 'split editor' and 'open changes' icon to click it. Is there any other way to access these particular icons?

**Comment by immanishbainsla** [comment]
Do we have any other workaround for time being?

**Comment by amitkrout** [comment]
@immanishbainsla Screenshot would be really helpful. Would you please highlight those and attach it

**Comment by immanishbainsla** [comment]
sure @amitkrout 
here it is
![VSCode Screenshot](https://user-images.githubusercontent.com/36675831/115962985-70429f80-a53b-11eb-9841-0441efa57418.jpeg)

**Comment by jrichter1** [comment]
Added `getItem` to search items by title in status bar. Analogically, `getAction` is now available for editor view. Released in 4.0.3.
