### ISSUE TITLE
webview findElements and findElement cannot work

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#276]
![image](https://user-images.githubusercontent.com/995909/116402866-7b5d3e80-a85f-11eb-9141-a43dec4837e0.png)

**Comment by zhfnjust** [comment]
use css selector does work same

![image](https://user-images.githubusercontent.com/995909/116404095-e3605480-a860-11eb-954e-f078b318d497.png)

**Comment by jrichter1** [comment]
The webview content is wrapped inside an iframe, so you first need to switch webdriver to search inside the iframe, do all the business inside, and then switch back.

```typescript
// first, switch inside the web view
await webview.switchToFrame();

// look for desired elements
const element = await webview.findWebElement(<locator>);
const elements = await webview.findWebElements(<locator>);

...
// after all web view manipulation is done, switch back to the default window
await webview.switchBack();
```

**Comment by zhfnjust** [comment]
> The webview content is wrapped inside an iframe, so you first need to switch webdriver to search inside the iframe, do all the business inside, and then switch back.
> 
> ```ts
> // first, switch inside the web view
> await webview.switchToFrame();
> 
> // look for desired elements
> const element = await webview.findWebElement(<locator>);
> const elements = await webview.findWebElements(<locator>);
> 
> ...
> // after all web view manipulation is done, switch back to the default window
> await webview.switchBack();
> ```

thank you , i try to do , but it still not working 

![image](https://user-images.githubusercontent.com/995909/116414840-6a1a2f00-a86b-11eb-97f1-9b825744e013.png)

**Comment by zhfnjust** [comment]
i do have a button on webview

![image](https://user-images.githubusercontent.com/995909/116415031-9c2b9100-a86b-11eb-8ef4-8243c4e9e161.png)

**Comment by zhfnjust** [comment]
@jrichter1

**Comment by jrichter1** [comment]
I think the method you are looking for in this case is called `webview.findWebElement`, try if that one works for you.

**Comment by zhfnjust** [comment]
got it ,thank you
