### ISSUE TITLE
set value for settingseditor as ComboSetting isn't selecting the value.

### ISSUE THREAD

**Issue by noorshiblee** [redhat-developer/vscode-extension-tester#278]
My source code:
`
    let setting: ComboSetting;
    let editor: SettingsEditor;

    before(async function() {
        this.timeout(15000);
        editor = await new Workbench().openSettings();
        setting = await editor.findSetting('Title Bar Style', 'Window') as ComboSetting;
    });
    it('getValue works', async () => {
       
        const val='custom';
        setting.setValue(val);
        const value = await setting.getValue();
        expect(value).equals('custom');
    });`

I am trying to select value "custom" which is a drop  down value. Below method is not working. What is your suggestion here??
![image](https://user-images.githubusercontent.com/16698852/116586541-e10e0100-a919-11eb-9511-d2a167190ddb.png)

**Comment by jrichter1** [comment]
Looks like you forgot to await `setValue`.

**Comment by noorshiblee** [comment]
Thanks for your reply. Actually started using this one recently. You suggested to use like this-`await setting.setValue(val);` .This still produces same result. Do you have any other suggestion?
