### ISSUE TITLE
Incorrect text insertion into InputBox and DialogHandler

### ISSUE THREAD

**Issue by detihoronyatkonya** [redhat-developer/vscode-extension-tester#279]
Hello. I am trying to open the folder as recommended [here](https://github.com/redhat-developer/vscode-extension-tester/wiki#opening-files-and-folders). But the incorrect path is substituted into the inputbox. As a result I get "/ bin + my line without delimiters"
![image](https://user-images.githubusercontent.com/81704456/116709154-0e6db400-a9d9-11eb-834f-d8c89e71b750.png)
![image](https://user-images.githubusercontent.com/81704456/116709178-1594c200-a9d9-11eb-8e24-c6f853dfba70.png)

I also tried to open the folder using the DialogHandler from vscode-extension-tester-native. In this case, the correct line is inserted, but when inserting, a  subdirectory is added to the path
![image](https://user-images.githubusercontent.com/81704456/116712771-dec0ab00-a9dc-11eb-9539-d61052581f76.png)
![image](https://user-images.githubusercontent.com/81704456/116712461-8b4e5d00-a9dc-11eb-9736-6f78f8110fa9.png)

**Comment by jrichter1** [comment]
Could you share the version of tester/vscode this is occuring with? I remember fixing the inputbox issue about 3 times already :)
As for the native dialog, I'm hoping it is going to die slowly, fixing it for multiple OSes is a nightmare.

**Comment by detihoronyatkonya** [comment]
@jrichter1 `"version": "4.0.2"`
