### ISSUE TITLE
feature request : select a particular text as webelement from file in editor

### ISSUE THREAD

**Issue by immanishbainsla** [redhat-developer/vscode-extension-tester#280]
Hey there, I want to perform some hover operation over a particular text which is in file opened in editor. It would be really great if extension-tester could have this functionality.
Thanks

here's the SS for reference : I want to select text "4.1.1" as webElement
![VSCode](https://user-images.githubusercontent.com/36675831/116881874-6c9cd000-ac41-11eb-98d7-b9b2bcc4ccc9.png)

**Comment by jrichter1** [comment]
in 4.1.0, TextEditor now has `selectText` and `getSelection` that returns the selection block as a page object
