### ISSUE TITLE
Any api to access debugger button?

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#282]
![image](https://user-images.githubusercontent.com/995909/117247476-e2d34980-ae70-11eb-8f7d-cb5066401c5f.png)

**Comment by zhfnjust** [comment]
and DebugConsoleView don't have any api to Simulate user input
![image](https://user-images.githubusercontent.com/995909/117270428-c8f33000-ae8b-11eb-9011-3bde21bf20e3.png)

**Comment by zhfnjust** [comment]
i am writing a debugger e2e test

**Comment by jrichter1** [comment]
It appears you are the first person to actually use these (sort of the reason they haven't been implemented yet).
The debugger controls look straightforward enough. 
About the console, would something like `evaluateExpression(expression: string)` that just sets the text and confirms be enough?

**Comment by zhfnjust** [comment]
it will be nice if we have `evaluateExpression(expression: string) `

it will be more nice if we have some api like `settext(text: string)` and `getcompletionsItems` to test the completionsRequest of the Debugger Adapter Protocal

**Comment by zhfnjust** [comment]
we also need api too set/clear Breakpoint

Now i use   await new Workbench().executeCommand('Debug: Inline Breakpoint');

@jrichter1

**Comment by jrichter1** [comment]
And the debug view just for good measure :)

**Comment by jrichter1** [comment]
4.1.0 now has some support for debugging:
 - text editor can toggle breakpoint on lines
 - DebugConsolveView can now evaluate expressions
 - DebugToolbar was added to use the debugger buttons
