### ISSUE TITLE
ERROR  npm failed with exit code 2 Error: Command failed: node_modules/.bin/vsce package --no-yarn

### ISSUE THREAD

**Issue by immanishbainsla** [redhat-developer/vscode-extension-tester#284]
Hi there,
I have been facing this issue, as 'module' flag is already set to 'commonjs', don't knwo what else could go wrong.
have tried googling but didn't find anything related. so posting here.

ERROR in /home/.../fabric8-analytics-vscode-extension/test-resources/VSCode-linux-x64/resources/app/extensions/markdown-language-features/notebook/index.ts
[tsl] ERROR in /home/.../fabric8-analytics-vscode-extension/test-resources/VSCode-linux-x64/resources/app/extensions/markdown-language-features/notebook/index.ts(19,22)
      TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'esnext', 'commonjs', 'amd', 'system', or 'umd'.
 ERROR  npm failed with exit code 2
Error: Command failed: node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at CodeUtil.packageExtension (/home/.../node_modules/vscode-extension-tester/out/util/codeUtil.js:180:23)
    at ExTester.<anonymous> (/home/.../node_modules/vscode-extension-tester/out/extester.js:77:27)
    at Generator.next (<anonymous>)
    at /home/.../node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/.../node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (/home/.../node_modules/vscode-extension-tester/out/extester.js:58:16)
    at ExTester.<anonymous> (/home/.../node_modules/vscode-extension-tester/out/extester.js:112:24)

Thanks.

**Comment by immanishbainsla** [comment]
have tried deleting node_modules and package-lock.json and then npm install also.

**Comment by jrichter1** [comment]
have you excluded `test-resources` from your tsconfig?

**Comment by immanishbainsla** [comment]
yes, it worked. Thanks a lot @jrichter1 , you have been great help. Amazing.

**Comment by immanishbainsla** [comment]
just 1 question, what could have gone wrong or what did I change that this error came?
I didn't need to add it before, I even tried with new fork, faced same error.

**Comment by jrichter1** [comment]
No idea, excluding test-resources from compilation is required if you want to keep building your extension successfully. Otherwise it's going to try and recompile the whole vscode instance inside and you get this error. 

So the real question here is, how did you not bump into this error up till now? :)

**Comment by immanishbainsla** [comment]
yes, exactly. It was working fine till yesterday morning. 
Thanks again.

**Comment by immanishbainsla** [comment]
this error has to do with the latest release. It came exactly after the release of Version 0.3.3 of fabric8-analytics-vscode-extension.
