### ISSUE TITLE
Is it possible to import vscode in tests?

### ISSUE THREAD

**Issue by CsCherrYY** [redhat-developer/vscode-extension-tester#288]
Hello,

I'm new to this package and just tried with the helloworld sample, it works well. I'd like to know can we use VSCode API in the tests by `import * as vscode from "vscode"`? I just tried to use this in the helloworld sample, and it fails with the following error: 
```
Error: Cannot find module 'vscode'
```

**Comment by jrichter1** [comment]
Technically, it should be possible to import the package, but the API is not going to work anyway. The tests will see the vscode instance as a chrome browser, only communicating through webdriver.

So, that would be a no, sorry.

**Comment by CsCherrYY** [comment]
Get it. Thanks!
