### ISSUE TITLE
Add new functionality to TextEditor

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-extension-tester#294]
I would like to ask for some enhancements to TextEditor. We could probably use something from https://github.com/eclipse/reddeer/blob/master/plugins/org.eclipse.reddeer.workbench/src/org/eclipse/reddeer/workbench/impl/editor/TextEditor.java

**Comment by jrichter1** [comment]
Added new functionality to TextEditor in 4.1.0
