### ISSUE TITLE
Any way to avoid Workspace Trust in latest vscode version? 

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#295]
![image](https://user-images.githubusercontent.com/995909/121802655-03f93800-cc70-11eb-9fba-ff64c0e30d1f.png)

**Comment by zhfnjust** [comment]
> I'm working on a new release that is going to run with trust turned off by default, coming later this week.
> 
> In the meantime, this is the setting you can pass in to disable workspace trust:
> 
> ```
> "security.workspace.trust.enabled": false
> ```

it' s great

**Comment by jrichter1** [comment]
4.1.0 is out and workspace trust is disabled by default.

**Comment by ewanharris** [comment]
@jrichter1, do you know if it's possible to run with workspace trust enabled? My extension requires workspace trust, and I'm trying to enable it by clicking the `Yes` button but VS Code doesn't seem to start the extension fully

**Comment by jrichter1** [comment]
@ewanharris I haven't actually tried that yet.

My assumption was if you're running with `"security.workspace.trust.enabled": true`, you would just accept whatever dialog code throws at you, and that would be about all there is to it.

Is there any particular step that's giving you trouble?

**Comment by ewanharris** [comment]
Gah sorry for timewasting, I shoulda looked closer, my extension was just error-ing out 🤦🏻  If it's any use I'm using the below to accept the dialog after adding a folder to the workspace. It's a slightly different prompt to the normal "trust workspace" prompt

```js
const trustButton = await this.driver.findElement(By.xpath('.//a[starts-with(@title, "Yes")]'));
trustButton.click()
```
