### ISSUE TITLE
"Run and Debug" an APP on windows cause an error: "Key in dictionary:'Path' Key being added:'PATH'"

### ISSUE THREAD

**Issue by LareinaJi** [redhat-developer/vscode-extension-tester#298]
I am trying to run an app from command palette automatically,:
```
await workbench.executeCommand('Debug: select and start debugging');        
const input = new InputBox();                         ​
​await input.selectQuickPick(0) ;
```

this works well on linux
but on windows10, a popup window will displays as followed:
<img width="418" alt="key_in_dictionary_error" src="https://user-images.githubusercontent.com/85340969/122677249-252fca80-d214-11eb-80af-31e75580b688.png">

**Comment by jrichter1** [comment]
This looks like it's coming from the debugger itself, most likely due to an issue in the environment setup or the launch configuration. That's beyond this humble framework's control.

**Comment by LareinaJi** [comment]
Thank you, @jrichter1, I finally find the reason, because we run APP, we tried to add a directory to PATH, by "set **PATH**=dirA;%PATH%", for some reason: here the **PATH** is transformed to Path.
