### ISSUE TITLE
[🚀 Request] Hide `INFO:CONSOLE` messages

### ISSUE THREAD

**Issue by microhobby** [redhat-developer/vscode-extension-tester#318]
is there a way to suppress these logs?

```
[17904:0707/120829.747:INFO:CONSOLE(61)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: electron/js2c/renderer_init.js (61)
[17904:0707/120832.379:INFO:CONSOLE(61)] "The vm module of Node.js is deprecated in the renderer process and will be removed.", source: electron/js2c/renderer_init.js (61)
```

I'm running from powershell core on Windows and these are annoying, if there was a way to suppress these logs and just have the test logs it would be very good.

Thanks in advance.

**Comment by microhobby** [comment]
I tried the `-l Off` argument and also `ELECTRON_NO_ATTACH_CONSOLE` but with no success.

**Comment by amakarev** [comment]
Faced the same problem. Can't change logging level

**Comment by andreriesco** [comment]
This  `INFO:CONSOLE` messages are still appearing to me on Windows.
Is there any configuration I need to add to hide this `INFO:CONSOLE` messages?

**Comment by djelinek** [comment]
> This `INFO:CONSOLE` messages are still appearing to me on Windows. Is there any configuration I need to add to hide this `INFO:CONSOLE` messages?

Can you provide please more information about environment and steps to reproduce if possible? It seems that it is not happening during our CI builds nor locally..

Thank you in advance!
