### ISSUE TITLE
wait untill element is loaded in the UI  --- NoSuchSessionError: invalid session id

### ISSUE THREAD

**Issue by noorshiblee** [redhat-developer/vscode-extension-tester#319]
**Scenario:**

- Load UI in vscode using new Workbench().executeCommand
- Wait until UI is loaded and visible.

**Trying workout:**
I am trying to write test case using below source code:

    `
        describe('Load Home Page', () => {
            let view: WebView;
            let driver: WebDriver;
            before(async function () {

                    driver = VSBrowser.instance.driver;
                    await new Workbench().executeCommand('Open Home Page'); **// this takes a lots of time to load UI in CI server**
                 
                    //**multiple way i have tried like below**
                   
                    //****line 20****
                    driver.wait(until.elementLocated(By.xpath("//*[@id='webview-af737bee-61f2-485d-a5f0-9c3e88fd5fbf']")),5000);
                   
                   //await driver.wait(until.elementIsVisible(driver.findElement(By.xpath("//iframe[contains(@id,'active-frame')]"))));

                    //driver.wait(until.elementIsVisible(driver.findElement(By.xpath("//*[@id='webview-af737bee-61f2-485d-a5f0-9c3e88fd5fbf']"))));

                    //await driver.wait(until.ableToSwitchToFrame(new WebView().findWebElement(By.xpath("//iframe[contains(@id,'active-frame')]"))));

                    //await driver.wait(until.ableToSwitchToFrame(By.xpath("//iframe[contains(@id,'active-frame')]")));

                    //await driver.wait(until.ableToSwitchToFrame(By.xpath("//iframe[contains(@class,'webview ready')]")));

                    //view = new WebView();
                    await view.switchToFrame();
            });`

None of the above method is working. I am not sure i am doing things correctly.

Each time it shows either mocha timeout error message or invalid session or etc. etc.

For ex: one error message while using the code like line 20 :

    `/home//-vscode/-vscode/packages/-vscode-ide/node_modules/mocha/lib/runner.js:962
    -vscode-ide:     throw err;
       -vscode-ide:     ^
       -vscode-ide: NoSuchSessionError: invalid session id
       -vscode-ide:     at Object.throwDecodedError (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/error.js:514:15)
       -vscode-ide:     at parseHttpResponse (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/http.js:519:13)
       -vscode-ide:     at /home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/http.js:441:30
       -vscode-ide:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
       -vscode-ide: From: Task: WebDriver.findElements(By(xpath, //*[@id='webview-af737bee-61f2-485d-a5f0-9c3e88fd5fbf']))
       -vscode-ide:     at Driver.schedule (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
       -vscode-ide:     at Driver.findElements (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/webdriver.js:1048:19)
      -vscode-ide:     at /home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/until.js:243:23
       -vscode-ide:     at /home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/webdriver.js:938:14
       -vscode-ide:     at TaskQueue.execute_ (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    -vscode-ide:     at TaskQueue.executeNext_ (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:3067:27)
      -vscode-ide:     at /home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:2974:25
       -vscode-ide:     at /home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:668:7
       -vscode-ide: From: Task: <anonymous>
       -vscode-ide:     at Timeout.pollCondition [as _onTimeout] (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:2195:19)
       -vscode-ide:     at listOnTimeout (internal/timers.js:557:17)
       -vscode-ide:     at processTimers (internal/timers.js:500:7)
        -vscode-ide: From: Task: Waiting for element to be located By(xpath, //*[@id='webview-af737bee-61f2-485d-a5f0-9c3e88fd5fbf'])
       -vscode-ide:     at scheduleWait (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:2188:20)
       -vscode-ide:     at ControlFlow.wait (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:2517:12)
      -vscode-ide:     at Driver.wait (/home//-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      -vscode-ide:     at Context.<anonymous> (/home//-vscode/-vscode/packages/-vscode-ide/out/test/ui/component/Home.test.js:42:20)
    -vscode-ide:     at Generator.next (<anonymous>)
    -vscode-ide:     at fulfilled (/home//-vscode/-vscode/packages/-vscode-ide/out/test/ui/component/Home.test.js:5:58) {
    -vscode-ide:   remoteStacktrace: '#0 0x5595117ef2b9 <unknown>\n'
    -vscode-ide: }`

What is suggested way of doing this scenario?

Thanks in advance

**Comment by jrichter1** [comment]
I'm not exactly sure what you are trying to do. I'm guessing you're opening up a web view. If it's the sort of web view that opens up in an editor, all you have to do wait for it to open and use a `WebView` object to access it, just like the last lines of the provided code. I don't know whether you need to wait for something to appear inside the web view, or outside, before accessing it.

As for the `NoSuchSessionError`, my guess is you are hitting a timeout. Mocha has hard timeout of 2 seconds for both test cases and hooks. Unless you increase it, anything longer is going to error out. In this case an error in the before hook is going to skip the entire test file. And if it's the last test file in the suite, the browser shuts down immediately without waiting for webdriver to finish its tasks.

**Comment by noorshiblee** [comment]
Thanks @jrichter1  for your reply. 

As you said 
    `If it's the sort of web view that opens up in an editor, all you have to do wait for it to open and use a WebView object to access it, `

Is that mean that if a web view  opens up in an editor, i can't access it's element by webdriver. I must have to use  WebView object to access it?

Thanks in advance

**Comment by jrichter1** [comment]
Of course you can access all the elements by webdriver. The page objects are there to ease the work. Webviews for example are located in two nested iframes that you need to switch your way through. And those iframes are inside a div that has a long generated string as an id.

The choice is always yours.

**Comment by noorshiblee** [comment]
![image999](https://user-images.githubusercontent.com/16698852/125286750-70716080-e31c-11eb-92f5-481222e31421.png)

@jrichter1 Thanks again. Still not sure whether i am doing wrong or it's extension problem.
Attached image contains the web element details.
I used the source 


    `before(async function () {

	driver = VSBrowser.instance.driver;

	await new Workbench().executeCommand('SLX:Open Home');
	
	driver.wait(until.elementLocated(By.xpath("//iframe[contains(@class,'webview ready')]")),5000);
      });`


It still fails with :+1: 

    `    /home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/mocha/lib/runner.js:962
        throw err;
        ^

         NoSuchSessionError: invalid session id
        at Object.throwDecodedError (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium- 
        webdriver/lib/error.js:514:15)
        at parseHttpResponse (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium- 
        webdriver/lib/http.js:519:13)
         at /home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/http.js:441:30
         at processTicksAndRejections (internal/process/task_queues.js:95:5)
         From: Task: WebDriver.findElements(By(xpath, //iframe[contains(@class,'webview ready')]))
        at Driver.schedule (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium- 
        webdriver/lib/webdriver.js:807:17)
        at Driver.findElements (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium- 
       webdriver/lib/webdriver.js:1048:19)
       at /home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/until.js:243:23
        at /home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/webdriver.js:938:14
        at TaskQueue.execute_ (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium- 
       webdriver/lib/promise.js:3084:14)
       at TaskQueue.executeNext_ (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium - 
      webdriver/lib/promise.js:3067:27)
      at /home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:2974:25
      at /home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/promise.js:668:7
      From: Task: <anonymous>
     at Timeout.pollCondition [as _onTimeout] (/home//-vscode/vscodetwo/-vscode/packages/-vscode- 
     ide/node_modules/selenium-webdriver/lib/promise.js:2195:19)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
       From: Task: Waiting for element to be located By(xpath, //iframe[contains(@class,'webview ready')])
       at scheduleWait (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium- 
       webdriver/lib/promise.js:2188:20)
       at ControlFlow.wait (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium- 
       webdriver/lib/promise.js:2517:12)
       at Driver.wait (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/node_modules/selenium- 
      webdriver/lib/webdriver.js:934:29)
      at Context.<anonymous> (/home//-vscode/vscodetwo/-vscode/packages/-vscode- ide/out/test/ui/component/Home.test.js:24:20)
      at Generator.next (<anonymous>)
      at fulfilled (/home//-vscode/vscodetwo/-vscode/packages/-vscode-ide/out/test/ui/component/Home.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    remoteStacktrace: '#0 0x563c2aa752b9 <unknown>\n'
      }`

**Comment by noorshiblee** [comment]
i can use 

`   view = new WebView();
     await view.switchToFrame();`

But i don't know the equal thing of `driver.wait(until.elementLocated` in Webview.

**Comment by jrichter1** [comment]
```typescript
before(async function () {
    driver = VSBrowser.instance.driver;
    await new Workbench().executeCommand(' Home');
    driver.wait(until.elementLocated(By.xpath("//iframe[contains(@class,'webview ready')]")),5000);
});
```
I'm guessing this is the last (if not the only) test file in the suite. Afterwards the browser just shuts down. The last line is not awaited, so the task just gets scheduled and the browser doesn't wait for it to finish (enter `NoSuchSessionError`).

```typescript
 view = new WebView(); await view.switchToFrame();
```
If you want to know all the details, you can check the [source](https://github.com/redhat-developer/vscode-extension-tester/blob/76490e890e02a782a403fdcdeb6810dc8ded0c72/page-objects/src/components/editor/WebView.ts#L41). But the general gist is:
 - look inside the editor to find the ID of the webview
 - wait for the webview container with the given ID to appear
 - find the `'webview ready'` iframe and switch to it
 - find the `active-frame` iframe and switch to it
