### ISSUE TITLE
Uncaught NoSuchElementError: no such element: Unable to locate element:

### ISSUE THREAD

**Issue by noorshiblee** [redhat-developer/vscode-extension-tester#320]
**Scenario:**

- After loading the UI using driver, Switching to Frame for next steps.

**Used source code**:

    `describe('Load Home Page', () => {
         let view: WebView;
         let driver: WebDriver;

        before(async function () {

	     driver = VSBrowser.instance.driver;

	     await driver.findElement(By.xpath("//a[contains(@aria-label,'UI-Page')]")).click();
 
            driver.wait(until.elementLocated(By.xpath("//a/span/span[contains(text(),'Home')]")),5000);

	     await driver.findElement(By.xpath("//a/span/span[contains(text(),'Home')]")).click();

	     await new Promise(res => {
		    setTimeout(res, 500);
	     });

	     driver.switchTo().frame(driver.findElement(By.xpath("//*[@id='active-frame']")));

    });`

**Above source gives  bellow error:**

    `Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='active-frame']"}
    vscode-ide:   (Session info: chrome=89.0.4389.128)
    vscode-ide:   (Driver info: chromedriver=89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}),platform=Linux 5.8.0-59-generic x86_64)
    -vscode-ide:       at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
    -vscode-ide:       at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
    -vscode-ide:       at        /home/n/-vscode/-vscode/packages/-vscode-ide/node_modules/selenium-webdriver/lib/http.js:441:30
    -vscode-ide:       at processTicksAndRejections (internal/process/task_queues.js:95:5)
    -vscode-ide:   From: Task: WebDriver.findElement(By(xpath, //*[@id='active-frame']))
    -vscode-ide:       at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    -vscode-ide:       at Driver.findElement (node_modules/selenium-webdriver/lib/webdriver.js:1014:17)
    -vscode-ide:       at Context.<anonymous> (out/test/ui/component/Home.test.js:38:44)
    -vscode-ide:       at Generator.next (<anonymous>)
    -vscode-ide:       at fulfilled (out/test/ui/component/Home.test.js:5:58)
    -vscode-ide:   From: Task: WebDriver.switchTo().frame([object Object])
    -vscode-ide:       at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    -vscode-ide:       at TargetLocator.frame    (node_modules/selenium-webdriver/lib/webdriver.js:1824:25)
    -vscode-ide:       at Context.<anonymous> (out/test/ui/component/Home.test.js:38:31)
    -vscode-ide:       at Generator.next (<anonymous>)
    -vscode-ide:       at fulfilled (out/test/ui/component/Home.test.js:5:58)
`

Looking for solution.

Thanks

**Comment by Foxhoundn** [comment]
I think this might be related to our issue #316

**Comment by jrichter1** [comment]
![Screenshot from 2021-07-12 13-02-52](https://user-images.githubusercontent.com/4181232/125277274-84fc2b80-e311-11eb-815b-7c46e2ec2f30.png)
This is the frame you are looking for. As you can see, it is wrapped inside another iframe. The only way to switch into the nested frame is to first switch into the outside frame. Then you can find the actual iframe you're looking for.

Or maybe use the page objects for `WebView`.

**Comment by odockal** [comment]
Is this issue still actual? Is it something we should take a look or did you manage to find a solution? Thanks.
