### ISSUE TITLE
Inconsistent test results for tests in test/test-project

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#33]
Hi, after following the contributing guide for this project, I realized that not all tests in `test/test-project` pass. I also realized that depending on the OS and the VS Code version, the test results are different (ie, some cases that failed before, pass. some cases that pass before, fail)

For example, on Windows, when using the latest version of VS Code (1.40,0) and ChromeDriver (76.0.3809.126), I only have one (sometimes two) test(s) failing.

When using VS Code version (1.37.0) and ChromeDriver (2.38), more tests are failing.

Test results are also different on my linux machine as well. As of now, I am not sure why this happens.

I don't mean to sound condescending, I am just really excited about this project.

**Comment by jrichter1** [comment]
I'm really interested in your findings here. Mostly because for some reason I rarely get test failures on my machines (maybe besides toggleContentAssist test which I've been trying to fix for like 5 releases and it always comes back). So I'm really interested what others might experience :)

If you could give me the list of failures you've experienced, that would be absolutely terrific. Even more so if you could include what OS + Code version combo they happened with. Also if you notice any quirks like hanging native dialogs, or pages opening in an external browser, don't hesitate to tell me.

Cheers!

**Comment by xorye** [comment]
Awesome, here are some output files from my machine, which is running Fedora 30

This is how I ran the tests:
1. Cloned the repo
2. `npm install && npm run build && npm run prepare-test`
3. `npm test > outputfile 2>&1`
4. Go to `test/test-project/package.json` and add the `-c` flag in  the `scripts.ui-test` script
5. repeat 3. and 4.

Here are the output files:
No -c flag: https://gist.github.com/xorye/0b6e48ba9a3ee300b11c97dbdb040142
-c 1.39.0: https://gist.github.com/xorye/953bb7df3253dc725a83873805ee30d4
-c 1.38.0: https://gist.github.com/xorye/71222160fb484ff2c7624118d11dccde
-c 1.37.0: https://gist.github.com/xorye/daf5595c324ae25bfcbff9cc55dc848a

For the tests for 1.38.0 and 1.37.0, this page: https://code.visualstudio.com/docs?start=true opens in my browser at the beginning.

For the tests for 1.39.0 and 1.40.0, this dialog sometimes shows up:
![image](https://user-images.githubusercontent.com/20326645/69659639-9f09cd00-104c-11ea-9c84-279bc6969279.png)
The dialog did not show up for the outputs I gathered above.

Please let me know if there is something you need. I'll collect output data from Windows 10 in the near future

**Comment by jrichter1** [comment]
Thanks for the logs! It looks like you are running a bunch of extensions that contribute some parts that were not accounted for. I don't know if it's the tests' fault, or the frameworks itself yet. Can you give me a list of extensions you have enabled so I can reproduce your environment?

Anyway, I've started fixing what I believe to be extension-agnostic in #34 - feel free to try it out :)

**Comment by xorye** [comment]
> It looks like you are running a bunch of extensions that contribute some parts that were not accounted for.

It looks like this was why my tests were failing. They seem good now!

I realized that disabling all installed extensions in VS Code isn't enough. When the test VS Code instance starts up, the extensions still enable

**Comment by xorye** [comment]
If you're still interested, here is a list of extensions I have currently installed:|

```
$ code --list-extensions
adashen.vscode-tomcat
alphabotsec.vscode-eclipse-keybindings
benbusby.earthbound-themes
dunstontc.dark-plus-syntax
eamodio.gitlens
EditorConfig.EditorConfig
Equinusocio.vsc-material-theme
extest-samples.helloworld-sample
gerane.Theme-Pastel
grimmer.vscode-back-forward-button
k--kato.intellij-idea-keybindings
mathiasfrohlich.Kotlin
ms-python.python
ms-vscode.vscode-typescript-tslint-plugin
oscarmcm.ocean-space
Pivotal.vscode-boot-dev-pack
Pivotal.vscode-concourse
Pivotal.vscode-manifest-yaml
quangogage.pastel-pixels
quangogage.quango-calm
ramyaraoa.show-offset
rchesnokov.serenity-theme
redhat.java
redhat.vscode-quarkus
redhat.vscode-yaml
shengchen.vscode-checkstyle
streetsidesoftware.code-spell-checker
testing.helloworld-sample
viktorqvarfordt.vscode-pitch-black-theme
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscjava.vscode-spring-initializr
vscmaven.vscode-xml-maven
vscode-extension-tester.test-project
vscode-sampless.helloworld-sample
whizkydee.material-palenight-theme

```

**Comment by xorye** [comment]
I've tried https://github.com/redhat-developer/vscode-extension-tester/pull/34 and I don't get the 
Getting Started page opening on 1.37.0 and 1.38.0 anymore.

Also, do you know a way to disable certain extensions during the tests?

**Comment by jrichter1** [comment]
I haven't found a way to disable specific extensions for a test run. Code seems to only have commands to uninstall extensions or just disable them all at once.

It is possible to navigate to the extensions view and disable some extensions during the test run. Some extensions might need to restart the whole application though.
