### ISSUE TITLE
VSCode not loading when upgrading to version 1.60

### ISSUE THREAD

**Issue by quoctruong** [redhat-developer/vscode-extension-tester#344]
Hi,

Currently, I'm using extension tester with version `1.55` of VSCode and everything is wroking great. However, when I attempt to upgrade VSCode to any version above that (`1.60` for example) then my tests fail to run. The VSCode instance that is started by the test will just show a blank canvas (no title bar or anything) and after 45 seconds, the test will time out. I believe the extension tester is waiting for this [logic](https://github.com/redhat-developer/vscode-extension-tester/blob/master/src/suite/runner.ts#L67) during the timeout. Any idea or suggestion on how I can fix/debug this issue?

Please find attached the `test.log` file in case it helps.

[test.log](https://github.com/redhat-developer/vscode-extension-tester/files/7124149/test.log)

**Comment by jrichter1** [comment]
Going over the logfile, I honestly have no idea what went wrong. It looks like path points to the correct executable, the chromedriver version is correct as well, but then it get stuck with
```
[DEBUG] DevTools WebSocket Event: Runtime.consoleAPICalled 6374BBEE7FE6DBCBF0BC2D9DCD2120FE {
   "args": [ {
      "type": "string",
      "value": "[resolve window config] Could not resolve window configuration within 10 seconds, but will continue to wait..."
   } ]
```

First thing I'd try is purging the whole test-resources folder letting everything be downloaded again, maybe it will help.

**Comment by quoctruong** [comment]
Hi Jan, I have tried that as well but that didn't seem to work. What's interesting is that I tried a simple extension with the tester and that works but when I tried it with my extension, it didn't seem to load.

**Comment by jrichter1** [comment]
Might be a configuration issue then. Is your extension available so we can try and debug it?

**Comment by adityaaswani** [comment]
1 way to check.
1. Put a breakpoint in the before() method of mocha test
2. Let the experimental instance launch by the browser
3. Help -> Toggle developers tools -> Console

I followed these steps to identify the fs-extra module was missing and my extension failed to load via the browser when trying to run mocha bdd tests

**Comment by quoctruong** [comment]
@jrichter1 I did some further testing and I encounter this strange behavior. If I run `node ./node_modules/.bin/extest run-tests ....` then VSCode version 1.60 loads just fine. However, if I put `extest run-tests ....` into my `package.json` and run `npm run testcommand` then VSCode version 1.60 will not load (it got stuck at waiting for work bench).

**Comment by odockal** [comment]
Is this issue still actual? Is it something we should take a look or did you manage to find a solution? Thanks.

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.
