### ISSUE TITLE
Change StatusBar.getItem to search aria-label instead of title

### ISSUE THREAD

**Issue by ChaseMor** [redhat-developer/vscode-extension-tester#345]
For recent versions of VS Code, 1.58+, [`getItem`](https://github.com/redhat-developer/vscode-extension-tester/blob/bbf84d4fff83303d6207df58764dbd10e95f4f32/page-objects/src/components/statusBar/StatusBar.ts#L29) searches the status bar items [based on their aria-label](https://github.com/redhat-developer/vscode-extension-tester/blob/bbf84d4fff83303d6207df58764dbd10e95f4f32/locators/lib/1.58.0.ts#L6).

But for versions prior to that, [it searches based off of the `title` attribute.](https://github.com/redhat-developer/vscode-extension-tester/blob/bbf84d4fff83303d6207df58764dbd10e95f4f32/locators/lib/1.37.0.ts#L302) This is somewhat problematic because in versions prior to 1.58, the `title` attribute represented the tooltip of the status bar item and not the actual text. [While the `aria-label` attribute is set to the actual text of the item. ](https://github.com/microsoft/vscode/blob/507ce72a4466fbb27b715c3722558bb15afa9f48/src/vs/workbench/api/browser/mainThreadStatusBar.ts#L38)

With the current way of searching, in order to find the status bar item on older versions of VS Code, the status bar item **must** have a tooltip. While switching to use its aria-label would support a broader variety of extensions.

**Comment by jrichter1** [comment]
Makes sense, I think I haven't really thought about the items contributed by extensions back then.
