### ISSUE TITLE
StatusBar.getItem throws an error when an item disappears while searching

### ISSUE THREAD

**Issue by ChaseMor** [redhat-developer/vscode-extension-tester#346]
With the current implementation of [`StatusBar.getItem`](https://github.com/redhat-developer/vscode-extension-tester/blob/bbf84d4fff83303d6207df58764dbd10e95f4f32/page-objects/src/components/statusBar/StatusBar.ts#L26), it gets all the StatusBar items, and then checks each one if they match their attribute. However, if an element disappears before it is compared, Selenium will throw an `StaleElementReferenceError`.

Ideally, in the case that the element is stale, it should just be ignored instead of throwing an error.

A short repro for this is shown here at https://github.com/ChaseMor/vscode-status-bar-example.

**Comment by jrichter1** [comment]
Thanks for the issue, and the solution.
