### ISSUE TITLE
Can I access vscode api in the mcha tests?

### ISSUE THREAD

**Issue by adityaaswani** [redhat-developer/vscode-extension-tester#349]
I tried to import vscode in the sample test file: helloworld-test.ts
import * as vscode from 'vscode';

But when I run the test I get the error Cannot find module 'vscode'.
Without vscode I am able to launch and run the sample mocha test.

**Comment by jrichter1** [comment]
That would be a no. As far as the tests are concerned, the vscode instance is just a chromium browser.

**Comment by adityaaswani** [comment]
I thought so. Thanks for confirming
