### ISSUE TITLE
Extension not being uninstalled after tests complete

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#35]
Hi, I've noticed that when testing an extension, the extension is packaged and installed as a vsix. When the tests are finished, the extension remains installed. 

Is there a built-in option I could set to uninstall the extension after the tests are finished?

**Comment by jrichter1** [comment]
> Is there a built-in option I could set to uninstall the extension after the tests are finished?

I should add one...

**Comment by jrichter1** [comment]
the `-u` flag is now available in 2.2.0

**Comment by xorye** [comment]
Thank you!
