### ISSUE TITLE
Support CustomEditor

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#359]
VS Code API is providing support for CustomEditor https://code.visualstudio.com/api/extension-guides/custom-editors

it would be nice having the Page Object in the framework too.

I think the potential actions/API for it should be:
* isDirty(): Promise<boolean>;
* save(): Promise<void>;
* getWebView(): promise<Webview>

maybe interesting to do at the same time the CustomTextEditor (unless the classic TextEditor can do the trick?)

**Comment by jrichter1** [comment]
Should be working fine in 4.2.3
