### ISSUE TITLE
How can I hover over a tree node?

### ISSUE THREAD

**Issue by ebennett48375** [redhat-developer/vscode-extension-tester#375]
I'm having a problem trying to click on a ViewActionItem, and I would appreciate any suggestions.

Here is a code fragment to show the problem. connNode is asserted to be defined.

1.  const treeItem = connNode as TreeItem;
2.  const action = await treeItem.getActionButton('Search Data Sets');
3.  assert(action !== undefined);
4.  await action.click();

The assert at line 3 is true, but the click on line 4 throws an item not interactable error.

I threw in  assert(await action.isDisplayed()) before line 4, and found that the item is in fact not displayed. I am assuming this is the cause of the error. The item is only visible when hovering over the tree node.

I found the ActionSequence API, and thought maybe I could fix it with that. The new code fragment is as follows:

1.  const treeItem = connNode as TreeItem;
2.  const action = await treeItem.getActionButton('Search Data Sets');
3.  assert(action !== undefined);
4.  const seq = new ActionSequence(driver);
5.  await seq.mouseMove(action).perform();
6.  assert(await action.isDisplayed());

The assert at line 6 continues to show that the item is not visible, so the mouseMove did not do what I had hoped.

Any suggestions on how I can hover over the treeItem or action and make the action item visible?

**Comment by jrichter1** [comment]
Your approach looks correct. I think the issue is that `action` element is not displayed when you are trying to move the mouse over it, which makes webdriver very confused.

It should work if you target the tree item instead. Btw. there is a shorthand for action sequence:
```typescript
await driver.actions().mouseMove(treeItem).perform();
```

**Comment by ebennett48375** [comment]
Jan,
Your suggestion worked.  I'm somewhat embarrassed that I did not think to try it before bothering you with it. :)

Thanks again for your help.
