### ISSUE TITLE
Using Cucumber instead of Mocha

### ISSUE THREAD

**Issue by JSorella** [redhat-developer/vscode-extension-tester#380]
Hi everyone,
I am pretty sure this is not the best place to make this kind of question, but I don't know where else discussions of this extension are taking place.

I am currently using this extension to test a plugin developed at my work.
The plugin works great but I need to work using Gerkhins definitions. I know Mocha is BDD, but I need to work with something mostly related to Cucumber, in order to define Gerkhins scenarios in a `.feature` file so anyone can read & define the scenarios without reading any code in the middle.
I was looking deeper into the Extension Tester code and seems that Mocha is very coupled with the project core.

So... Is there any way I can work using Cucumber instead of Mocha? Or is this simply impossible?

**Comment by jrichter1** [comment]
So far there only is a mocha runner. In general the runner defines a global before/after hook to start/stop the browser and loads desired test files. If cucumber API allows that, then we can add a cucumber runner as well.

**Comment by JSorella** [comment]
> So far there only is a mocha runner. In general the runner defines a global before/after hook to start/stop the browser and loads desired test files. If cucumber API allows that, then we can add a cucumber runner as well.

Yes, of course, Cucumber has the BeforeAll and AfterAll global hooks, as explained here:
https://cucumber.io/docs/cucumber/api/

**Comment by JSorella** [comment]
@jrichter1 
How difficult could be to develop this? I think I am able to help if it's possible :)
