### ISSUE TITLE
Inconsistency when checking editor titles

### ISSUE THREAD

**Issue by ChaseMor** [redhat-developer/vscode-extension-tester#381]
If trying to iterate through and open all editors within an editor group (e.g. clearing all the text in open editors), one might use the code

```typescript
async function openEachEditor(group: EditorGroup) {
  const titles = await group.getOpenEditorTitles();
  for (const tabTitle of titles) {
    const editor: Editor = await group.openEditor(tabTitle);
    
    ...

  }
}
```

This however has the potential to fail because of inconsistencies between getting an editor's title and getting an editor from its title.

[When getting an editor's title, the title returned is:](https://github.com/redhat-developer/vscode-extension-tester/blob/df34cd9c953b98b4b3de1d213028fb0c41e00fe2/page-objects/src/components/editor/EditorView.ts#L242)
```typescript
const title = path.basename(await tab.getAttribute(EditorView.locators.EditorView.tabTitle));
```

[But when trying to open an editor, `openEditor` calls `getTabByTitle` which checks it like so:](https://github.com/redhat-developer/vscode-extension-tester/blob/df34cd9c953b98b4b3de1d213028fb0c41e00fe2/page-objects/src/components/editor/EditorView.ts#L253)
```typescript
const label = await element.getAttribute(EditorView.locators.EditorView.tabLabel);
if (label.startsWith(`${title}${EditorView.locators.EditorView.tabSeparator}`)) {
  tab = element;
  break;
}
```

While this does work in most cases, there is a case in which these do not match.

That is when the editor is working on an unsaved file and the first line of which contains a path. And example being [a kubernetes object](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#describing-a-kubernetes-object)
```yaml
apiVersion: apps/v1
kind: Deployment
spec: ...
```

In this case, both the aria-label and title are both the contents of the first line followed by `apiVersion: apps/v1 • Untitled-1`. But `path.basename` will truncate the first part of the contents and return `v1 • Untitled-1`.

**Comment by jrichter1** [comment]
Titles should now only be retrieved from one place, the editor tab.
