### ISSUE TITLE
`extest setup-and-run` - Error: Command failed: ELECTRON_RUN_AS_NODE=1 

### ISSUE THREAD

**Issue by AlexXuChen** [redhat-developer/vscode-extension-tester#387]
When running `extest setup-and-run`, I'm met with the following error:
```
Error: Command failed: ELECTRON_RUN_AS_NODE=1 "<root>/test-resources/VSCode-linux-x64/code" "<root>/test-resources/VSCode-linux-x64/resources/app/out/cli.js" -v

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```
where `<root>` is the project directory.

Normally at this stage, a selenium webdriver would open to run through the UI tests.

**Comment by brianignacio5** [comment]
I think this is probably fixed in #386 Have you tested `v4.2.3` ?

**Comment by AlexXuChen** [comment]
Yes it works now, I was using version ^4.1.2. Thanks!

**Comment by jrichter1** [comment]
`4.2.3` 's sole purpose was to fix this, nice to see it actually works
