### ISSUE TITLE
[Wish] Support pre and post run hooks?

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#39]
I have an extension that is unfortunately annoyingly hard to unit test (requires more mocking code than actual test code) and UI tests are imho the way to go. Unfortunately, I have absolutely no idea how to collect test coverage from UI tests, e.g. via [nyc](https://github.com/istanbuljs/nyc).

Is this even possible? If I understand this module correctly, then it launches a new instance of vscode and one would have to somehow hook into the launch to collect test coverage?

**Comment by jrichter1** [comment]
With the way tools like `nyc` work, it should be possible to get coverage from just about any test. Though I don't know how much tweaking is required in this case.

First step is to instrument the source files. This basically injects code that reports usage into every statement the coverage keeps track of. `nyc` should have some options for this, like what files to include and where to put the results.

Now if the tests are run with the instrumented files, you get the raw usage data whenever they trip over the instrumented code. All that is left after that is to hook up some reporter to make a coverage report from the raw files after the test run. Again, I believe `nyc` has some options to do just that.

The remaining question is, how hard it would be to integrate some tool like this, e.g. how much configuration would have to be done manually.

**Comment by dcermak** [comment]
I am unfortunately not an expert in this, but I have managed to collect test coverage from my extension's unit tests by running this function before the test execution:
``` ts
function setupCoverage() {
  const NYC = require("nyc");
  const nyc = new NYC({
    all: true,
    cwd: path.join(__dirname, "..", "..", ".."),
    exclude: ["**/test/**", ".vscode-test/**"],
    hookRequire: true,
    hookRunInContext: true,
    hookRunInThisContext: true,
    instrument: true,
    reporter: ["text", "html", "lcov", "json-summary"]
  });

  nyc.reset();
  nyc.wrap();

  return nyc;
}
```
and these two lines after all tests ran (`nyc` here is the return value of the function `setupCoverage()`):
``` ts
nyc.writeCoverageFile();
nyc.report();
```

So if one could specify arbitrary hooks that get executed before and after all the tests run, that would be perfect for me. This would also make it possible to setup file system or function mocks, which I have so far also not been able to achieve with vscode-extension-tester.

Would some form of generic pre-/post-hook functionality be possible to pull off?

**Comment by jrichter1** [comment]
Sounds easy enough to do in the API. The CLI on the other hand would be pretty awkward to pass code into, so it would need some convenient way to load the callbacks. Some interface file maybe?
I'll need to give it some thought.

You can also get this effect with a little hack of your own. The trick is to have a single suite (describe block) that calls other suites (as functions for example). That way the top level hooks would essentially be run before/after all your tests.

**Comment by dcermak** [comment]
> Sounds easy enough to do in the API. The CLI on the other hand would be pretty awkward to pass code into, so it would need some convenient way to load the callbacks. Some interface file maybe?

I guess that most users of such a hook feature wouldn't mind using the API directly, so I wouldn't stress too much about providing a CLI interface to that. If you want to provide one though, then I guess the user could provide a js file that exports two functions: `beforeSuite()` and `afterSuite()` and `extester` runs these functions before and after the suite.

> 
> You can also get this effect with a little hack of your own. The trick is to have a single suite (describe block) that calls other suites (as functions for example). That way the top level hooks would essentially be run before/after all your tests.

Hm, but that doesn't appear to work for hooks into the actual extension though. I've tried mocking a few library calls that are run by the extension, but these don't appear to be taken into account.

**Comment by jrichter1** [comment]
> > You can also get this effect with a little hack of your own. The trick is to have a single suite (describe block) that calls other suites (as functions for example). That way the top level hooks would essentially be run before/after all your tests.
> 
> Hm, but that doesn't appear to work for hooks into the actual extension though. I've tried mocking a few library calls that are run by the extension, but these don't appear to be taken into account.

Mocks won't do much good here, I'm afraid. The vscode instance your extension is running inside is  completely isolated from the tests. The communication only happens through chromedriver (webdriver protocol), extension code is not available in the tests.

**Comment by dcermak** [comment]
> > > You can also get this effect with a little hack of your own. The trick is to have a single suite (describe block) that calls other suites (as functions for example). That way the top level hooks would essentially be run before/after all your tests.
> > 
> > 
> > Hm, but that doesn't appear to work for hooks into the actual extension though. I've tried mocking a few library calls that are run by the extension, but these don't appear to be taken into account.
> 
> Mocks won't do much good here, I'm afraid. The vscode instance your extension is running inside is completely isolated from the tests. The communication only happens through chromedriver (webdriver protocol), extension code is not available in the tests.

Is there a possible way to add hooks into the vscode instance that actually runs the tests? I think that would also be necessary to collect test coverage data.

**Comment by jrichter1** [comment]
> Is there a possible way to add hooks into the vscode instance that actually runs the tests? I think that would also be necessary to collect test coverage data.

I don't know if it is even possible to add hooks into running browser like this. It's beyone what this framework can do anyway. If you need something done before or after the whole test run, the best bet would be to define your own scripts and simply chain them together.

You could have `scriptA` to instrument your source files and build the extension, then run the tests, then `scriptB` would collect the coverage.
`npm run scriptA && npm test && npm run scriptB`

**Comment by dcermak** [comment]
> I don't know if it is even possible to add hooks into running browser like this. It's beyond what this framework can do anyway. If you need something done before or after the whole test run, the best bet would be to define your own scripts and simply chain them together.

That's a pity, I'll see if I can get something together and in case I do, I'll report back. However I cannot promise I'll find something, so feel free to close this issue.
