### ISSUE TITLE
Add option to update outdated extensions

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-extension-tester#391]
When using `extest` dependent extensions will be installed and cached but they will never be updated.

I seen some warnings being logged about all my dependent extensions that that are outdated but I have no option to tell extest to update them.

Because vscode does not allow you to mention versions when mentioning dependent extensions we endup testing with outdated ones, not only locally but also on CI if you happened to enable caching of test-resources, something that can improve testing performance.

We need an option to tell to update extensions instead of using outdated cached ones.

**Comment by jrichter1** [comment]
Since vscode has no CLI option to update extensions, there is no way to conveniently do this.

If you really want to start with a clean slate, you can use `-e /path/to/some/folder` which will tell vscode to store and search for extensions in `/path/to/some/folder`. If you also delete `/path/to/some/folder` before every test run, you can be sure there are no outdated extensions used by your tests.

**Comment by ssbarnea** [comment]
Based on`code --help`, adding `--force` would make vscode upgrade extension when possible and avoid displaying any runtime warnings about outdated extension.

```
$ code --force --install-extension redhat.ansible
Installing extensions...
Extension 'redhat.ansible' is already installed.
```
Old:
```
$ code --install-extension redhat.ansible 
Installing extensions...
Extension 'redhat.ansible' v0.7.0 is already installed. Use '--force' option to update to latest version or provide '@<version>' to install a specific version, for example: 'redhat.ansible@1.2.3'.
```

This makes me believe that the only change we have to make is to add `--force` to the command. In fact I see no reason for not making this implicit as I see no use of running testing with outdated dependencies.

**Comment by jrichter1** [comment]
right, I thought the request was to update all extensions before running

**Comment by ssbarnea** [comment]
My impression is that my change does this. I don't really care about extensions that are not mentioned in the list of dependencies. If someone is installing these using a different method, it would be up to them to ensure they are updated.
