### ISSUE TITLE
OpenDialog doesn't work on mac

### ISSUE THREAD

**Issue by devipv02** [redhat-developer/vscode-extension-tester#40]
Hi,
Using vscode-extension-tester, I'm trying to do this 'workbench.executeCommand('Workspaces: Add Folder to Workspace...');' which opens a native dialog. I'm using 
const dialog = await DialogHandler.getOpenDialog();
dialog.selectPath($WORKSPACE_PATH) 
dialog.confirm();

This doesn't work and dialog stays open. Let me if this works in mac or any alternate approaches to open a folder/workspace in vscode. [I just need a way to add an empty folder to the vscode and from there i'm good testing my extension]

**Comment by jrichter1** [comment]
The dialog is indeed broken on mac, and I'm not quite able to get it working.

Therefore I am putting together a little extension to go along with the tester that would allow opening files/folders using a command. That should circumvent any need for open dialog and should be more stable in the end.

It shall be included into the next release.

**Comment by xorye** [comment]
Hi, I've come across a similar problem. In my case, the extension I would like to test provides this functionality:

* User calls a VS Code command through the command palette
* Input box appears, user types in input, hits enter
* the dialog appears, prompting the user to choose a folder

In this case, the dialog is opened by the vscode extension I am testing, so I think it would be amazing if Mac support was eventually added. 

Is it an issue with the 'node-key-sender' npm module and its compatibility with Mac?

**Comment by jrichter1** [comment]
> Is it an issue with the 'node-key-sender' npm module and its compatibility with Mac?

Very much so. Specifically [this issue](https://github.com/garimpeiro-it/node-key-sender/issues/25).

I understand the need for dialog handling, but so far I've failed to find a way to get it a;; working properly without writing it all myself.

**Comment by devipv02** [comment]
Hi, I'm able to get a workaround for this using robotjs on VSCode 1.40
	var robot = require('robotjs');
	var ncp = require('copy-paste');  

        ncp.copy($PATH);   // Path to open dialog
        robot.keyToggle("g", "down", ["command", "shift"]);
        robot.keyToggle("g", "up", ["command", "shift"]);
        robot.keyToggle("v", "down", ["command"]);
        robot.keyToggle("v", "up", ["command"]);
        robot.keyToggle("enter", "down");
        robot.keyToggle("enter", "up");
        robot.keyToggle("enter", "down");
        robot.keyToggle("enter", "up");

**Comment by jrichter1** [comment]
Robotjs definitely is a worthy alternative, but they have [issues with newer versions of nodejs](https://github.com/octalmage/robotjs/issues/520). As in I can't currently use robotjs with nodejs newer than version 8. Once they get a fix released, I'd be glad to try it out.

**Comment by devipv02** [comment]
My current version of nodejs is 10.16.1 and i don't see any issue with robotjs

**Comment by jrichter1** [comment]
Fixed as per #56, hopefully :)
