### ISSUE TITLE
[Request] How to access the variables view

### ISSUE THREAD

**Issue by asitsahoo351** [redhat-developer/vscode-extension-tester#402]
While debugging I want to test the variables view, I am able to expand the variables view by using the code :
 var runDebugSideBarView = new SideBarView().getContent();
 var variablesSection = (await runDebugSideBarView.getSection('Variables'));
 await variablesSection.expand();

But, after this I am not able to expand Locals/Globals/Registers and get their content to verify. How can I access this variables view and verify the variables or registers present in it? 
![variable_view](https://user-images.githubusercontent.com/41184165/144799342-85795a5b-c009-48dd-800e-d9c1dee774ef.JPG)

**Comment by mlorinc** [comment]
Created #828, which will allow to fetch variable name, variable value, and change variable value. Although, I need to fix tests first.
