### ISSUE TITLE
textEditor.selectText & textEditor.getSelection() throw NosuchElement error

### ISSUE THREAD

**Issue by luyu12** [redhat-developer/vscode-extension-tester#405]
My Code
` await textEditor.selectText('name');
        const selection = await textEditor.getSelection();

        if(!selection) {
            throw('no selected text');
        }

        const contextMenu = await selection.openContextMenu();
        console.log('menu: ' + selection.getText);
        const pMenuItem = await contextMenu.getItem('...')`

 `Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-menu-container"}
  (Session info: chrome=91.0.4472.164)
  (Driver info: chromedriver=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}),platform=Mac OS X 11.6.0 x86_64)`

**Comment by SURYASPR** [comment]
I'm trying to test simple helloworld-sample extension using vscode-extension-tester but running into this issue https://github.com/redhat-developer/vscode-extension-tester/issues/410

Can you please let me know if it's working for you ?

**Comment by djelinek** [comment]
`textEditor.getSelection` is not working on macOS

you can workaround with 
```
editor.selectText()
editor.getSelectedText()
```
