### ISSUE TITLE
Hello World sample extension testing is failing

### ISSUE THREAD

**Issue by SURYASPR** [redhat-developer/vscode-extension-tester#410]
I'm using 4.2.3 version of vscode extension tester and testing of the simple hello world extension mentioned in  https://developers.redhat.com/blog/2019/11/18/new-tools-for-automating-end-to-end-tests-for-vs-code-extensions#how_it_works
is failing using it. After it launched the new instance, it could not find the Hello World command in command pallette.

When I clicked the 'Extensions' in the new instance, it's showing 0 extensions. That means hello world extension is not installed into the instance even in though in terminal logs it said succesfully installed.

VS Code and system details:
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Please help in fixing it.

**Comment by asitsahoo351** [comment]
I am also facing the same issue

**Comment by odockal** [comment]
Is this issue still actual? Is it something we should take a look or did you manage to find a solution? Thanks.

**Comment by SURYASPR** [comment]
In the new instance if I reload the window, then it's able to find all the installed extensions and then it's working as expected.

**Comment by RovoMe** [comment]
While experimenting with the sample helloworld project I noticed a couple of things:

- `await new ActivityBar().getViewControl('Explorer');` i.e. will look for an `aria-label` in the DOM with the content `Active View Switcher`. If VSCode is run in a language other than English, this lookup will fail as the value here is set depending on the locale specified in VSCode
- `bottomBar-test.ts` fails for me in the current form as the test expects an sole line with the content `hello world!`. My default terminal is tmux with `/bin/bash` as default shell and in this setup I get a line that contains `@hello world!@` back and as such the test here fails. If I replace the `some` call to `some(line => line.includes('hello world!'))` that test passes
- `textEditor-test.ts` did not create a new empty file with the given `create new file` "command" string. On replacing it with `workbench.action.files.newUntitledFile` the new file is created in the editor and the tests can now operate on it. The same holds true for `modalDialog-test.ts`
- `webView-test.ts` should use `extension.webview` as command ID for the `executeCommand(...)` operation and in addition to that also specify that command in the `activationEvents` in the `package.json`

**Comment by djelinek** [comment]
> While experimenting with the sample helloworld project I noticed a couple of things:
> 
> * `await new ActivityBar().getViewControl('Explorer');` i.e. will look for an `aria-label` in the DOM with the content `Active View Switcher`. If VSCode is run in a language other than English, this lookup will fail as the value here is set depending on the locale specified in VSCode
> * `bottomBar-test.ts` fails for me in the current form as the test expects an sole line with the content `hello world!`. My default terminal is tmux with `/bin/bash` as default shell and in this setup I get a line that contains `@hello world!@` back and as such the test here fails. If I replace the `some` call to `some(line => line.includes('hello world!'))` that test passes
> * `textEditor-test.ts` did not create a new empty file with the given `create new file` "command" string. On replacing it with `workbench.action.files.newUntitledFile` the new file is created in the editor and the tests can now operate on it. The same holds true for `modalDialog-test.ts`
> * `webView-test.ts` should use `extension.webview` as command ID for the `executeCommand(...)` operation and in addition to that also specify that command in the `activationEvents` in the `package.json`

nice investigation 🙂 . If you are interested in, feel free to contribute into this project with some improvements for sample-project.

Closing - no issue activity for a long time. Feel free to reopen if needed.
