### ISSUE TITLE
error running extest setup-tests on Windows

### ISSUE THREAD

**Issue by gpsaraiva** [redhat-developer/vscode-extension-tester#423]
I am facing this issue when running the command "extest setup-tests":
> mysql-shell-vscode@1.0.17 e2e-setup
> extest setup-tests

Downloading VS Code from: https://update.code.visualstudio.com/latest/win32-x64-archive/stable
progress: 0/128 (0%)
progress: 53542903/108107739 (49%)
progress: 108107739/108107739 (100%)
Downloaded VS Code into Z:\extension\test-resources\stable.zip
Unpacking VS Code into Z:\extension\test-resources
Error: Cannot move 'vscodeUVkFIW' to a subdirectory of itself, 'Z:\extension\test-resources\VSCode-win32-x64-archive'.
    at Z:\extension\node_modules\vscode-extension-tester\node_modules\fs-extra\lib\util\stat.js:108:17
    at callback (Z:\extension\node_modules\graceful-fs\polyfills.js:299:20)
    at FSReqCallback.oncomplete (node:fs:199:5)

Can you help ?
Thanks

**Comment by mharringADI** [comment]
I ran into this when I had vscode open to the extension directory (I was debugging tests from vscode). Looking at ProcessExplorer, I can see that vscode is holding on to the file handle, preventing extest from renaming the folder.

My "workaround" was to close vscode, run "extest setup-tests" from the command line to download the zip, then open vscode again. This time, running "extest setup-tests" will use the cached values and skip downloading the zip.
