### ISSUE TITLE
Make locators framework independent

### ISSUE THREAD

**Issue by christian-bromann** [redhat-developer/vscode-extension-tester#425]
Hey,

first off, great work on this library. I just started building VSCode extensions and really didn't understand why there was no proper e2e test solution. We are building heavy webview based extensions and this is the only way we can guarantee our extension works e2e.

As the maintainer of [WebdriverIO](https://webdriver.io/) I would love to allow WebdriverIO users to leverage this capability. Given Selenium has a slight different way of building page objects all I really am interested in are the locators. Unfortunately these require `selenium-webdriver` and I wonder if it would be possible to make it independent from it so that I could consume it in my WebdriverIO service.

Happy to do the leg work for it, would just like to get a agreement and some sort of direction.

**Comment by christian-bromann** [comment]
Just as an update: I just released a WebdriverIO service to run VSCode extension tests that was inspired by this project. For now I [ported the locators](https://github.com/webdriverio-community/wdio-vscode-service/blob/main/src/locators/1.37.0.ts) as I didn't want to depend on `selenium-webdriver`. If there is an interest creating a common page locator package that works independently from the test framework / automation library I would love hear. Otherwise I will try to contribute back changes I found in upcoming VSCode versions if time allows.

**Comment by odockal** [comment]
@christian-bromann Hello christian! Let me thank you and give credit to @jrichter1 who is author to this project. 
Let me also to express an apology for a delay before reaching back to you. We are quite occupied with multiple other projects and do not give enough attention to everything we do. 

As of your issue. We discussed the topic and there is should not be a hard argument against moving selenium implementation  from locators towards another part of the library. Though I am not an expert in typescript to find ideal solution.

I will working on some ideas in the days to come. I would be glad for any suggestion you have ;)

**Comment by christian-bromann** [comment]
> I would be glad for any suggestion you have ;)

So I have been porting the [locators](https://github.com/webdriverio-community/wdio-vscode-service/tree/main/src/locators) you have collected over the time and remove the dependency to Selenium. It would be possible to package this up into an extra NPM package the problem though is that these are just string locators and while most of them use the CSS selector strategy, there are some that only WebdriverIO knows to interpret, e.g. `p=Foobar` which WebdriverIO compiles into an xPath.

That said, I am happy to contribute new locators back into this project as I find them which will require no work from your side.
