### ISSUE TITLE
extest fails a "Launching browser ..." with no error message or useful debug information

### ISSUE THREAD

**Issue by ssmall** [redhat-developer/vscode-extension-tester#428]
- **Platform:** macOS Monterey 12.2.1 (darwin/arm64)
- `vscode-extension-tester` version: `4.2.4`

When I run the command `./node_modules/.bin/extest run-tests -c 1.55.0 "./dist/dist/all_tests.js" --mocha_config config.mocharc.js --code_settings "./src/ui-test/settings.json"` I get the following output:

```
Loading mocha configuration from config.mocharc.js
Detected user defined code settings
Writing code settings to REDACTED/test-resources/settings/User/settings.json
Launching browser...
```

and the command fails with exit code 1.

At this point, I am looking for any tips or steps I can try to get further information about what could be failing. The complete lack of an error message means that I don't really know where to start.

Some additional information that may be relevant:

- `./dist` is a symlink
- `./node_modules` is a symlink
- I have verified that the contents of `./dist/dist/all_tests.js` are as expected
- This issue is only happening for me on macOS; I have a Linux developer environment as well and have no issues running the exact same command on the same codebase there.

**Comment by djelinek** [comment]
There is no response for 3 weeks so for now I am closing this issue. 

If you will still need help, please feel free to reopen this issue.
