### ISSUE TITLE
DebugConsoleView getText not working

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#433]
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/995909/160968991-d45303c1-403a-48e2-ba40-efaf88c0f7d9.png">

```js

export async function getsCryptDebugOutput(text: string = ''): Promise<string> {

  return await VSBrowser.instance.driver.wait(async () => {
  
    try {
      const outputView = await new Workbench().getBottomBar().openDebugConsoleView();

      let output = await outputView.getText();
      await sleep(1000);
      if (text) {
        if (output.indexOf(text) > -1) {
          return output;
        } else {
          return ''
        }
      } else {
        return output;
      }
    } catch (error) {
      

    }

    return '';

  }, 120000, `getsCryptDebugOutput timeout text:${text}`)
}
```

**Comment by zhfnjust** [comment]
it seems `openContextMenu` has a issue.

when call `openContextMenu`,   this happend:


<img width="2557" alt="image" src="https://user-images.githubusercontent.com/995909/160973373-3b6bb2e7-1063-4ce5-8305-5368c1fcc4d8.png">

and `outputView.getText()` call `openContextMenu` inside

**Comment by djelinek** [comment]
Hello @zhfnjust do you still facing same issues ? or did you some progress?

**Comment by djelinek** [comment]
There is no response for 3 weeks so for now I am closing this issue. 

If you will still need help, please feel free to reopen this issue.
