### ISSUE TITLE
[🚫 Bug] extester ignores output option from mocarc file

### ISSUE THREAD

**Issue by imeliran** [redhat-developer/vscode-extension-tester#436]
Hello,

I have an issue where I referred the extester command to a custom "mocharc" file as described in the following wiki link:
 https://github.com/redhat-developer/vscode-extension-tester/wiki/Mocha-Configuration

To simplify things here's how my mocharc.json file looks like: 
{
"color": true,
"ui": "bdd",
"reporter": "xunit",
"reporter-option": ["output=doda.xml"]
}

When I run the test using extester command with --mocha_config <path>/<to>/mocharc.json I do see in my console the xunit results format, however the file doda.xml is never created. seems like the code ignore that option.
According to official mochajs starting version 9.1.0 they added the out option of reporter-option as described here:
https://github.com/mochajs/mocha/issues/4607

Does anyone make the test results exported into an external file. 
I need that support for CI integration.
Thanks in advance,

Eliran

**Comment by djelinek** [comment]
Hello, thank you for reporting issue. Unfortunately I was not able to find out information about xunit reporter and its output option. Are you able to point me to some documentation?

also.. are you able to use output parameter using mocha cli directly? which means it is a problem of extest CLI?

**Comment by djelinek** [comment]
closing, in case of follow up questions. Feel free to continue in the thread or reopen a issue 🙂
