### ISSUE TITLE
[MacOS][Bug] Unable to select popup menu item

### ISSUE THREAD

**Issue by unsortedhashsets** [redhat-developer/vscode-extension-tester#444]
**Summary:** 
Unable to select a popup menu item (MacOS)

**Code part:**
```
const item = await findSectionItem(testFolder, `${fileName}.${extension}`);
const menu = await item.openContextMenu();            // <---------------------- Error inside
const option = await menu.getItem(`${startIntegration}`); 
await option?.click();
```
**Expected result:**
1. Select section item 
2. Right-click on the item to open the menu 
3. Select a specific option 
4. Click on the selected function

**Actual result:**

1. Select section item
2. Right-click on the item to open the menu 
3.  Menu opened with error, no object selected, the menu remains open while other tests continue.

**More info:**
- OS - MacOS 12.3.1
- VS code - 1.67

**State:**
![Screenshot from 2022-05-19 12-17-10](https://user-images.githubusercontent.com/46084942/169275810-34318c88-58d1-46ae-b768-782c0b193a21.png)

**Error:**
![Screenshot from 2022-05-18 09-58-17](https://user-images.githubusercontent.com/46084942/169275885-8d7ba2d9-7e9d-433c-aa8a-5ab5e8d33adb.png)

**Comment by unsortedhashsets** [comment]
Same problem with the popup menu in the other (custom) section

**State:**
![Screenshot from 2022-05-19 14-16-23](https://user-images.githubusercontent.com/46084942/169291329-95029015-4663-4724-824d-c55f0e135865.png)

**Error:**
![Screenshot from 2022-05-19 14-25-30](https://user-images.githubusercontent.com/46084942/169292704-72c981cb-8c8f-4df6-8dc6-c3533b963294.png)

**Comment by fjakobs** [comment]
I have the same issue. Does VSCode on OSX use native context menus and if so is there a way to turn it off?

**Comment by vkavitha** [comment]
is there an update on this bug ?is there a workaround to try for getting this work in Mac ?

**Comment by djelinek** [comment]
Hello, this is not supported bug. Please see [know issues](https://github.com/redhat-developer/vscode-extension-tester/blob/main/KNOWN_ISSUES.md#macos-known-limitations-of-native-objects) for more information.
