### ISSUE TITLE
[🚀 Request] `exTester.installFromMarketplace()` can't download platform specific extensions

### ISSUE THREAD

**Issue by CsCherrYY** [redhat-developer/vscode-extension-tester#450]
currently `exTester.installFromMarketplace()` will not download [platform specific](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions) versions of the extension. 

e.g., the `redhat.java` extension releases the platform specific versions since `1.2.0`, now the newest version of the extension is `1.7.0`, but when you invoke `exTester.installFromMarketplace("redhat.java")`, you will get the version `1.1.0`(the last version doesn't adopt platform specific extension)

**Comment by pospisilf** [comment]
Closing as I don't think this issue is relevant anymore. I am currently getting latest available version without any issue. 

If you still think there's problem, please reopen issue and provide more informations about plugin and platform.
