### ISSUE TITLE
Error: stdout maxBuffer length exceeded in mac

### ISSUE THREAD

**Issue by devipv02** [redhat-developer/vscode-extension-tester#46]
Hi,
When the ExTester downloads the vscode zip and unpacks it, an error is thrown.

> UnhandledPromiseRejectionWarning: RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded.

I see in test-resources folder, the unpack process just waits till the size of Visual Studio Code is 199.2 MB every time i try to run the tests. [Actual size of VSCode 1.40 being 236MB]

Adding maxBuffer to '*/node_modules/vscode-extension-tester/out/util/unpack.js' file, line 22 will resolve this issue
`child_process_1.exec(`cd ${target} && unzip ${path.basename(input.toString())}`, {maxBuffer: 1024 * 500}, (err) => {`

If this is not intended, Let me know if there is any other setting i can change this to unpack the VSCode successfully

**Comment by jrichter1** [comment]
Buffer told to behave properly in the new release. If it happens again, feel free to reopen.
