### ISSUE TITLE
fedora: unable to build project using system version of node/npm (16)

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-extension-tester#464]
We discovered that we cannot build the project using system npm on fedora (35 and 36) as it failing with permission errors, and obviously we don't build as root.

```
[ssbarnea@f1 vscode-extension-tester]$ /usr/bin/npm run build

> vscode-extension-tester@4.3.0 prebuild
> npm run prepare-deps


> vscode-extension-tester@4.3.0 prepare-deps
> npm run build-page-objects && npm run build-locators


> vscode-extension-tester@4.3.0 build-page-objects
> cd page-objects && npm i && npm run build


added 65 packages, and audited 66 packages in 1s

found 0 vulnerabilities

> monaco-page-objects@2.0.0 build
> rimraf out/ && tsc


> vscode-extension-tester@4.3.0 build-locators
> cd locators && npm i && npm run build


added 32 packages, and audited 34 packages in 906ms

found 0 vulnerabilities

> vscode-extension-tester-locators@2.0.0 build
> rimraf out/ && tsc


> vscode-extension-tester@4.3.0 build
> npm link ./page-objects ./locators && rimraf out/ && tsc && chmod a+x ./out/cli.js

npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ssbarnea/.npm/_logs/2022-06-29T09_22_38_243Z-debug-0.log
[ssbarnea@f1 vscode-extension-tester]$
```

I mention that this was reproduced on two totally different machines. I can also assert that installing nvm and using it a valid workaround, still... why, why why?! 😭

To my surprise we did not observe this problem on GHA ubuntu-latest runners.

**Comment by odockal** [comment]
@ssbarnea This seems to me more like concrete npm configuration problem on your machine. I am using nvm to run node+npm on Fedora 36 and I have no problems like these.

**Comment by odockal** [comment]
I have found some docs on npm side: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally.
Either use nvm or move the npm's default directory under your home folder.

**Comment by ssbarnea** [comment]
I agree with you that this is not effectively an extest issue but i find it hilarious to not be able to use nodejs on fedora as a normal user, out of the box.

I use `nvm` myself but it is a PITA to install and it does slowdown the shell considerably. No wonder why I see it not recommended by most, usually indicating `asdf` as a better alternative. Still, most people might not really need a node version manager at all.
