### ISSUE TITLE
Support VSCode V1.69 / ChromeDriver 100.0.4896.60

### ISSUE THREAD

**Issue by gigara** [redhat-developer/vscode-extension-tester#466]
Currently getting the below error when we try to run the sample project with the latest version of VSCode.

```
WebDriverError: target frame detached
  (Session info: chrome=100.0.4896.160)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:522:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:589:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:514:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:740:17)
      at async Driver.findElements (node_modules/selenium-webdriver/lib/webdriver.js:1066:17)

```

**Comment by apupier** [comment]
It also happens for our VS Code AtlasMap extension: see https://github.com/jboss-fuse/vscode-atlasmap/runs/7249487937?check_suite_focus=true#step:10:53

**Comment by odockal** [comment]
Seems like a [bug] introduced in Chromium 99.x. Fix is supposed to be included in chrome driver 103.

[bug]: https://bugs.chromium.org/p/chromedriver/issues/detail?id=4048

**Comment by apupier** [comment]
if I understood well, the chrome webdriver is coming from Seleium-webdriver. latest released version is still on version 100 [chrome](https://github.com/SeleniumHQ/selenium/blob/a4995e2c096239b42c373f26498a6c9bb4f2b3e7/common/repositories.bzl#L80)

So we would need a new release of selenium-webdriver? (changed to 103 in trunk https://github.com/SeleniumHQ/selenium/blob/989c5644d3162d1ab90dacd9947d5f7294ae9808/common/repositories.bzl#L80 ) or maybe we can use an older version of selenium-webdriver?

**Comment by odockal** [comment]
I tried to use chromium driver 103 but that was not compatible with vscode 1.69 (using electron 18? with chrome 100.x). But I am trying some workaround, let's me see if that will work.
