### ISSUE TITLE
Parallel mode ?

### ISSUE THREAD

**Issue by gpsaraiva** [redhat-developer/vscode-extension-tester#469]
Hello,

Mocha supports the parallel mode (run tests in parallel). Is this possible on vscode-extension-tester ?
I did tested it using the following configuration:
- add the "parallel": true on my .mocharc.json file
- have 2 .ts files with tests under my tests folder

When I start the tests, the driver object seems to not to be created at all.
browser = VSBrowser.instance;
driver = browser.driver;
driver.takeScreenshot() -> TypeError: Cannot read properties of undefined (reading 'takeScreenshot')

If I removed the "parallel": true flag from my .mocharc.json file, everything works fine.

Thanks

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.
