### ISSUE TITLE
await webview1.switchToFrame();  Throwing Error as -  NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":".//div[starts-with(@id, 'webview-editor')]"}

### ISSUE THREAD

**Issue by ajcrypto** [redhat-developer/vscode-extension-tester#472]
I am trying to switch to webview and I am getting an error. Please find the code below

`        it('Enter details', async function () {
        
       
            const webview1 = new WebView(new EditorView(),By.xpath("//*[text()='Oracle Blockchain Platform - Create 
            Specification']"));
   
            await driver.sleep(2000);
            await driver.actions().move({x:0,y:0,origin:webview1}).perform()
            console.log("Title "+ await webview1.getTitle());   // Oracle Blockchain Platform - Create Specification

            await webview1.switchToFrame();

          const specFileName = await webview1.findWebElement(By.xpath("//input[@type='text' and @id='sp-file-name']"));   
          await specFileName.click();
          await specFileName.sendKeys("FabCarDemoSpecFile");
          await webview1.switchBack();
 

        }).timeout(40000);`

Vscode: 1.66.2
Extest : 4.3.0
Command:
 "ui-test": "npm run compile && extest setup-and-run -c 1.66.2 out/ui-test/*.js"

**Comment by gigara** [comment]
I'm also getting the same when trying to switch back from the webview

**Comment by ajcrypto** [comment]
The following code has resolved my issue, but it's still a pain as again when I am switching to a new tab, gives me similar kind of error

`      await driver.switchTo().frame(driver.findElement(By.xpath("//*[@class='webview ready']")));
        await driver.switchTo().frame(driver.findElement(By.id("active-frame")));`

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.

**Comment by sgotko** [comment]
Issue is still actual for me.
Code like this: 
```javascript
  const editorView = new EditorView();
  await editorView.openEditor('Webview title');
  const webview = new WebView();
  await webview.switchToFrame();
```
Causes this:
```shell
NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":".//div[starts-with(@id, 'webview-editor')]"}
  (Session info: chrome=108.0.5359.215)
      at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:524:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:601:13)
      at Executor.execute (node_modules\selenium-webdriver\lib\http.js:529:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Driver.execute (node_modules\selenium-webdriver\lib\webdriver.js:745:17)
``` 

VSCode verson: 1.81.1
Extester version: 4.4.1
