### ISSUE TITLE
findSetting() returns undefined, but shows the setting on a screenshot

### ISSUE THREAD

**Issue by YuggothFungi** [redhat-developer/vscode-extension-tester#473]
Hi, first of all, many thanks for your hard work. It really helps a lot. Here's where I've stumbled, please guide me through, I tried to debug, but lacked the knowledge of interconnection between components obviously.

I am trying to reach the setting of an extension, so I go with workbench.openSettings() for a promised SettingsEditor object, but then I get _undefined_ after findSetting() call. Screenshot shows me that the setting is there and findSetting actually sends search string and it returns the only possible setting. 
Terminal reports the following message that seems to refer to the issue:
`[17692:0722/104829.208:INFO:CONSOLE(602)] "%c WARN color: #993 Settings pattern "keyboard.*" doesn't match any settings", source: vscode-file://vscode-app/d:/Work/vscode-test-example/svacer-extension/test-resources/VSCode-win32-x64-archive/resources/app/out/vs/workbench/workbench.desktop.main.js (602)`
![Suite 2 Check Svacer settings](https://user-images.githubusercontent.com/25670616/180386848-605ed2e4-655b-4797-8e76-e1316a937b7b.png)

What is strange to me, is that I get **pending** id here 
      const workbench = new Workbench();
      const settingsEditor = await workbench.openSettings();
      console.log(settingsEditor);
:
```
SettingsEditor {
  driver_: Driver {
    session_: Promise { [Session] },
    executor_: Executor { customCommands_: [Map], log_: [Logger], w3c: true },
    fileDetector_: null,
    onQuit_: [Function: onQuit],
    authenticatorId_: null
  },
  id_: Promise { <pending> },
  enclosingItem: EditorView...
```

While, for example, when I access ViewControl from ActivityBar, I get the id right away
      const activityBar = new ActivityBar();
      const control = await activityBar?.getViewControl('Explorer');
      console.log(control);
:
```
ViewControl {
  driver_: Driver {
    session_: Promise { [Session] },
    executor_: Executor { customCommands_: [Map], log_: [Logger], w3c: true },
    fileDetector_: null,
    onQuit_: [Function: onQuit],
    authenticatorId_: null
  },
  id_: Promise { 'f566adef-4bb2-4601-b008-e5bed943a075' },
  enclosingItem: ActivityBar...
```

VS code version: 1.69.2 (user setup)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by YuggothFungi** [comment]
Suggest probably to change to enhancement.
The reason why findSetting() does not return the correct object is the order of arguments. For instance, if I pass "findSetting('Project', 'Svacer', 'Project Settings')" the object will be returned correctly.

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.
