### ISSUE TITLE
[Request] New feature: add webview context to SideBarView

### ISSUE THREAD

**Issue by YuggothFungi** [redhat-developer/vscode-extension-tester#477]
I am trying to automate UI testing of the extension for VS Code that has certain actions brought out into the SideBarView section as webview. One of the sections in Explorer is a self written HTML, which I want to access via webdriver.

If I understand correctly, the page source won't have that html code (and only reference a webview tag), so I have to switch to that webview somehow. That could be done using WebView API, but it only exposes webviews that are located (to the best of my understanding) inside the EditorView of VS code. Thus, the webview that is called from the SideBarView section remains unreachable to selenium webdriver. 

I guess there should be an abstract way to access webview context without tying to ExplorerView object.

**Comment by djelinek** [comment]
Duplicates #394
