### ISSUE TITLE
Add placeholder min/max values to --code_version option

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-extension-tester#480]
As new versions vscode appear often and they are likely to break extest, we need to expose the minimum and the maximum version of vscode that is supported by current version, so users of this tool can use them in their testing pipelines.

**Comment by odockal** [comment]
@ssbarnea Definitely makes sense. But to makes it clear, what does min/max refer to exactly? I am looking at it this way:
`-c max` would be referring to the latest supported version of vscode that extester supports/is tested, right?
`-c min` is then a minimal version that is supported/tested officially. 
`-c x.y.z` is concrete version user wants to use (is not restricted by us at all, simply must be version that can be downloaded from vscode server).
And without parameter we are referring to the latest vscode version that might not work with latest extester.

does it sound right?

**Comment by ssbarnea** [comment]
It does sound right. I guess that we will need to add a scheduled pipeline that creates a PR for bumping the max to the latest version published. This will allow us to know when it gets broken and to quickly bump max when it just works.

**Comment by djelinek** [comment]
@odockal it would be nice also mention this new feature at extester WIKI page
