### ISSUE TITLE
How to get the current VSBrowser instance?

### ISSUE THREAD

**Issue by aduhanx1** [redhat-developer/vscode-extension-tester#481]
Is it possible to get the current VSBrowser instance with `vscode-extension-tester`? My tests need to involve the opening of a workspace file, which I need to be opened as soon as the browser is launched, in order for my subsequent tests to pass. I tried using `VSBrowser.instance.openResources([pathToWorkspace])`; however, this opens a new VSBrowser instance after the test has ended.

I was also wondering if there's any setting that allows the workspace to be opened before any test is launched, but so far haven't been able to find anything that can solve my problem.

**Comment by odockal** [comment]
@aduhanx1 Hello, I believe that openResource method should truly open new vscode instance, but extension-tester should simply continue working with that instance without problems. We have a test running just fine with it (unless it is new bug) [1]. What VScode version are we talking about? What extension-tester are you using?

As of the second part of your question, I believe that we could implement the feature of opening some workspace on vscode start up. I will create a new issue for that.

[1]: https://github.com/redhat-developer/vscode-extension-tester/blob/master/test/test-project/src/test/xsideBar/scmView-test.ts#L12

**Comment by aduhanx1** [comment]
Hi @odockal , thank you for your reply. Based on the example you provided, I managed to fix the issue by adding more delay to the `before` function. My working code looks like this:

```typescript
describe('My Tests', () => {
    before(async function context() {
        this.timeout(90000);
        await VSBrowser.instance.openResources(path.join('src', 'tests', 'resources', 'my-workspace'));
        await new Promise((res) => { setTimeout(res, 6000); });    // added delay here
    });

    it('Title bar test', async () => {
        const titleBar = new TitleBar();
        const title = await titleBar.getTitle();
        expect(title).equals('Get Started - my-workspace - Visual Studio Code');
    });
});
```
