### ISSUE TITLE
How to launch each test file in a new VS Code instance?

### ISSUE THREAD

**Issue by ada-la** [redhat-developer/vscode-extension-tester#484]
Is it possible to do this? I'd like to launch and run each file in a new instance so that the tests have a clean slate each time.

**Comment by odockal** [comment]
I do not thing that we have designed the extester to work this way. It based on mocha and is spawned per suite. But I believe that you could probably workaround this using one of two approaches. On github actions (for example) you could parametrized npm script to run ui tests on different configuration (test cases) or you could probably chain multiple setup-and-run commands in npm script - I am not sure this will work, you could probably try.

**Comment by mlorinc** [comment]
Also you could call [Extester](https://github.com/redhat-developer/vscode-extension-tester/blob/995f141ac0e599775dd6cc7367ddce8364cbb283/src/extester.ts#L32)#runTests multiple times and pass file path as argument. However this approach does not work on all environments for reasons reported in #485.

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.
