### ISSUE TITLE
Tests in ui-test are not passing

### ISSUE THREAD

**Issue by jeffb-sfdc** [redhat-developer/vscode-extension-tester#486]
I'm evaluating vscode-extension-tester, and it looks promising.  Maybe these are known issues, but I'm running in to some issues getting the stock tests to pass.

To level set here, I'm running locally on Mac OS X 12.5 (x64)
Chrome 104.0.5112.101 (Official Build) (x86_64)
Visual Studio Code 1.70.2 (Universal)
(if you need any other information about my environment, just let me know)

I ran `npm install --save-dev vscode-extension-tester`
I then cloned `vscode-extension-tester`
I the cd into `vscode-extension-tester/sample-projects/` and built

I'm attempting to get the tests in activityBar-test.ts and bottomBar-test.ts to pass.  I'm running each test (file) individually, and here is a list of the issues I'm encountering, with just these two files so far:

activityBar-test.ts
The tests in activityBar-test.ts seems to be very flakey - sometimes they pass, sometime some tests fail.  I found that if I debug a failing test, it always passes.  My "fix" was to add a pause.  At line 13 in activityBar-test.ts I added:
```
    beforeEach(async () => {
        await new Promise(resolve => setTimeout((resolve), 2000));
    });
```
I tried pausing for 1000ms, but tests still sometimes failed.  (the error I got was, "StaleElementReferenceError: stale element reference: element is not attached to the page document").

So far, a pause of 2 seconds for each test seems to fix the issue, but IMHO this isn't a great fix - it's unreliable (what happens when the tests run on a slow build machine?  Bump the pause up to pausing 10 seconds each test?), and adds overhead - the time to run and validate increases by 2 seconds for every test written.

bottomBar-test.ts
The 'There are no warnings' test fails.

UPDATE: Please see https://github.com/redhat-developer/vscode-extension-tester/issues/487

<s>
I stepped through this test, and it's expecting 0 warnings.  I don't know about you, but on my machine, when problems.ts is opened, there are 12 warnings.  One fix is to get rid of the 'There are no warnings' test and replace with:

        // now we can look at the warning markers
        it('Warning markers are displayed', async () => {
            // generally, there are 3 marker types (warning, error, and file - file just contains other markers though)
            // we want to see the warnings
            const errors = await view.getAllMarkers(MarkerType.Warning);

            // assert that there are errors (there should be 12 warnings in the file)
            expect(errors.length).equals(12);
        });
...but this seems odd - I'd expected all of the tests checked in to pass, and with this one particular test (checking for 0 warnings) is not the results of what I'm seeing, and instead should check for the existence of 12 warnings. Unless that's not the case, and that's not what you see locally...
</s>

The 'Filtering works' test fails.  When I step through and debug this test, the call to:

```
await view.setFilter('aa');
```
...doesn't work.  I can step over this and switch back to the instance of VS Code that's being debugged, and see that the filter isn't set.  I can also manually set the filter to 'aa' at this point, and then the test passes.  I stepped into `setFilter()` and took a look... off hand I didn't see anything wrong and it seems like it should work, and no exceptions are being thrown, but yet the filter isn't being set to 'aa'.

Are these known issues?

**Comment by odockal** [comment]
@jeffb-sfdc hello, thanks for reporting, for now we plan to work on VScode 1.70 support (https://github.com/redhat-developer/vscode-extension-tester/issues/479), I believe the one you are using when running `npm run ui-test`. You could probably make it pass by updating the npm script command with `-c 1.69.2` which will download older version of vscode.

**Comment by jeffb-sfdc** [comment]
Thanks @odockal I tried using 1.69.2, but I still get the same issue.  I have a fix for some of these and will create a PR.  Being new to this project I don't know if my changes will be "the right" changes... it will be interesting to see what the feedback on my PRs is.

**Comment by djelinek** [comment]
Closing - sample-projects tests should be working now
