### ISSUE TITLE
Some sittings cannot be found using settingsEditor.findSetting()

### ISSUE THREAD

**Issue by zcervink** [redhat-developer/vscode-extension-tester#496]
- the following 2 code examples make `setting` variable to be undefined:

```
const settingsEditor = await new Workbench().openSettings();
const setting = await settingsEditor.findSetting('Yaml: Schemas', 'Extensions');
```
```
const settingsEditor = await new Workbench().openSettings();
const setting = await settingsEditor.findSetting('Yaml: Schemas');
```

- tests inside extension tester works as expected, so some settings can be found

**Comment by odockal** [comment]
@zcervink It seems that you are using it wrong. The correct form would be:
```
const setting = await settingsEditor.findSetting('Schemas', 'Yaml');
```
and for the example of `Editor: Auto Save` I used when we were talking about it should be (and works):
```
const setting = await settingsEditor.findSetting('Auto Save', 'Files');
```

We should fix readme for Settings and remove mentioned of `Editor: Auto Save` and replace it with `Files: Auto Save`.

**Comment by ashish-gawali-adi** [comment]
I have a setting something like this: `Extension-id > Div: Path` and I using the code as: 
```
const setting = await settingsEditor.findSetting(
        "Path",
        "Extension-id",
        "Div"
      );
```

The setting is resolving to `undefined`.
