### ISSUE TITLE
"after all" hook errors out when uninstalling vscode-extension-tester.api-handler

### ISSUE THREAD

**Issue by quoctruong** [redhat-developer/vscode-extension-tester#50]
I get the following error when the test suite was trying to uninstall the api-handler:
```
Shutting down the browser
Extension 'vscode-extension-tester.api-handler' is not installed.
Make sure you use the full extension ID, including the publisher, e.g.: ms-vscode.csharp
  1) "after all" hook

  1 passing (32s)
  1 failing

  1) "after all" hook:
     Error: Command failed: set ELECTRON_RUN_AS_NODE=1 && "<redacted>\VSCode-win32-x64-archive\Code.exe" "<redacted>\app\out\cli.js" --uninstall-extension "vscode-extension-tester.api-handler"
```

Also the command that I run is: `extest run-tests *.js`

Is it because the test suite closes the VSCode instance before trying to uninstall the api-handler?

**Comment by caleteeter** [comment]
I ran into the same issue.  I found this hard coded value in the uninstall util but not in the install.  Is this just a left over artifact?

https://github.com/redhat-developer/vscode-extension-tester/blob/d9e21b8866a825b76932956bf7fa9035b45250eb/src/util/codeUtil.ts#L136

**Comment by jrichter1** [comment]
The api-handler is supposed to be installed during setup, but since you're not running the setup it's not there. And I totally forgot to account for that.

**Comment by jrichter1** [comment]
I've moved the code around so `run-tests` command can use the `api-handler` as well. The error should no longer appear.
