### ISSUE TITLE
[🚫 Bug] BottomBarPanel().openProblemsView() is not properly working

### ISSUE THREAD

**Issue by djelinek** [redhat-developer/vscode-extension-tester#505]
The method is not correctly working for win/linux
The Problems view is not opened and the clipboard contains 'a' in buffer

```
TimeoutError: Waiting until element is visible
    Wait timed out after 5198ms
```

**Comment by YuggothFungi** [comment]
I came across the same issue and noticed that if you first call TerminalView, for instance, in any other test, then ProblemsView is opened without any issue:
    const terminalView = await new BottomBarPanel().openTerminalView();
    const problemsView = await new BottomBarPanel().openProblemsView(); // now it works.

**Comment by djelinek** [comment]
fixed

**Comment by djelinek** [comment]
closing for now - cannot reproduce
