### ISSUE TITLE
Option for disabling all other vscode extensions

### ISSUE THREAD

**Issue by gnikit** [redhat-developer/vscode-extension-tester#510]
Is there an easy way to pass to vscode the `--disable-extensions` flag before the tests are run? My local vscode extensions are interfering with the some of the tests e.g. fetching a notification.

The only workaround I could think of was using the Insiders build for code development and then having a barebones installation of the Stable vscode with no extensions installed (or vice versa).

**Comment by mlorinc** [comment]
Hi,

Have you tried option `--extensions_dir <dir>`? I usually create new `test-extensions` directory and delete it after run.
