### ISSUE TITLE
Upgrade from 4.4.0 to 5.0.0 or newer results in error

### ISSUE THREAD

**Issue by zdrapela** [redhat-developer/vscode-extension-tester#519]
## Expected Behavior
- Tried to bump the version of ExTester used in [kie-tools](https://github.com/kiegroup/kie-tools) from 4.4.0 to 5.0.0 (_packages that use ExTester are listed bellow_). 
- Similar change worked with previous versions, so no problems were expected.

## Actual Behavior
- After changing the version to 5.0.0, running integrations tests of vscode extension results in following error:
![image](https://user-images.githubusercontent.com/61500440/193817600-8b2e5b6a-6e54-4239-b15b-4b594b7d322d.png)
- Using latest versions of [`vsce`](https://www.npmjs.com/package/vsce) and [`vscode-test`](https://www.npmjs.com/package/@vscode/test-electron) didn't help.

## Steps to Reproduce the Problem
  1. Checkout to this branch: [zdrapela-patch-3](https://github.com/zdrapela/kie-tools/tree/zdrapela-patch-3) or perform [these changes](https://github.com/kiegroup/kie-tools/compare/main...zdrapela:kie-tools:zdrapela-patch-3) on main branch.
  2. `cd kie-tools`
  3. `pnpm bootstrap`
  4. `pnpm -F vscode-extension-pack-kogito-kie-editors... build:dev`
  5. `export KIE_TOOLS_BUILD__runIntegrationTests=true`
  6. `pnpm -F vscode-extension-pack-kogito-kie-editors test:it`

Broader description located [here](https://github.com/kiegroup/kie-tools#build-from-source). 
ExTester is used in following packages:
- [vscode-extension-pack-kogito-kie-editors](https://github.com/kiegroup/kie-tools/tree/main/packages/vscode-extension-pack-kogito-kie-editors) (steps to reproduce are for this package)
- [vscode-extension-serverless-workflow-editor](https://github.com/zdrapela/kie-tools/tree/main/packages/vscode-extension-serverless-workflow-editor)
- [vscode-extension-yard-editor](https://github.com/zdrapela/kie-tools/tree/main/packages/vscode-extension-yard-editor)

## Specifications

  - VSCode version: 1.69.2 and 1.71.2 (same problem with both versions)
  - ExTester version: 5.0.0
  - Platform: 
      - [x] Linux (RHEL 8.6)
      - [ ] macOS
      - [ ] Windows

**Comment by domhanak** [comment]
I guess this is relevant too - https://github.com/microsoft/vscode-vsce/issues/421

**Comment by domhanak** [comment]
Read around some articles and it seems there is a viable workaround for pnpm with `vsce package`
I guess this line - https://github.com/redhat-developer/vscode-extension-tester/blob/f9eb420cd2afdf07d8ce674791a60ba880ff0017/src/util/codeUtil.ts#L197 
should consider adding `--no-dependencies` when `pnpm` is used?

**Comment by zdrapela** [comment]
The issue persists in 5.2.0

**Comment by zdrapela** [comment]
I can confirm, that workaround suggested by @domhanak works. I consider it useful to add the option to use `--no-dependencies` with ExTester.

There is also another workaround, that works for us. You can use `package.json` to tell `vsce` to don't use dependencies by setting the following:
```
{
  ...
  "vsce": {
    "dependencies": false
  }
}
```
I use that in [this PR](https://github.com/kiegroup/kie-tools/pull/1369). This was discussed at `vsce` issues [439](https://github.com/microsoft/vscode-vsce/issues/439) and [742](https://github.com/microsoft/vscode-vsce/issues/742)

I am still not sure, why it worked before and after upgrading to 5.0.0 it stopped working. But otherwise, we can continue to use newer versions of ExTester.

**Comment by zdrapela** [comment]
The problem was caused by `vsce`. The `vscode-extension-tester` works when `vsce` version 2.9.2 or lower is used. In `vsce` version 2.9.3 a [minor change was introduced](https://github.com/microsoft/vscode-vsce/commit/d68e2f7947069dd26c6aa425523cee8372dbd73a#diff-7ed38395221a42cf5b3ccf6754c4ef75e4713032fd607cbac04ce51849597466L188), that removed the check for `yarn.lock` file and tried to get `yarn` dependencies (`yarn list --prod --json`) even when the `yarn.lock` file is not present:
```if (await exists(path.join(cwd, 'yarn.lock'))) {...```

That is why we have to now disable the dependencies. By doing so, we achieve the same behavior of `vsce` that was before achieved by the `if` statement.

**Comment by zdrapela** [comment]
Adding the option to use `--no-dependencies` with ExTester would be nice to have, but since there is a viable workaround with `package.json` that can do the same, I am closing the issue.
