### ISSUE TITLE
On Mac: WebDriverError: unknown error: Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#52]
I am getting the following error when I try to run the helloworld-sample project's ui-tests on Mac 10.14.6

```
WebDriverError: unknown error: Chrome failed to start: exited abnormally
  (unknown error: unable to discover open pages)
  (The process started from chrome location /Users/davidkwon/Documents/Github_Repositories/vscode-extension-tester/sample-projects/helloworld-sample/test-resources/Visual Studio Code.app/Contents/MacOS/Electron is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Mac OS X 10.14.6 x86_64)
```

Here is the complete output: https://gist.github.com/xorye/5ac9a3c52ce68b5565ceee5381b2ae76

To reproduce this issue:
On Mac OS, clone this repository
`cd vscode-extension-tester/sample-projects/helloworld-sample`
`npm install`
`npm run ui-test`

On my machine, this error happens about 90 percent of the time. I tried running `npm run ui-test` around 20 times, it succeeded only twice.

I noticed that when running `npm run ui-test`, this process:  (scroll sideways to see the full line)
```
UID   PID  PPID        F CPU PRI NI       SZ    RSS WCHAN     S             ADDR TTY           TIME CMD
501  4451  4449     6006   0   0  0        0      0 -      Z+                  0 ttys001    0:00.00 (Electron)
```
Exists for less than a second, and then dissappears on the next `ps -l` output.

**Comment by xorye** [comment]
Sorry, this issue seems to have been a problem with my machine, although I am not 100% sure.
I can't reproduce this error anymore.

**Comment by jrichter1** [comment]
I haven't had any luck reproducing this, I have a couple of questions:
 1. what version of code are you running against?
 2. does this keep happening even after deleting the whole `test-resources` folder?

**Comment by jrichter1** [comment]
I've run into this when setting up mac machines on Travis. It seems to be tied to the storage folder (the test-resources one by default). Might be a permissions issue, I still can't really figure it out.

Anyway, I could work around this by switching to a folder that I just created in the user home directory. Something like adding this flag `-s ~/test`. Give it a shot if you will, hopefully it will help.

**Comment by immanishbainsla** [comment]
I am also facing same error as https://gist.github.com/xorye/5ac9a3c52ce68b5565ceee5381b2ae76
but runs all tests successfully when os is set to [ubuntu-latest](https://github.com/immanishbainsla/fabric8-analytics-vscode-extension/blob/master/.github/workflows/ui-test.yml#:~:text=The%20type,ubuntu-latest) only it works fine 
but after adding [matrix](https://github.com/immanishbainsla/fabric8-analytics-vscode-extension/blob/master/.github/workflows/ui-test.yml#:~:text=strategy,matrix.os) it runs into this error 

failed tests with matrix : https://github.com/immanishbainsla/fabric8-analytics-vscode-extension/runs/2555732071?check_suite_focus=true
success tests with ubuntu-latest only : https://github.com/immanishbainsla/fabric8-analytics-vscode-extension/actions/runs/831512635

nodejs version : 14.16.1
vscode version : 1.50.0

**Comment by jrichter1** [comment]
Interesting, as if chromedriver didn't like the path that gets generated by the matrix setup.

Might be worth trying to store everything on a simpler path, like user home (or a new folder inside user home rather). There is a `-s` flag in `extest` that lets you change the storage directory. If that helps, we may at least know why this error could be happening.

**Comment by immanishbainsla** [comment]
failed again

try 1: '-s test-resources/'
test-script line : "ui-test": "npm install && npm run test-compile && npx extest setup-and-run -i -s test-resources ./out/ui-test/allTestsSuite.js -o settings.json"

ci-test-link : https://github.com/immanishbainsla/fabric8-analytics-vscode-extension/runs/2562945519?check_suite_focus=true
 in this test windows and ubuntu works fine but macos fails
Error : 
```
Detected user defined code settings
Writing code settings to /Users/runner/work/fabric8-analytics-vscode-extension/fabric8-analytics-vscode-extension/test-resources/settings/User/settings.json
Launching browser...
  1) "before all" hook in "{root}"
  2) "after all" hook in "{root}"

  0 passing (1s)
  2 failing

  1) "before all" hook in "{root}":
     WebDriverError: unknown error: Chrome failed to start: exited abnormally.
  (chrome not reachable)
  (The process started from chrome location /Users/runner/work/fabric8-analytics-vscode-extension/fabric8-analytics-vscode-extension/test-resources/Visual Studio Code.app/Contents/MacOS/Electron is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=89.0.4389.23 (61b08ee2c50024bab004e48d2b1b083cdbdac579-refs/branch-heads/4389@{#294}),platform=Mac OS X 10.15.7 x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /Users/runner/work/fabric8-analytics-vscode-extension/fabric8-analytics-vscode-extension/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  From: Task: WebDriver.createSession()
      at Function.createSession (node_modules/selenium-webdriver/lib/webdriver.js:769:24)
      at Function.createSession (node_modules/selenium-webdriver/chrome.js:761:15)
      at createDriver (node_modules/selenium-webdriver/index.js:170:33)
      at Builder.build (node_modules/selenium-webdriver/index.js:642:16)
      at VSBrowser.<anonymous> (node_modules/vscode-extension-tester/out/browser.js:73:18)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/browser.js:5:58)

  2) "after all" hook in "{root}":
     TypeError: Cannot read property 'manage' of undefined
      at VSBrowser.<anonymous> (node_modules/vscode-extension-tester/out/browser.js:110:48)
      at Generator.next (<anonymous>)
      at /Users/runner/work/fabric8-analytics-vscode-extension/fabric8-analytics-vscode-extension/node_modules/vscode-extension-tester/out/browser.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/vscode-extension-tester/out/browser.js:4:12)
      at VSBrowser.quit (node_modules/vscode-extension-tester/out/browser.js:109:16)
      at Context.<anonymous> (node_modules/vscode-extension-tester/out/suite/runner.js:77:35)
      at Generator.next (<anonymous>)
      at /Users/runner/work/fabric8-analytics-vscode-extension/fabric8-analytics-vscode-extension/node_modules/vscode-extension-tester/out/suite/runner.js:8:71
      at new Promise (<anonymous>)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fabric8-analytics@0.3.4 ui-test: `npm install && npm run test-compile && npx extest setup-and-run -i -s test-resources/ ./out/ui-test/allTestsSuite.js -o settings.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fabric8-analytics@0.3.4 ui-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/runner/.npm/_logs/2021-05-12T05_31_49_929Z-debug.log
Error: The process '/usr/local/bin/npm' failed with exit code 1
```

======================================================================================

try 2: '-s .'
test-script line : "ui-test": "npm install && npm run test-compile && npx extest setup-and-run -i -s . ./out/ui-test/allTestsSuite.js -o settings.json"

ci-test-link : https://github.com/immanishbainsla/fabric8-analytics-vscode-extension/runs/2562784404?check_suite_focus=true

PS : this is failing for ubuntu not macos (by changing to "-s .")
Error : 
```
test/vscontext.mock.ts(22,3): error TS2322: Type '{ extensionPath: string; storagePath: string; logPath: string; secrets: undefined; extension: undefined; subscriptions: any; workspaceState: DummyMemento; globalState: DummyMemento; ... 7 more ...; globalStorageUri: undefined; }' is not assignable to type 'ExtensionContext'.
  Object literal may only specify known properties, and 'secrets' does not exist in type 'ExtensionContext'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fabric8-analytics@0.3.4 test-compile: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fabric8-analytics@0.3.4 test-compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-12T05_04_22_439Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! fabric8-analytics@0.3.4 ui-test: `npm install && npm run test-compile && npx extest setup-and-run -i -s . ./out/ui-test/allTestsSuite.js -o settings.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the fabric8-analytics@0.3.4 ui-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-05-12T05_04_22_461Z-debug.log
/usr/bin/bash /home/runner/work/_actions/GabrielBB/xvfb-action/v1.5/cleanup.sh
Killing the following xvfb processes: 1858
Error: The process '/usr/bin/xvfb-run' failed with exit code 2
```

**Comment by jrichter1** [comment]
@immanishbainsla what I had in mind was putting the storage somewhere outside the working directory, specifically on a shorter path than is default for the matrix job. Doing `-s .` is just going to dump vscode into your cwd and tsc is going to try to compile it (and fail).

**Comment by immanishbainsla** [comment]
you mean something like "-s ../../" wiil change dir to "/Users/runner/work/"?

**Comment by jrichter1** [comment]
something like that, or `-s ~/whatever` for linux, something to shorten the path :)

**Comment by immanishbainsla** [comment]
thanks Jan. "../" this worked for me.

**Comment by jrichter1** [comment]
This should be mitigated in 4.2.3.
