### ISSUE TITLE
TerminalView.gettext() does not work for vscode 1.72.x

### ISSUE THREAD

**Issue by LareinaJi** [redhat-developer/vscode-extension-tester#521]
> for vscode 1.72.x, there are some change to terminal, as described in https://code.visualstudio.com/docs/terminal/basics

> in the function getText(),

 getText() {
        return __awaiter(this, void 0, void 0, function* () {
            const workbench = new __1.Workbench();
            yield workbench.executeCommand('terminal select all');
            yield workbench.getDriver().sleep(500);
            yield workbench.executeCommand('terminal copy selection');
            yield workbench.getDriver().sleep(500);
            const text = clipboard.readSync();
            clipboard.writeSync('');
            return text;
        });
    }

the command ('terminal copy selection') has been removed from vscode 1.72.x

according to doc above: "Copying is done automatically on selection when terminal.integrated.copyOnSelection is enabled.", we can rewrite this function.

## Specifications

  - VSCode version: 1.72.0
  - ExTester version: ???
  - Platform: 
      - [ ] Linux
      - [ ] macOS
      - [ ] Windows

**Comment by djelinek** [comment]
actually the `TerminalView.getText()` is already implemented a quite differently. Please see https://github.com/redhat-developer/vscode-extension-tester/blob/master/page-objects/src/components/bottomBar/Views.ts#L122

This change will be available in next extester release
