### ISSUE TITLE
Do we have an option to specify which mocha reporter to use in Extester.runTests()?

### ISSUE THREAD

**Issue by devipv02** [redhat-developer/vscode-extension-tester#53]
Currently we get the test output in console when we run Extester.runTests(). It would be great if we can allow a reporter (Eg: mocha-jenkins-reporter) to the runner.ts file so that we can capture the output in a file and integrate with Jenkins build.

**Comment by jrichter1** [comment]
I haven't explicitly done anything to change mocha options. Maybe [mocha config](https://mochajs.org/#configuring-mocha-nodejs) will work.

**Comment by jrichter1** [comment]
Turns out mocha config did not work out of the box, so I added it explicitly. It should work in a very similar fashion though. Check out the [wiki page](https://github.com/redhat-developer/vscode-extension-tester/wiki/Mocha-Configuration) for details.
