### ISSUE TITLE
Can't get text from terminal view

### ISSUE THREAD

**Issue by ayachensiyuan** [redhat-developer/vscode-extension-tester#537]
When I tried to retrieve the contents of terminal, I use ```const text = await terminalView?.getText()``` to get the context, but context is empty. I found that it was only happened on my mac PC. There was no problem when I ran it on github action. 

> Tag each new issue with relevant **LABELS** (*bug*, *enhancement*, etc.).

> Replace all **???** with relevant information.

## Expected Behavior
- text value should have context.
## Actual Behavior
- text value is empty.
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/67082457/205003839-91e0e3ad-ef6b-4aeb-92ad-b9875ce2024b.png">
<img width="969" alt="image" src="https://user-images.githubusercontent.com/67082457/205003948-c59b329d-cc0f-453a-a203-ffda7ecf209b.png">

## Steps to Reproduce the Problem

  1. ???
  2. ???
  3. ???

## Specifications

  - VSCode version: 1.73.1 
  - ExTester version: 'ms-teams-vscode-extension-4.1.3
  - Platform: 
      - [ v13.0.1 ] macOS

**Comment by vkavitha** [comment]
Any update on this issue? Is this specific to MacOS , as the implementation seems to be using OpenContextMenu which is nt working in MAC ? any workaround for getting the terminal view text is much appreciated

**Comment by LongOddCode** [comment]
Any update?

**Comment by djelinek** [comment]
Hello there, sorry for late response. I am currently working on solution for this. Stay tuned. Hopefully the fix should be delivered in next release.

**Comment by djelinek** [comment]
see https://github.com/redhat-developer/vscode-extension-tester/wiki/TerminalView#get-text with description how to make it working on macOS

fix released in extester-5.5.0
