### ISSUE TITLE
Input.getText() and Input.clearText() not working on Mac

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#54]
On macOS Mojave 10.14.6, the Input.getText() and Input.clearText() functions are not working.

The issue seems to be because `await input.sendKeys(Key.chord(Input.ctlKey, 'a'), Key.chord(Input.ctlKey, 'c'));` and `await input.sendKeys(Key.chord(Input.ctlKey, 'a'), Key.BACK_SPACE);` is not working on Mac.

This issue seems to be a problem with selenium and chrome, where sending command and another key doesn't work:
 https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/5919

For `Input.getText()` how about doing this? :
```
return await this.findElement(Input.locators.Input.inputBox)
            .findElement(Input.locators.Input.input).getAttribute('value');
```

Using `getAttribute('value')` to get the value of the `<input>` is working for my Linux machine and macOS.

**Comment by jrichter1** [comment]
Good point with `getText`, `value` is definitely easier to use. As far as clear goes, I wanted to use webdriver's own `clear` method, but that breaks the inputbox for some reason.

I'm trying out a way to handle inputs without the command key, and no clipboard either. Could you try if #58 fixes the issue for you?

**Comment by xorye** [comment]
Thank you, I will try to look into it this week

**Comment by jrichter1** [comment]
I took the liberty of not waiting and pushed the changes. Tests are now green, but if you come across the problem again, feel free to reopen/open an issue.

**Comment by noorshiblee** [comment]
@jrichter1  I am on ubuntu 20.04 with latest version of this lib and latest vscode(1.58,2) also. I am facing this issue on my machine.
When i open the input box, it has some path exist already . First i need to clear and set my new text. But not working . see my sample code 

```
`const input = await InputBox.create();
await input.click();
await input.clear();

await input.sendKeys(Key.chord(Key.SHIFT, Key.HOME), Key.BACK_SPACE);
//await input.setText(Key.CONTROL + "a");
//await input.setText(Key.DELETE);
//await input.setText(path.resolve(__dirname, '..'));
await input.setText('/tools/Appdir/version');
await input.confirm();
`

I tried with several combination with sendkeys as u see in my commented code. But nothing works.... :-(
Any suggestion. Thanks a lot in advance.

**Comment by jrichter1** [comment]
@noorshiblee the intended way would just be to use `setText`, because it will replace any text already present.
```typescript
const input = await InputBox.create();
await input.setText('/tools/Appdir/version/');
await input.confirm();
```
But since you seem to have some trouble with that, would you mind describing the symptoms? Is the original text left hanging there? Does the input end up empty instead? Is it stuck with a completely different text/path?

**Comment by noorshiblee** [comment]
Thanks for the reply. I tried with your suggested way also.As you can see in the image,  the original text left hanging there. No empty or different path.

![image](https://user-images.githubusercontent.com/16698852/127332676-24a652a5-046f-42bd-9f99-022898b622c1.png)

**Comment by jrichter1** [comment]
@noorshiblee I ended up trying in a freshly installed ubuntu 20.04 box, with an empty project. Made a test file that looks like this:
```typescript
import { Workbench, InputBox } from 'vscode-extension-tester';

describe('Tests', () => {
    it('Test', async () => {
        await new Workbench().executeCommand('file: open folder');
        await new Promise(res => setTimeout(res, 1000));
        const input = await InputBox.create();
        await input.setText('/path/to/folder');
        await input.confirm();
    }).timeout(15000);
});
```
And it opened the folder successfully. Using latest version of both the framework and vscode. I can't quite see what is wrong at your end.

**Comment by noorshiblee** [comment]
Hello @jrichter1 

Sorry for my long late response. What you have mentioned here also works for me. But my scenario is bit different. 

I don't need to open workbench. Using webdriver,  i click on a web element on my webpage and it opens that input box where i need to give folder destination. 
After that i use below code: 
      
        const input = await InputBox.create();
        await input.setText('/path/to/folder');
        await input.confirm();


which doesn't work.

Error is: ```Waiting for element to be located By(css selector, .quick-input-widget)```

Thanks
