### ISSUE TITLE
Cannot use Werbview.switchToFrame with VS Code 1.74+ when there ar several webview opened

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#545]
## Expected Behavior
- Support several Webviews opened like in previous versions

## Actual Behavior
- the switchToFrame is nto working

## Steps to Reproduce the Problem

  1. see https://github.com/redhat-developer/vscode-extension-tester/pull/544

## Specifications

  - VSCode version: 1.74
  - ExTester version: 5.2.1
  - Platform: 
      - [ ] Linux
      - [ ] macOS
      - [ ] Windows

**Comment by djelinek** [comment]
Merged
