### ISSUE TITLE
[🚫 Bug] Tests of test-project/ are affecting each other

### ISSUE THREAD

**Issue by djelinek** [redhat-developer/vscode-extension-tester#637]
> Define the issue title **short** and **most specific** to the problem.

> Replace all **'???'** with relevant information.

**Describe the bug** 
- The problem is that each test class should be independant

**Steps to Reproduce**
1. ???
2. ???
3. ???

**Expected behavior**
- each test class could be executed separately

**Environment information**
 - OS:
    - [x] Windows
    - [x] Linux
    - [x] macOS
- VSCode version:  ???
- ExTester version:  ???
- Node (npm) version:  ???

**Attachments**
> If applicable, add screenshots, logs, examples... to help explain your problem.

**Comment by pospisilf** [comment]
Tests were improved. Overall stability is much better now. If some follow up unstability will show up, please open new issue for it.
