### ISSUE TITLE
Input.clear() not working in special cases

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#68]
In an input box, if the current text is highlighted by dragging the mouse cursor from left to right (and only left to right, this part is important), then `Input.clear()` does not work.

From the source code, it looks like `Input.clear()` is trying to select all text by doing `Shift + Home`, but if the whole text is already highlighted from left to right, `Shift + Home` will unhighlight everything instead.

From what I tried, `Shift + Home` does not highlight all text if the cursor isn't on the far right, if the right-most character isn't highlighted, or if text was highlighted from left to right.

For the time being, I could prevent this issue by sending `Key.RIGHT` until the cursor is all the way to the right, before calling `Input.clear()`

**Comment by jrichter1** [comment]
Fixed in #69 and released in 2.4.0
