### ISSUE TITLE
[🚫 Bug] Clicks not being intercepted in SideBarView and BottomBarPannel

### ISSUE THREAD

**Issue by roguib** [redhat-developer/vscode-extension-tester#742]
I'm not able to perform a click action on native VS Code web elements. When calling `await WebElement.click()` I can see the element being selected but the action that should happen on a click is not performed. For example, consider the following code:

```ts
const bottomBar = new BottomBarPanel();
const problemsView = await bottomBar.openProblemsView();

const markers = await problemsView.getAllVisibleMarkers(MarkerType.Any);
for (const marker of markers) {
  if(await marker.getText() === 'Lorem') {
    console.log('item clicked'); // from the logs I can see this code is being executed
    await marker.click(); // Only selects the problem row, but doesn't click it
  }
}
```

Same issue happens to me with the ExplorerBar:
```ts
const control = await new ActivityBar().getViewControl('Explorer');
await control.openView();

const gruntfile = await control.findElement(By.xpath("//span[text()='Gruntfile.js']"));
await gruntfile.click();
```

Here is how it looks like:
<img width="240" alt="Screenshot 2023-04-18 at 09 31 00" src="https://user-images.githubusercontent.com/30463479/232704244-eb97f4f0-7438-4d03-ad49-6737cfed1396.png">

 I'd expect that the actual file would be opened in the Editor on a click action, not just being selected in the file tree.

The problem might be on my side, but I can't actually point where the actual problem is with my code.

**Expected behavior**
- Peforming a click on a vscode element should not only only select the item but also should perform the action that comes with it (e.g opening the file in the editor).

**Environment information**
 - OS:
    - [ ] Windows
    - [ ] Linux
    - [X] macOS
- VSCode version:  1.77.3
- ExTester version:  5.5.2
- Node (npm) version:  16.16.0 (8.11.0)

**Comment by djelinek** [comment]
Hello @roguib,
I will be working on your issue. Is this still valid problem for you? Did you tried with latest extester 5.6.0 and latest VS Code 1.78.2?

**Comment by djelinek** [comment]
regarding to Explorer issue you described... Could you please try to use extester implementation to open/click on item inside side view? Code below should work as expected for you. Could you try please?

```
await (await new ActivityBar().getViewControl('Explorer') as ViewControl).openView();
const section = await new SideBarView().getContent().getSection('<open Workspace/folder name>') as ViewSection;
await section.openItem('Gruntfile.js');
```

**Comment by djelinek** [comment]
regarding to `markers`. What exactly are you trying to achieve by click on that element? I tried manually and click on marker performs expand/collapse for me? Is that what are you looking for?

in case yes, you can use `await marker.toggleExpand(true);`

**Comment by roguib** [comment]
Thanks for taking a look @djelinek.

> What exactly are you trying to achieve by click on that element?

We have a problems view that lists some missing configuration files the user has to update in order to use the extension. When the user clicks in one of those problems it opens a file in vscode where they can make the necessary changes. 

When using this code snippet:
```ts
const markers = await problemsView.getAllVisibleMarkers(MarkerType.Any);
for (const marker of markers) {
  if(await marker.getText() === 'Info: Missing Fusion Application base URL at line 1 and character 1.') {
    await marker.click();
  }
}
```
the problem row gets highlighted, in a similar way it was happening with the grunt file in the file tree navigator, but the file isn't opened. If during the test i click on that same problem, the file gets opened without any issue, so I thought it was something related either with my code or with the library.

**Comment by djelinek** [comment]
Hello @roguib, I am sorry I did not have enough capacity and lost a track of this isue. Do you still having same issues? in case you have, could you please try this code as tmp workaround?

```typescript
const markers = await problemsView.getAllVisibleMarkers(MarkerType.Any);
for (const marker of markers) {
  const markerText = await (await marker.findElement(By.className('monaco-highlighted-label'))).getText();
  if(markerText === 'Info: Text.') {
    await marker.click();
  }
}
```

please let me know if it helps, there seems to be more problems in Markers implementation I need to fix 🙂
