### ISSUE TITLE
[🚫 Bug] methods manage() and isInstaled() from ExtensionsViewItem checks wrong "button" WebElement if found more then one extension

### ISSUE THREAD

**Issue by nallikaea** [redhat-developer/vscode-extension-tester#767]
> Define the issue title **short** and **most specific** to the problem.

> Replace all **'???'** with relevant information.

**Describe the bug** 
- Trying to automate test case using monaco-page-object library v.3.1.0. It should get recommended extension list from file, and check if it installed and enabled in DevWorkspace. There can be found more then one extension by keyword, for ex. "java", so test script will filter found WebElements by publisher and return one. After it try to extend methods `element.isInstaled()` to check if it is true and `element.manage()` to check if "Enable" menu item is inactive. But inside the methods conditions for buttons `ExtensionsViewItem.locators.ExtensionsViewItem.install` and `ExtensionsViewItem.locators.ExtensionsViewItem.manage` provide checks not for the found item but for the first one.

Connected issues: 
https://github.com/eclipse/che/issues/22176
Test script code:
https://github.com/eclipse/che/blob/main/tests/e2e/specs/dashboard-samples/RecomendedExtentions.spec.ts

**Steps to Reproduce**
1. Open Extension View
2. Try to find some extensions with keyword "Java"
3. Try to get context menu with method manage() for the second found item

**Actual behavior**
```
 manage() {
        return __awaiter(this, void 0, void 0, function* () {
            yield this.getDriver().wait(selenium_webdriver_1.until.elementLocated(ExtensionsViewItem.locators.ExtensionsViewItem.manage), 1000);
            const button = yield this.enclosingItem.findElement(ExtensionsViewItem.locators.ExtensionsViewItem.manage);
            yield this.getDriver().executeScript('arguments[0].style.border=\'2px solid red\'', button);
            if ((yield button.getAttribute('class')).indexOf('disabled') > -1) {
                throw new Error(`Extension '${yield this.getTitle()}' is not installed`);
            }
            return this.openContextMenu();
        });
```
 **if ((yield button.getAttribute('class')).indexOf('disabled') > -1)** condition checks button for the first element;

**Expected behavior**
-  **if ((yield button.getAttribute('class')).indexOf('disabled') > -1)** condition checks button for the second element;

**Environment information**
 - OS:
    - [ ] Windows
    - [x] Linux
    - [ ] macOS
- VSCode version:  1.78
- ExTester version:  3.1.0
- Version: 1.78.0
- Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
- Node (npm) version:  v16.18.1

**Attachments**
> If applicable, add screenshots, logs, examples... to help explain your problem.
Screencast with highlights: 
[Screencast from 15.05.23 14:30:08.webm](https://github.com/redhat-developer/vscode-extension-tester/assets/72726250/4cdca81f-f6e3-4271-8903-bc418b351147)
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/8198/console
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/8198/artifact/test-repo/tests/e2e/

**Comment by djelinek** [comment]
Hello @Daybringer how is it going with this issue? Any update or you need some help? 🙂

**Comment by nallikaea** [comment]
@djelinek @Daybringer Hi, I want to inquire about this task status. Do you need any help from my side?

**Comment by djelinek** [comment]
No idea, I was also asking about the status.

Could you please share with us @Daybringer ? 🙂

**Comment by dmytro-ndp** [comment]
@djelinek : it seems @Daybringer couldn't finish the task. 
Would you, please, continue working on it?

**Comment by pospisilf** [comment]
You can use ExtensionsViewSection for work with Marketplace. It's necessary to give full name of Item to get specific item, then results of isInstalled() or manage() will be correct and related to specific extension. 

```
const view = await ((await new ActivityBar().getViewControl('Extensions')) as ViewControl).openView();

// wait until section is properly loaded
await view.getDriver().wait(async function () {
    return (await view.getContent().getSections()).length > 0;
});
section = (await view.getContent().getSection('Installed')) as ExtensionsViewSection; // replace Installed by required section

// wait until extension is loaded
await section.getDriver().wait(async function () {
    item = (await section.findItem(`Gradle for Java`)) as ExtensionsViewItem; // replace Gradle for Java with required extension
    return item !== undefined;
});

console.log(`isInstalled(): ${await item.isInstalled()}`); 
 ```
 
 For work with  Recommended section simply replace Installed with Recommended like
 ```
section = (await view.getContent().getSection('Recommended')) as ExtensionsViewSection;
```
