### ISSUE TITLE
Support for editor groups

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#77]
It seems like [`EditorView`](https://github.com/redhat-developer/vscode-extension-tester/wiki/EditorView) only supports the first [editor group](https://code.visualstudio.com/assets/docs/getstarted/userinterface/hero.png).

It would be great if there was a way to select/view all editor groups.

**Comment by jrichter1** [comment]
Editor groups added in 2.5.0 :)
