### ISSUE TITLE
`Error: Cannot find module 'opencv4nodejs'` when running on RHEL node on Jenkins

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/vscode-extension-tester#80]
```
[Pipeline] {
[Pipeline] sh
+ npm run ui-test

> vscode-openshift-connector@0.1.4 ui-test /mnt/hudson_workspace/workspace/vscode-openshift-build
> extest setup-and-run out/test/ui/*.test.js

/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/cv.js:14
  throw err
  ^

Error: Cannot find module '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/build/Release/opencv4nodejs'
Require stack:
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/cv.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/opencv4nodejs.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/lib/provider/opencv/image-writer.class.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/lib/adapter/vision.adapter.class.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/index.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/webdriver/native/openDialog.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/webdriver/native/dialogHandler.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/extester.js
- /mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/cv.js:11:8)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/cv.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/opencv4nodejs-prebuilt/lib/opencv4nodejs.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/lib/provider/opencv/image-writer.class.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/lib/adapter/vision.adapter.class.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/@nut-tree/nut-js/dist/index.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/webdriver/native/openDialog.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/webdriver/native/dialogHandler.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/extester.js',
    '/mnt/hudson_workspace/workspace/vscode-openshift-build/node_modules/vscode-extension-tester/out/cli.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-openshift-connector@0.1.4 ui-test: `extest setup-and-run out/test/ui/*.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vscode-openshift-connector@0.1.4 ui-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hudson/.npm/_logs/2020-03-13T19_44_59_967Z-debug.log

[Pipeline] }
Terminating xvnc.
```

**Comment by devipv02** [comment]
Do we have any solution for this. I too get the same error when 'npm install' is performed on Jenkins.
`13:48:27  [INFO] Installed npm locally.
13:48:27  [INFO] 
13:48:27  [INFO] --- frontend-maven-plugin:1.6:npm (npm install) @ script-debugger-test ---
13:48:27  [INFO] Running 'npm install' in /home/jenkins/agent/workspace/thunderdome/iron_dome_run_test_p/script-debugger-test
13:48:28  [WARNING] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
13:48:36  [INFO] 
13:48:36  [INFO] > opencv4nodejs-prebuilt@5.3.0 install /home/jenkins/agent/workspace/code-test/node_modules/opencv4nodejs-prebuilt
13:48:36  [INFO] > prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
13:48:36  [INFO] 
13:48:36  [ERROR] sh: prebuild-install: command not found
13:48:36  [ERROR] module.js:478
13:48:36  [ERROR]     throw err;
13:48:36  [ERROR]     ^
13:48:36  [ERROR] 
13:48:36  [ERROR] Error: Cannot find module '/home/jenkins/agent/workspace/code-test/node_modules/opencv4nodejs-prebuilt/install/dependencies.js'
13:48:36  [ERROR]     at Function.Module._resolveFilename (module.js:476:15)
13:48:36  [ERROR]     at Function.Module._load (module.js:424:25)
13:48:36  [ERROR]     at Module.runMain (module.js:611:10)
13:48:36  [ERROR]     at run (bootstrap_node.js:394:7)
13:48:36  [ERROR]     at startup (bootstrap_node.js:160:9)
13:48:36  [ERROR]     at bootstrap_node.js:507:3
13:48:36  [ERROR] npm ERR! code ELIFECYCLE
13:48:36  [ERROR] npm ERR! errno 1
13:48:36  [ERROR] npm ERR! opencv4nodejs-prebuilt@5.3.0 install: `prebuild-install || (node ./install/dependencies.js && node ./install/install.js)`
13:48:36  [ERROR] npm ERR! Exit status 1
13:48:36  [ERROR] npm ERR! 
13:48:36  [ERROR] npm ERR! Failed at the opencv4nodejs-prebuilt@5.3.0 install script.
13:48:36  [ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
13:48:36  [ERROR] 
13:48:36  [ERROR] npm ERR! A complete log of this run can be found in:
13:48:36  [ERROR] npm ERR!     /root/.npm/_logs/2020-04-04T08_18_35_270Z-debug.log
`

**Comment by jrichter1** [comment]
`opencv4nodejs` is a native module, as such it is being handled by [node-gyp](https://github.com/nodejs/node-gyp).
AFAIK, `node-gyp` needs Python (both version 2 and 3 seem to work) and a C/C++ compiler (GCC for example) to operate. Having both installed on your machine should let you build the project.

**Comment by jrichter1** [comment]
The native module is being deprecated, recommend not using going forward. Use simple dialogs instead.
