### ISSUE TITLE
Inputbox's create function does not have a field to pass a timeout

### ISSUE THREAD

**Issue by infiniteregrets** [redhat-developer/vscode-extension-tester#821]
For my use case, I need to wait more than the hardcoded timeout i.e. 5000 ms as it usually just times out before the input box shows up. This would help control flakiness in our tests by setting a custom timeout and would a be a good addition to the API

**Comment by infiniteregrets** [comment]
@djelinek When should the next release be expected?

**Comment by djelinek** [comment]
@infiniteregrets I would like to release during next week. Probably on the beginning (Mon/Tue) in case everything goes well.
