### ISSUE TITLE
[Request] Add support for Node 18 LTS

### ISSUE THREAD

**Issue by djelinek** [redhat-developer/vscode-extension-tester#851]
> Define the issue title **short** and **most specific** to the problem.

> Replace all **'???'** with relevant information.

**What is the feature you are missing?**
- ???

**Could you provide some example of usage?**
- ???

**Comment by djelinek** [comment]
![image](https://github.com/redhat-developer/vscode-extension-tester/assets/18696866/78eb01aa-0159-48a0-9a81-0f9dcf2cd244)

**Comment by apupier** [comment]
Current failure with Node 18 https://github.com/redhat-developer/vscode-extension-tester/actions/runs/6119824012/job/16610513154?pr=930#step:5:123 :

```
  1) "before all" hook in "{root}":
     Error: Server terminated early with status 2
      at /home/runner/work/vscode-extension-tester/vscode-extension-tester/node_modules/selenium-webdriver/remote/index.js:260:24
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by djelinek** [comment]
Latest working NodeJS version with vscode-extension-tester / selenium-webdriver is NodeJS <=18.15.0
