### ISSUE TITLE
[🚀 Request] Running tests in headless mode

### ISSUE THREAD

**Issue by alii-gator** [redhat-developer/vscode-extension-tester#86]
I am going through the documentation, but couldn't find any tips on how to configure the framework to run in headless mode? Is it even possible?

**Comment by jrichter1** [comment]
To my knowledge, headless mode is disabled for VS Code (chromium `--headless` flag actually does nothing). Unless there is some hack I'm not aware of, I don't think this will be possible.

Currently, the best way of getting the window off your screen is to use a virtual frame buffer (works great on linux, not too sure about other systems though).

**Comment by DonJayamanne** [comment]
Hi engineer from python extension,  we managed to get this (headless) working when using puppeteer, ie running vscode in headless mode. 
Infact it was something we ran on our ci pipelines (on azure pipelines, on mac, Linux and windows). 

The code is no longer there however it's in the commit history, we removed it from the phon extension as it wasn't getting used.

**Comment by gpsaraiva** [comment]
hi [DonJayamanne](https://github.com/DonJayamanne) can you provide me the code to run on headless mode please ?
thank you

**Comment by djelinek** [comment]
https://www.selenium.dev/blog/2023/headless-is-going-away/#how-can-i-set-headless-mode-from-now-on

**Comment by deribaucourt** [comment]
Hi, sorry for the late reply but this topic is one of the first to come up on Google for this kind of issues.
I was able to run VSCode tests in the headless GitHub action environment. See https://github.com/savoirfairelinux/vscode-bitbake/pull/30/commits/a1660424a0ab6ab40cfb16af09aa87270eba9636

**Comment by djelinek** [comment]
currently not possible with selenium-webdriver

**Comment by lppedd** [comment]
> currently not possible with selenium-webdriver

Wondering if something has changed since last year, or if this is still the status quo.

**Comment by lppedd** [comment]
Nevermind, I've read your last comment in #1787, it's unfortunate!
