### ISSUE TITLE
[Bug] Exception trying to discover chromedriver version: error sending request for url

### ISSUE THREAD

**Issue by gpsaraiva** [redhat-developer/vscode-extension-tester#894]
I started seeing this issue when executing the tests:

PS C:\workspace\ClientQA\Shell_UI\Pipeline_Run_Ext_tests\shell-plugins\gui\extension\tests\e2e> npm run e2e-tests -- -s C:\Users\james\test-resources-db\ -e C:\Users\james\test-resources-db\ext\ -f -o vscode_settings.json ./output/tests/ui-db.js

> e2e-tests@1.0.0 e2e-tests
> extest run-tests -s C:\Users\james\test-resources-db\ -e C:\Users\james\test-resources-db\ext\ -f -o vscode_settings.json ./output/tests/ui-db.js

Loading mocha configuration from C:\workspace\ClientQA\Shell_UI\Pipeline_Run_Ext_tests\shell-plugins\gui\extension\tests\e2e\.mocharc.json

Detected user defined code settings
Writing code settings to C:\Users\james\test-resources-db\settings\User\settings.json
Launching browser...
Selenium Manager binary found at C:\workspace\ClientQA\Shell_UI\Pipeline_Run_Ext_tests\shell-plugins\gui\extension\tests\e2e\node_modules\selenium-webdriver\bin\windows\selenium-manager.exe
Exception trying to discover chromedriver version: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
Driver path: C:\Users\james\test-resources-db\chromedriver.exe
Browser path: "C:\Users\james\test-resources-db\VSCode-win32-x64-archive\Code.exe"
  1) "before all" hook in "{root}"
  2) "after all" hook in "{root}"

  0 passing (1m)
  2 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 45000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (node:internal/timers:569:17)
      at process.processTimers (node:internal/timers:512:7)

**Environment information**
 - OS:
    - [X ] Windows
    - [ ] Linux
    - [ ] macOS
- VSCode version:  1.78.2
- ExTester version:  5.6.0 and above
- Node (npm) version:  9.5.1

Note that I am running these tests on a Windows VM within a corporate network. (It requires a proxy to communicate to the outside). I find this a weird behavior since I am using the "-f" flag (offline mode). VSCode and chromedriver were downloaded correctly using the vscode-extension-tester scripts.

**Comment by gpsaraiva** [comment]
Ok, I found that it's related to this: https://github.com/SeleniumHQ/selenium/issues/12481

**Comment by knightq** [comment]
> I am facing similar issue. I am on chromedriver 118.0.5993.70 and selenium==4.10.0 and I get this error when I execute my robotframework script - Exception trying to discover chromedriver version: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: dns error: No such host is known. (os error 11001)
> 
> Any help to resolve would be great, Thank you

Same problem here @GitAnusha93, have you resolved?

**Comment by VirajThale** [comment]
Info: 
Chrome version : 120.0.6099.225 
driver chrome : 120.0.6099.109
Platform : Windows Remote desktop 
framework : Python 
Selenium ver: selenium-server-4.12.0.jar 

Facing this issue while running selenium test project could you help me on how can we disable to send to check chrome version or driver version in between the 7 testcase sometime it will failed with exception as given below:
- Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)

Sometimes selenium fail to execute driver and you have to press any key on cmd prompt to execute browser opening.

Regards, 
Thanks

**Comment by djelinek** [comment]
@GitAnusha93 I am sorry but I do not have any experience on `Robot` framework. For me the link you have mentioned is working fine.

I would like to help but I feel I do not know how.

The initial problem was hopefully resolved. It was problem with newer version of selenium-webdriver which was by default using `Selenium Manager`. That was bypassed and we are not leveraging this Selenium feature.

**I would suggest to retry with latest ExTester v7.2.0 and NodeJS 18.x**

In case of still having issues, please feel free to open new Bug were you can provide more information and steps to reproduce.

Thank you!

**Comment by justATester3939** [comment]
I have similar issue:
[ WARN ] Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json)
09:31:51  [ WARN ] Error sending stats to Plausible: error sending request for url (https://plausible.io/api/event)

**Comment by plo750** [comment]
Hello,
Same issue with version of chrome driver 127.0.6533.88 (r1313161)

[WARN (+88.64s)] Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: Une tentative de connexion a échoué car le parti connecté n’a pas répondu convenablement au-delà d’une certaine durée ou une connexion établie a échoué car l’hôte de connexion n’a pas répondu. (os error 10060)
[ WARN ] Exception managing chrome: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: tcp connect error: Une tentative de connexion a �chou� car le parti connect� n�a pas r�pondu convenablement au-del� d�une certaine dur�e ou une connexion �tablie a �chou� car l�h�te de connexion n�a pas r�pondu. (os error 10060)

With selenium library: robotframework-seleniumlibrary 6.2.0

Thanks for your help

**Comment by djelinek** [comment]
> robotframework-seleniumlibrary

Hello, I am sorry, could you please specify your usecase and problem you are having with ExTester? I do not see connection with `robotframework-seleniumlibrary` and also I do not understand from where is coming the attempt to get chromderiver 127.x.x.x because latest VS Code 1.92 is build on 124.x.x.x and earlier VS Code releases are using chromedriver <124.x.x.x
