### ISSUE TITLE
 [Bug] TextEditor#toggleBreakpoint does not work for multiple breakpoints

### ISSUE THREAD

**Issue by c3danielxu** [redhat-developer/vscode-extension-tester#922]
**Describe the bug** 
- TextEditor#toggleBreakpoint does not work for multiple breakpoints

**Steps to Reproduce**
1. With an editor open, use the following code:
```js
const editor = new TextEditor();
await editor.toggleBreakpoint(1);
await editor.toggleBreakpoint(2);
```
2. Observe that the first toggle breakpoint works
3. Observe that the second toggle breakpoint removes the first breakpoint instead of adding a new breakpoint

**Expected behavior**
- The editor should have two breakpoints

**Environment information**
 - OS:
    - [ ] Windows
    - [ ] Linux
    - [x] macOS
- VSCode version:  1.81.1
- ExTester version:  5.9.1
- Node (npm) version: v16.15.1 (npm 8.11.0)

**Attachments**
When I stepped through the code, I saw that the first `toggleBreakpoint` would correct click on line 479. The second `toggleBreakpoint` clicked on line 472 which removed the first breakpoint. I logged the `id_` field for both iterations in the debug console and saw they had the same PromiseResult which seems to mean they were the same object.

<img width="1493" alt="vscodebreakpoint" src="https://github.com/redhat-developer/vscode-extension-tester/assets/111001237/26935b19-fae4-4196-8cc6-396311e9f925">

**Comment by djelinek** [comment]
Duplicates #904 

Hello @c3danielxu thank you for reporting this issue. I am closing it in favour of already reported same issue. so please keep track on issue-904
