### ISSUE TITLE
Provide test job on Insider build

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#94]
it will allow to detect early compatibility issues. It is especially useful as VS Code upgrades are automatic by default so most VS Code extension are trying to test against latest available version (and it would be interesting for them to test also on insiders)

**Comment by jrichter1** [comment]
If I recall correctly, there is a way to switch to insider build, but I haven't tried it for months. I'll have to check if it even works with in the current version.

**Comment by apupier** [comment]
seems to be `-t insider`

https://github.com/redhat-developer/vscode-extension-tester/blob/7d33a84218879bb835b5c0c8e089d501e79809dc/src/cli.ts#L14

**Comment by jrichter1** [comment]
it's broken anyway :(

**Comment by jrichter1** [comment]
I've fixed using the insider builds. Got a travis build set up for latest insider build here: 
https://github.com/redhat-developer/vscode-extension-tester/tree/insider

**Comment by apupier** [comment]
Travis is no more used.
The GitHub Actiosn deosn't seem to have an Insider job https://github.com/redhat-developer/vscode-extension-tester/tree/master/.github/workflows
