### ISSUE TITLE
[🚫 Bug] Running order is wrong when running multiple test in multiple files

### ISSUE THREAD

**Issue by simple00-ji** [redhat-developer/vscode-extension-tester#979]
### Describe the bug

with latest version 5.10.0， when trying to run  running multiple test in multiple files, it will run them in reverse order 
 I  want to run with the order _setup-> createProject-> dbuildProject with the command:
$ extest run-tests "out/test/systemtest/{_setup,createProject,dbuildProject}.js"
but It run in the order dbuildProject -> createProject -> _setup

with 5.9.1, the issue does not exist.

### Steps to reproduce

```Shell
1. create 2 ts, one with name _setup.ts, the other with a.ts
2. build them and run with the command
   extest run-tests "{_setup,a}.js"
```

### Logs

```Shell
$ extest run-tests "out/test/systemtest/{_setup,createProject,dbuildProject}.js"

Writing code settings to /5Aarea/repos/devcode_ci/test-resources/settings/User/settings.json
Launching browser...
Browser ready in 5548 ms
Launching tests...
  Build Projects Tests
    1) DevStudio Build project

  Create Project Tests
    2) "before all" hook for "DevStudio Create project"

  Prepare Test Environment
```

### Operating System

Ubuntu 20.04

### Visual Studio Code

1.83.1

### vscode-extension-tester

5.10.0

### NodeJS

18.15.0

### npm

9.5.0

**Comment by djelinek** [comment]
Hello, thank you for reporting the issue. Actually it seems evrything working as expected now. If you need to execute your tests in predefined order you can. eg. for example you have provided it should looks like:

```
extest run-tests '_setup.js' 'a.js' 
```

In case of any other issues, please feel free to contact me.

**Comment by simple00-ji** [comment]
the command "extest run-tests '_setup.js' 'a.js'  "  does not work here
To run multiple files, the only command  I can use  is _extest run-tests  {_setup,a}.js"_  just as https://github.com/redhat-developer/vscode-extension-tester/issues/151 mentioned.
anyway, with 5.10.0, to workaround this issue, I just reverse the js files:  such as if I want to run it with _setup-> createProject-> dbuildProject   order,  the command is modified to: _extest run-tests "out/test/systemtest/{dbuildProject,createProject,_setup}.js"_

**Comment by djelinek** [comment]
Thank you for your reply @simple00-ji 

It should work that way, we are using it in many other projects. We have implemented to consume more files as glob patterns few versions ago. 

see `extest run-tests` API - [here](https://github.com/redhat-developer/vscode-extension-tester/blob/main/src/cli.ts#L73)
and also example used by our test-project [here](https://github.com/redhat-developer/vscode-extension-tester/blob/main/test/test-project/package.json#L160)
