### ISSUE TITLE
[🚫 Bug] Failed to write a test for a user webview

### ISSUE THREAD

**Issue by AndreyMoskalev565** [redhat-developer/vscode-extension-tester#993]
### Describe the bug

Hi! We wanted to use the library to test our extension, however, the findElement/findElements and findWebElement/findWebElements methods could not find our panel elements. By default, the panel is located at the bottom of VS Code. We tried moving the panel to the editor area, as well as reproducing an example from the [documentation](https://github.com/redhat-developer/vscode-extension-tester/wiki/WebView) and an[ example from the repository](https://github.com/redhat-developer/vscode-extension-tester/blob/main/sample-projects/helloworld-sample/src/ui-test/webView-test.ts), but to no avail. We may have done something wrong. Could you please make sure that our panel is testable, for example, by implementing there the emulation of a button click and send us an example? Your help would be greatly appreciated.

Our extension is called "PVS-Studio" and is available in the marketplace. The panel we are trying to test looks like this:
 
![image](https://github.com/redhat-developer/vscode-extension-tester/assets/119808569/53305247-2198-4de1-9548-fbd7cd51b421)

If the panel is hidden, it can be shown using the "PVS-Studio: Show Window" command from the command palette.

### Steps to reproduce

```Shell
-
```

### Logs

```Shell
-
```

### Operating System

Windows 11

### Visual Studio Code

1.83.0

### vscode-extension-tester

5.10.0

### NodeJS

16.20.1

### npm

8.19.4

**Comment by djelinek** [comment]
Hello @AndreyMoskalev565 , I can help you in case you will provide me some easy example extension which will implement the webview with button you are not able to test click there.

I can then setup and provide some functional test for you into that example project.

**Comment by AndreyMoskalev565** [comment]
Hello! I would like to make sure if the library can be used to test a specific webview which is used in the "PVS-Studio" extension. Could you tell me please if the extension source code is necessary for a basic test, such as clicking a button? I suppose it is sufficient to understand the HTML structure of the webview. You can see this structure by calling the "Developer: Open Webview Developer Tools" command in the command palette. Also, you may need to have the id of the tested webview — "PVSPanel".

**Comment by djelinek** [comment]
> Hello! I would like to make sure if the library can be used to test a specific webview which is used in the ["PVS-Studio"](https://marketplace.visualstudio.com/items?itemName=EvgeniyRyzhkov.pvs-studio-vscode) extension. Could you tell me please if the extension source code is necessary for a basic test, such as clicking a button? I suppose it is sufficient to understand the HTML structure of the webview. You can see this structure by calling the "Developer: Open Webview Developer Tools" command in the command palette. Also, you may need to have the id of the tested webview — "PVSPanel".

- extester framework is able to test every webview, you just need to switch into webview before start to looking for web elements in there
- extension source code is not necessary, you are able to install directly from marketplace

- I was not primary asking for source code or anything. I was trying to encourage you to prepare some example test project which will implement the extester API to setup tests and install extension, also containing tests you are trying to execute against your extension webview - this would allow me to only help and focus on tests implementation part, not also the whole setup of environment of test project.. 
 
anyway.. I can try with some existing project we have.. I will share with you later

**Comment by djelinek** [comment]
your extension is implementing Webview View VS Code API, which we will support on extester side from next release (coming soon..)

**Comment by djelinek** [comment]
here is an example of code for your extension view https://github.com/djelinek/vscode-extension-tester/commit/7aae7a40dbefb9a974e878e15bb9267e0ce4754b
